---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gossa
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: pldubouilh/gossa
      tag: v0.1.8.0
    nameOverride: gossa
    env:
      FOLLOW_SYMLINKS: "true"
      READONLY: "true"
      SKIP_HIDDEN_FILE: "true"
      UID: "1000"
      GID: "1000"
      HOST: "0.0.0.0"
      PORT: "8001"
      PREFIX: "/"
      DATADIR: "/data"
    service:
      main:
        ports:
          http:
            port: 8001
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"

          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: "cdn.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "cdn.${SECRET_PUBLIC_DOMAIN}"
            secretName: gossa-tls
    persistence:
      data:
        enabled: true
        type: custom
        mountPath: /data
        readOnly: true
        volumeSpec:
          nfs:
            server: "neon.${SECRET_PRIVATE_DOMAIN}"
            path: /mnt/user/appdata/cdn
