---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.2.26
      pullPolicy: IfNotPresent
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Run UniFi as root
      RUNAS_UID0: "false"
      # -- Specify the user ID the application will run as
      UNIFI_UID: "999"
      # -- Specify the group ID the application will run as
      UNIFI_GID: "999"
      # -- Java Virtual Machine (JVM) initial, and minimum, heap size
      # Unset value means there is no lower limit
      JVM_INIT_HEAP_SIZE:
      # -- Java Virtual Machine (JVM) maximum heap size
      # For larger installations a larger value is recommended.
      # For memory constrained system this value can be lowered.
      JVM_MAX_HEAP_SIZE: 1024M
      # # -- External MongoDB URI
      # DB_URI:  # mongodb://unifi-mongodb:27017/unifi
      # STATDB_URI:  # mongodb://unifi-mongodb:27017/unifi_stat
      # DB_NAME:  # unifi

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: unifi
        externalIPs:
          - 10.10.10.252
        externalTrafficPolicy: Local
    ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/enable: "true"
      # -- Enable and configure settings for the captive portal ingress under this key.
      # @default -- See values.yaml
      portal:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        ingressClassName: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/enable: "true"
        hosts:
          -  ## Host address. Helm template can be passed.
            host: "ui.${SECRET_DOMAIN}"
            paths:
              -  ## Path. Helm template can be passed.
                path: /
                ## Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
        tls:
          - secretName: unifi-web-tls
            hosts:
              - "ui.${SECRET_DOMAIN}"
      # -- Configure persistence settings for the chart under this key.
      # @default -- See values.yaml
      persistence:
      data:
        enabled: true
        mountPath: /unifi
        size: 20Gi
        storageClass: "longhorn"
