# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:DUu3iO2/Zg==,iv:ykccrXP3q10Gq7JPY4OA6+FzmsfJUzEwgLvzYIz4l+I=,tag:Bq0PZZ1G6Wddd03tUXIBkQ==,type:str]
    admin-password: ENC[AES256_GCM,data:QTwvt5K4hsiAPTBsJEU=,iv:eW9d11YEzUQ3jEfNwWFXn2tH/C9pN0cgrLBbm6eQjBU=,tag:rl+7NsmSGby9PQu4R5aZpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dGNVdFdnMnNLUllEN3Yy
            SkQ5akZYUVVaOTBlUlplbUE1aTVhNElzcGk4Cm12S1VkczQxUUFGbVFvc0ZHMFdr
            QWhabDJsRUhDOE5VMnErcTlHNTE3VEUKLS0tIFNpSTBURDhTekZtb0d4ZkQyTmlo
            bTIydkRlYlBBajBuYi95YzJ5UUxwb2cKqizotFqBmjDO7VeiNjLhe+CxTbdP46eT
            RpzQLvAQkSb9nnO1OxP55QZXfBKEl/Rq79Zy3Hd/eF0JB39qoSMi/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-18T01:13:10Z"
    mac: ENC[AES256_GCM,data:8r25KfzQ93piJU4KePAQFjubrvO0Aiu4R2lQO4cwRYJKtO2/QoneFsMx2grYY27hc4eS8+SKI3N3OL1NTj35491I+HgXDrbF1YYDJqToDSGmyvlg1kUP8hospC2ybqVX1rnTNPt0ZAcSNvRod3AA6NQVRoFlhFYfg6h6OjTPR+k=,iv:V1n8UdKoR4O4k8dWtALml7yGC87J0Ys9/pRdEwruIaU=,tag:LIfitYkeCERXefDIAkZZ+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
