version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true