---
# Project information
site_name: coolguy1771 | Home Cluster
site_description: My home Kubernetes (k3s) cluster managed by GitOps (Flux2)
site_author: Tyler Witlin
site_url: https://coolguy1771.github.io/k3s/

# Repository
repo_name: coolguy1771/k3s
repo_url: https://github.com/coolguy1771/k3s
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  features:
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: ./docs

# Customization
extra_css:
  - _static/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coolguy1771
    - icon: fontawesome/brands/discord
      link: https://discord.gg/k8s-at-home
    - icon: fontawesome/brands/twitter

# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - macros:
      include_dir: docs/_snippets

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

# Navigation structure
nav:
  - Introduction: index.md
  - Installation:
      - Guidelines: installation/guidelines.md
      - Preparing Nodes: installation/preparing-nodes.md
      - Installing Kubernetes: installation/installing-kubernetes.md
      - Bootstrap Applications: installation/bootstrap-applications.md
  - Networking:
      - General: networking/general.md
      - DNS: networking/dns.md
  - Storage:
      - Rook PVC Backup: storage/rook-pvc-backup.md
      - Rook PVC Restore: storage/rook-pvc-restore.md
