# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:v4EKqDPnj4sj6eUXZoixWaItqwEm083kjjN1juOA6qmK299zfjmRzSJfc4/WtV4AjFP9qj6QLUkXSHfLXWLz2OEX4ktGw58miUah3M9N03BLe/Rdpgcu7/V+2X6h4fGhiWv57uuIK0LUofOniUUTK2WecmmR8JA9nNoVy2Noc5vfoTjKC1tZHIQVoWNtYHGwbpqHIo70Fs3SYRG2zVDiSwxKo2BNWrHClBSL2dv4P5jMT3xGDO7zc8qMGuMrksL81qUaiwBj79e6QXmO1OYHHpy5ThpVwvJlKsbTN8bEOIhsaZPOO70wyKqhCZ/I,iv:jn0n6iHYy1fLjPMfjWt8UxF5cneePc6wYeqF/HgnW8o=,tag:+xTgJmCt1On7jb5EPXh50Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVzVLVEZaSTJjRlFCVy84
            SlB0YjFzemJuZlV3U3cwdEs5NnZuc25sZmtNCkVoc0VLY2RLZkM4bGxQUVNVcTdB
            WnV0TWFDYk5oWlhhTHdMMVZUUWpUL1kKLS0tIHhaS3U4UlJ3VXNYUi9yOTRZaC9z
            UGFxYWRhYmRobUxaZTdNWG1hR1VlTTgKaJF7VWLa4Sd/LP2MPmBvmpVqHoUHh9cu
            z43uypUAs4+I67wYfMiEI4U50ewzsfU+q1OIagAHrKbneCKuNO5n9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:12:50Z"
    mac: ENC[AES256_GCM,data:d3lCqs8EYi3PpawPYPXKEeSY3AMQUOOeEJLnO2otY07T5rQO83SyzoeJQrjnHrzEv+ZSNmCQXMIya16sLNWM+4qT+AGpLy41+9085pvzpv79Aag1OIzo7NShy6JlCnnQqK6cCcUYVIfnP7zoMhbExytbfUnYpDFglbIQl5M1h48=,iv:714EQPnVbN5RAHg+V+NijHAvI8hRsKW2sWQN/zFKssg=,tag:CX9Kgrl4qlkYrT/0MlKoFQ==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAo6JvX7amPLCV1z2Aj/xj4abLmVjGy/4cqb0azvzgAd6T
            cpFX9G+J7/bjnocPro7UTrMxMD8KTj3T9IU1x5TLV/Ncr2MK9KPEMRtmC3T5k9NL
            ja+HM35xKu5vjUF6BukbJnHEcVQthjTF8NGPBFNlQpuQNbFeC3DZQAe+PSfFBISD
            GwSKlNvepT803P9TjWIpRV54Ik5kLldV+ILETvlFrM/o9WAFehCKsB83ADgGBTYo
            YHLk0NM8fAzissX69fumNLfW0QEOS/BBvfK1fgai1WL8GCv2erFIZsWWMbDP7JaB
            Za+5EkCXMz9d0zg2e5E9V8/NLV/tv7Ymp2yL7TdsnHEvSF2aY/g+gnox/aTDDqut
            xzFJg4vziaQVnk4sMO31LGOYAO5FS3EQSHp+6mH4aB1io49mkR5vAg8iXDcmFExX
            Fy5ZneM2Wm0ZAyt2c3+MMHh0+PX41ChLQUhSqUM3H3+Ak5pPyhSQ43n2/iQO+08H
            WIgd0poaSRSMC7dbY/t2NhPKFwailKyN9Fvvhmx91Ql/4qZLFcyr3+3neKWECbzQ
            AIN8TJ186tLqgMqvZ1vBJFFnzWe1WKZB9J/NaHqYTg+f0bzet/jJLK3b1RqMhpJE
            05L2b3TdaRQyVYh/qeuUeQtAzpyjPt8cBfAEQL+LPgeGDYw2SLKLkLJX7pAp4ebU
            aAEJAhBGvSgNCzjoaVun+SZxK3zNRw1sxhk4Egz0+fA+3s+r9kU00ND2/G0IYCxV
            l3IjlTbXV0hPz20Jan36zF1pi2z99tiONC9+ScgzkkVE6h9udSgBZrBLXZiCBXJs
            Rs7y87Ff+ocy
            =mNZD
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
