# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:7NsP1yQvgzRSYAPWTtwHb/9StKvsQMTExUto0TTw7twtfkF0S1x7/x9HXU19akzqaDBOFyjuLhBbBnYZGM8yB3plxa6OCEPUex/Pupju9un7JWnZKQQuIEpSIXcAH8n6BPR1T68ax76xFdOQVrZNqYJpANOAfK6EoX7ElfOiIm7juH86ditU+lpuu9qKEgsLjnr6XUhBLdGZe4TeMcBGJxqp7MqAlrqq9YsdOWEuTOEJ3z05vgiMzYu7SuZI1k3r70fpm7U3CB5wfZ1nBlGS/19GahjSQRHADq4wX4Nlt8ew7P1MKUZn6yxhYiw2,iv:jn0n6iHYy1fLjPMfjWt8UxF5cneePc6wYeqF/HgnW8o=,tag:gODtDZxfGWVECAbNVeeU5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjajZLYW1ZNVIreGRrOWxt
            SVZPSGdKc3h3T01tSFJJWjdiNkhhWVVnQlVjCmdhcWU1cjFXNGUySlJOd01VSFdh
            UU5MdUJBQWM2a1pWV2tVZjJGM2xzRDQKLS0tIGVabXZRdlU2cFJGTUg4eEpKcE1F
            VjFaOEJ3Tm9uRElGRVZacFVIWW9UWVkKXdnbewKcy4z2Q2wYVZqCYNKwoQNFgqva
            OS9HbcXEzy6wgaM3J66rvxcsZ/vvbpyQi6K+/j7HORaSfIiSFqervA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:40:52Z"
    mac: ENC[AES256_GCM,data:Zo+Lln2lH2G+s3TCL+ee2JFJBlcazl799Uk/x+37weC3Sit9jL09sx/fm38Fh9THlOacYii3J8HLmDlw+ZUvMlJUlu8zCa+WRo6LcN75GtaMO75dZdqr4GCXGyFWtNan2rDV9lyFvJggcXXbRHDzOR5Rz1PtdaD8xcPBi2loE1Q=,iv:y2stI/oScXdDlLv2C0vBh0p21/6+cZt1xvCfUru7+qc=,tag:ynKZ5/M0lqlhSmMuauvTDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
