# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:aDu84Iugn459x5O/xxuRwHLB+q52VvQ/y/9KFmUYeCetjD6q7aoqPbUaT0J44vgKBLi5mxt5Mk7UrSbOrXomwvKTtj8FsReHcG2x8uNpzdSpmx/EZalvRPxFyCfcwaahrQrohjZ88m9UoDcSLsZbFK/IB7lvNpipMqVZfqmgvBgUTL7xlnSIX+42p1m7JbsVj11Kw7JqNlFyN0X4tgw=,iv:BP1/GOiSIr6FuiaYo2qt0IzhbFD6BwFqpR1VCkFhi1w=,tag:pB3cr4Un6YqvOHvJFDZlsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjajZLYW1ZNVIreGRrOWxt
            SVZPSGdKc3h3T01tSFJJWjdiNkhhWVVnQlVjCmdhcWU1cjFXNGUySlJOd01VSFdh
            UU5MdUJBQWM2a1pWV2tVZjJGM2xzRDQKLS0tIGVabXZRdlU2cFJGTUg4eEpKcE1F
            VjFaOEJ3Tm9uRElGRVZacFVIWW9UWVkKXdnbewKcy4z2Q2wYVZqCYNKwoQNFgqva
            OS9HbcXEzy6wgaM3J66rvxcsZ/vvbpyQi6K+/j7HORaSfIiSFqervA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-08T05:04:57Z"
    mac: ENC[AES256_GCM,data:T07wNflHUp1H4hyIgdeEh57AEPTHDLU+3SHXxFG30J8uLgnNYIuprCRt+SPLVeMt3IozQl8iP7uHdfcBwiB5IOaoY0k1wu1YJCqzhK3Tsa2355nY/0Idi8GMeJ/MuyywhPi4ecz6mL1a7KR76+ubIFj2RN0BGvnuHb7YGbJYLNs=,iv:+eFDIGPdKzwVPIbhKN4rThul5ZfOFOw9tPjNq5ROS24=,tag:DwaOxRtUfiQcI3oIZyeraA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
