# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:VvLZsA4tCDndpaEUhVILn5A2cuCJGdJYZ0xrm50WrZNMmXex+y0BugqN4dR+CAxzwzyuBOCdK4/XyUBzjXVH2Jt16D4VktA3++2ade2NYQqu4LggBFDWthXrJaeKgzki3Zx8sz/I3z9RzhMV1lTKVEopRO6/7v32Ju+P+ah3p5g+iJVFtnrBDk5yUbvy29OBPF+ACkP2wf8TrFlPDthGVScLj4yetfsmfSAgTlyA+94HrY4GQyWehlicAPOvOtVZSKjMCwRHMhNEcSOJNZxtB2GjbZXiZhQsBaiaY/Ze+jR/Y9CySHaUlQIQTbRX,iv:jn0n6iHYy1fLjPMfjWt8UxF5cneePc6wYeqF/HgnW8o=,tag:S2tl8z7INmKbTienXWN7tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RndMU3ZJTVcxVERNQ2xI
            NFMxRnl2bjh5R2N4TzluTk90MmVOdzBkdUJvCjk2T0wrTnZKVW9tejkvbXRKVXMw
            WkdiaGhWdXBZSDJyb2FqYjFucFR4VGcKLS0tIEQxM0hUUldDbFNIZ21FUk8yaFNi
            UXAvbmRRRWZoNG9rSS9Xa0NFbW9lMW8KSouv0Ppth0k/gJB1Mbo/JvqpG23D+4/t
            6ZvxSaeaSNXQOR4q8OmgNMU321U48fULNRDp0AjQxX7iJfqrfihe0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-08T15:23:36Z"
    mac: ENC[AES256_GCM,data:yc5QFat6HtfaPc42O+HaJiKTup4ShoTLkGSjAsWzYxjzw8wiourPdT9N95oHVNrTatM9zhtVKeim6aGXe75V+ki2jSdkGT+RpD2t7PFObfuFXbTS3eFWxjA34sgmm4EjhRbYbnI3HA9HUE01oR0NWIhMwvbAq36qy5WTJdqvuJI=,iv:IxxunZ82D8EaR39rWoBz6V0wSNBE36zPbBr4HMSc9Uo=,tag:tUsCjXf7zn5uzmLCnK6s7A==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ//U1ycfWZg6hTlz7MD9CDUesUZVTXprVbnCrzRo9ZuN4J5
            wXA5vN+CPbJjj2K5STaeJPC1Si6QS/T2sO0g+cCindF1/OFgoXIFXn8HkFLeg/3E
            xKF0MgIBaPMASWGwRhsUegvvQBPMDMUnMcB3wXZ+9fXP3H5ARSSKGrfgEYpm2VsI
            sKJbKuFbn4OU13oQpkp4pdVU7pU4hlmvDRDRwgugYwFlWgKVZsQBvHc139N105z1
            iD5drXU42YbTYEwk8zjSLY/s61xtXE0C06AhHaAyvWHv24+d7azgDjRQMoP9lNev
            lRvYqWhFGppQ5YsTx5bErKkXPGOynBa0ZajN2dfDRMW/CghpEMrUt/HrbMIo7nX8
            gNNuzmMlmTAaOl0BqNoRP93TNExkJpUsV2geLPTObgXjiiQ2xdGRjAYGXhk0lAOk
            tsio1yPpYo8j/ebceksTj6P3L5S+GifIsnFW8lKEUQlTkpPFUL5WAvUIPwjGWTPT
            S/EUQ3loN2Jz6IPMBktfvwidXVhx6iPqIN2WNfEkBQ1vz+47203RDd2An0tHCJSV
            XYcbDhAAkwr+H102iwapX95bBVkqcq35lsa2pfyo/LxDfgKExd3bD7F8cgbvnfb0
            n4B8n365nFnbm7eCBzX0zLS1JMBPqs/AD8h1pZXD5AK2C0FoLmSnqJ/utU/Mk6jU
            ZgEJAhBvo25yVr1oWBnxxQ3uVfw8d1ihtLG+laoyjPEq7ep9ARrTuxdPLfa/TlVH
            okK0hjh+reJyXAyCUiTCkwBI66xcDpyp2/DmpZquJ4hOA2uRvLodM2djoj7K7gLa
            2/qDslWtYg==
            =MqFl
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-29T16:02:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAApiTsLkv63fI54AJDS9tqMJLS+KbolGYmw7yz1Q4cVM2j
            KRb2bL7rRBVpMXZuRbWU0ExtJqTeQTZt7c6IOUPKNsj6hTnSGnANuQ5CZZwqJiD6
            VqstGJJ9QjK0h+69c/SxwDQgy7iKmup0pm834dS6UJWi/Qhq+tCn9ptAPjpQYSyt
            DFYxgXpE9dixpEHrPaqHnw5aCRmtxDUHT078/NbCfkoUVIa10FfwX8243PL0Ss89
            4uNgefr8UFlKZNpeqY+g03PuYdQu0bhJoxTPvl30v6VMLx++eLgpcW1h0gZJk1Bg
            iyqqdrlPl3f7JdGOQUc6I8F38zzXl8p4KUNQcjq/UV1crJzJnFSLa0HpHwwJXXOm
            0LEASF0YohsYSoZTjg5wvR5b69z1OeA0FaCQH7oHgzXTNiX2WaC1jAr7+agl4V8b
            4yHbAAkz3Z2QZu18WsdTEj5fi+DFoOLntLZ6SL3wpC6DmKalQ5jM/6HS8PRLBLEI
            ZfrAbviTR0G9op3B2WggkadwxqOe49wCIUL8dhlUCk37id2uptQpytFYDai71cN6
            lS5vRhY3yfYXW9PvKcRJaE5dLev+aiiU/jX3T408i/zhABLh5ChpL0pjtPvAxfBr
            qtt1vCGCZwAd5v74pl7RLz7VQJwLZhJc7+WqykoNh50JQo+CEqRXluu12zvYtKHU
            ZgEJAhAB5cMGxuWS2D+j30kiNRW+BN8qGuIvlldyArdNk/zwaEoXER4AgGLORNrY
            m4Vofz63y0U/PD+Zyqi4hMTY82Gjv1/SVtsY7+KujYOexwc0gGznBB1ZTPiegPB0
            ErJBqdWtOQ==
            =to7o
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
