# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:w3LimFPEq8o3DGlDYzwmD9oqIfQGNx7T0r7ZdLTZod+aN+FnMvqTaySO2eCDt3nduf7BgqRo7i8XV0Xed4G5q1/BTVAahtPfW8t0eXJg6iVxkobY1BojiryTmsZqu/Xoa0x3is2qKWdj7iTz7+1QHtd/jMR0QG7DxjoVuOMiTpmxoqRoqN9SoLOLM4unv/FJxwJyJrHbjgRxx/tOQ8hWUOFzfeJbXR+wHu7dm8sxA+XJV0/z55zDRdV1Px9NkpA5tP2jOzZ/9tZs0OE=,iv:lrEoApaS6gJ+T2FcsO0oq3mnLgYGAnNpTcYRmbTHGBs=,tag:UfkcpmwrxAyodukjAmyvLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-24T21:10:23Z"
    mac: ENC[AES256_GCM,data:7Ov4xBmYW3ZS+fhQSuMVJGRBAgNw3OKxJ9EljqSGflZf5IgunzClya9EJhmlZLnSeUg3cnkf7vGcrY7LgXjQ7tl79uaYPR3NwZTU5HSHsc6R5e7pmnp7N5a2Ngz71bsSRv0QokL5sZKtxcKtbV/tZoAbDWGSE+tSXZNLhBbUcWQ=,iv:UQorcToIGqXtYQlgDze32xTXoWYY+scC4Pn6HtxVSpE=,tag:hEv70TtIeFYlgLXalAsDfg==,type:str]
    pgp:
        - created_at: "2021-08-23T23:03:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6YvMuRc2PZqAQ//ZuIGBgyiJThIBvNpsbVpfC0r8KZBnXy33nB5pV+AncL8
            j6KPlaHFSMBcXfxc0/yDwcJcKENS7ZnVVLqNUQwBnkajbCPyBYou6K5Md8zHqpMU
            BveEqI4Rx8FgaxGWrMW2/Mft0Jr2g710AYXpIUuqv4LbAid2nf8EGZqeoU2E0WlC
            Ge5r6NTupI7K0lI4AIBOGNsCzZTIieK+Ds3aGmmtUIK8RvD/lv0R9Og7k24Gtf/t
            qTQi63jdXtBdbbXsXfDQ2Lop8LUZXhO79VO1tGWwvrDGd98smbu4jEBmj00X0i3H
            RDEL6lM2E3r5FgHy6p+/b1xXhQtPQdSbpJUplurfNyD4XtXBHhhDBrN/gbBPL4Oy
            wkhhlf/r2YHDafnTsTh2fOhhlehwy+mTFP691Fn+/gx5SJC2MmX893qNdSkXsjK6
            SIN7vBIpQzV8B9jXydNPPtTo4SUjYTkOr7Y1ipI1EEFS6Lhrc3+a2+ZwJsSzY2LE
            txTsG/TJ3OPG8uEOkYyzA5TqkamrJHnTr/D8GSzcuzZuBmDE/XusLq52Gd2rm7YC
            C1sSS0VrLxSc4kkOYTeGTb0m+sNjDJ/7ahs9Bd9kVhKz/+PEuDhiQAa59RK0BUP/
            vfw5q/7SSG8SLBctrN703ZPbQFlhW1CAXhsfbl6pdro3VEd/XNyccA/2xTsmABzU
            aAEJAhXD8E5W+w+mA4XL3Ew9Tck0R9lC41bOfLVTeuVYlOwj+q24PrZfQtFneijv
            L0cHD+Y2NuvR0/tRWEDifXHyuFOeFxuwQFNIfR1n+Hek5czY6HbDrRL3LjksYIvs
            FjNNPDYB7czT
            =oV1N
            -----END PGP MESSAGE-----
          fp: 86B2157D15BC53A36FBA055FCC5C3C333A4093D1
        - created_at: "2021-08-23T23:03:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9FqixZt57HSAQ//ZI+oc/fBOJJ64wcWrkWHWqYfi9kVnai2UqViqlKHYHYE
            N/4Sr2g3pwxtpVrBvlnTMOsEXMk8OsX4/hWtO9itQBb3ZoGZDcH/w4lGF8K78V81
            38jnmiz4BCQ7WeM5/x7jWIVJEgpB1wHvQwwtPySPBCz/hS//XeL/jPnPky6MmPnS
            jqvn/+n7zvO57Jn953rDAlmN+8l77gN9KLdD8koUZzI/Z3h339AtglDD/rSn+oFg
            X1LWr/x2yzEExrldlZlWvNjfUNkUEH+HzB3SBjJvvNGFYeJ6KlsNXDBilYDlL6o7
            Q8VW86oQl8kaHvzWAorNrXc9q4bhUoRp6HuOJwXHfKNeRnkVpe/m2a2dmfCvfY8/
            4FHv5fUsLXS6JQ2FGuXVtT5kM9K0T1VlMszukl6rk1kgq/CYOeE6UxKJS00KNUGO
            sDaqS9PoSoASunN6KAV9C3fr5R6baFNEOdWVGFnGClgqTtTMQSyXUzRmtA4PCpdv
            3CbeHy1sMg6niH6j9VLEKVQKSgGiSPjsxCm1qae0ugbBY+zKDuQ0Ob1nFpvqGT3m
            hXmW5f6IlAwPMa2ex7QrG4IudUe+ZrrGIJGRMAFg7XX580VBuAUkwCl+/2E2eG5w
            kLAJuWogkTuHEYun/7fcn0YYxPvwwQnM5ZCA+albxSuliQHgMGbhKoYPgRGkxL/U
            aAEJAhU6RsoW14Ys5J6JjF2yUaO2qj2hWQVe/QzpHWoefWjYYL43v31sjFfa31bx
            t52NBL+A0xalaTP094JBij+L4mjE5DeucYPncxULmhHpE8jlhaP1lbrslcaggewl
            o5iutg/lO+KV
            =+NhI
            -----END PGP MESSAGE-----
          fp: E04EE454BEACA869B2FB211472C2E881FE50E35B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
