# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:jQGcMEZTw99hRWbXHmdl7GCvuaiRjPtLmymE6UeC1BetaVVr8gFxB//fKL9Hytayfv25GRNKw+ptcGEkgwToSbNssjMIEwqAovEPgeSXIB5KMC+b4cAbn0N2boTYBxZaJ4egQZ+bM2B9hBzirjjSfVl85jufinNd/6ykDZNxQT3PhjKVVjU=,iv:u/92nV5W2W+a+OrSvvCJkTFNcgHJKmY4xriQoyZrWoA=,tag:RvZaH/QPcFy/WHFOMOFMIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjajZLYW1ZNVIreGRrOWxt
            SVZPSGdKc3h3T01tSFJJWjdiNkhhWVVnQlVjCmdhcWU1cjFXNGUySlJOd01VSFdh
            UU5MdUJBQWM2a1pWV2tVZjJGM2xzRDQKLS0tIGVabXZRdlU2cFJGTUg4eEpKcE1F
            VjFaOEJ3Tm9uRElGRVZacFVIWW9UWVkKXdnbewKcy4z2Q2wYVZqCYNKwoQNFgqva
            OS9HbcXEzy6wgaM3J66rvxcsZ/vvbpyQi6K+/j7HORaSfIiSFqervA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-08T05:20:32Z"
    mac: ENC[AES256_GCM,data:5obC2A5BKSHiMDBPZwbEm2dwQQfsmkRC9XDgb2Afz86xDoQLVGGyudv/Lmmi35kJ9Bel/jBiUbdl+78ZeG8KIWYxWhIVEAMe9XTIMnmAjzKqfvsRhE9O5HkcHqNc6tmVLupb3X4MnZ5fHwVvWjKFhiwYXJEIarKO2cMm70ed2Ms=,iv:oYnDMx+lquv4T/7LMvhSBrjNmeIzDykGv6667eokEbM=,tag:AE3hwHOfgtyixf8dGMvfOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
