---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: blackbox-exporter
    image:
      repository: quay.io/prometheus/blackbox-exporter
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: &host "blackbox.${SECRET_PUBLIC_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: blackbox-tls
    allowIcmp: true
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 30s
        scrapeTimeout: 30s
      targets:
        - module: icmp
          name: opnsense
          url: opnsense
        - module: icmp
          name: osiris
          url: osiris
        - module: icmp
          name: dell-idrac-0
          url: dell-idrac-0
    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: HostDown
          expr: probe_success == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            message: The host {{"{{ $labels.target }}"}} is currently unreachable
        - alert: SlowResponseTime
          annotations:
            message: The response time for {{"{{ $labels.target }}"}} has been greater than 30 seconds for 5 minutes.
          expr: probe_duration_seconds > 30
          for: 5m
          labels:
            severity: warning
