---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://operator.min.io/
      chart: minio-operator
      version: 4.1.8
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    console:
      image:
        repository: minio/console
        tag: v0.9.3
        pullPolicy: IfNotPresent
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - hosts:
              - minio.${SECRET_DOMAIN}
            secretName: minio-tls
        rules:
          - host:
              - minio.${SECRET_DOMAIN}
            http:
              paths:
                - path: /
    tenants:
      # Tenant name
      - name: minio
        ## Registry location and Tag to download MinIO Server image
        image:
          repository: minio/minio
          tag: RELEASE.2021-08-20T18-32-01Z
          pullPolicy: IfNotPresent
        ## Customize namespace for tenant deployment
        namespace: minio
        pools:
          ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
          ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
          ## Note that the operator does not support upgrading from standalone to distributed mode.
          - servers: 4
            ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
            volumesPerServer: 4
            ## size specifies the capacity per volume
            size: 100Gi
            ## storageClass specifies the storage class name to be used for this pool
            storageClassName: "nfs-client"
        ## Mount path where PV will be mounted inside container(s).
        mountPath: /export
        ## Sub path inside Mount path where MinIO stores data.
        subPath: /data
        # pool secrets
        secrets:
          # create a kubernetes secret object with the accessKey and secretKey as defined here.
          enabled: true
          name: minio-secret
          accessKey: ${SECRET_S3_ACCESS_KEY}
          secretKey: ${SECRET_S3_SECRET_KEY}
        # pool metrics to be read by Prometheus
        metrics:
          enabled: true
          port: 9000
        certificate:
          ## Enable automatic Kubernetes based certificate generation and signing as explained in
          ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
          requestAutoCert: true
        ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
        ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
        s3:
          ## This feature is turned off by default
          bucketDNS: true
