---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pretend-youre-xyzzy
  namespace: game-servers
spec:
  releaseName: pretend-youre-xyzzy
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pretend-youre-xyzzy
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: emcniece/dockeryourxyzzy
      pullPolicy: IfNotPresent
      tag: "4"
    strategy:
      type: Recreate
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
        #  hajimari.io/icon: https://twitter.com/hastebin/photo
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "cards.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "cards.${SECRET_DOMAIN}"
          secretName: cards-tls
