# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:HCyXOPt3HbwiqCw0wl0OjI7VjmQpiviNL051pL/VOv7bwD0edSCX7DTfEZI0RvsFxx9sNBsZinGtbCZnrparFQFrq6syOGyA5aC+ezJAXvmt+G2h9i96OoDdfYDF6BgY+RnzyMFzW3kQH8TQ+zxFBI+2lk0TH9pP,iv:keuLHpDmiumZtfiWLGIa1Fx/SjO8GiUHwseGP6ltjnM=,tag:NLrDxuo0q3ZqvkKP/uZe/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL1ViQXRNbHQ0VDBRNGkx
            N2JqZlFyTzBnSnVrdldIMmJOQlp0QVdibEc4ClpZVTlyTHJpT2RrZS9lZFN1VS9U
            ZkRzVVI0dEpKbU9GZDN3MVordkpsU2sKLS0tIFBMWmVvdjVseTg4YnZCME4vNFhM
            bGdUbDRYREI4QkwzWko4UitvY0JMQm8K0DkuALfa1ExZ22huUfYHKSE3lQZ5U79t
            hUdpFjtsdSORDFCxBX5mz3MEJRCQN2fuwTWhP74CxXphY9+K5t5D4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:48:42Z"
    mac: ENC[AES256_GCM,data:qGJzxF8ZAlFzkpuUoc+J/A8UTkiiUtcHziebV3CSKSx+r/VhRtdwC7XQ/B883jixvE0Ib45C1JfNfPz5HrYi2tpoIKVPON/lksakvsiLXZJuQj9zMNdaudH36WzdOLzR1cn1ZvrgnDZO5v1nAtKCMZ8uNZqOZU2eDWOVbmCB/1M=,iv:7iLFWht5mSdiUSpGaLdp+GCtytDemIScgnO+cS2EdKo=,tag:S9LlaWr5Cr3Y7UPJzhfxbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
