---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-v1
  namespace: auth
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-v1
  namespace: auth
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-block
