---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2021.12.4
      pullPolicy: IfNotPresent
    ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-lock-outline"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_STUDIO}"
          external-dns/is-public: "true"
        hosts:
          - host: "auth.${SECRET_DOMAIN_STUDIO}"
            paths:
              - path: "/"
                pathType: Prefix
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN_STUDIO}"
            secretName: authentik-tls 
    authentik:
      secret_key: "${SECRET_AUTHENTIK_KEY}"
      geoip: /geoip/GeoLite2-City.mmdb
      email:
        host: "in-v3.mailjet.com"
        port: 587
        username: "${SECRET_EMAIL_USERNAME}"
        password: "${SECRET_EMAIL_PASSWORD}"
        use_tls: true
        from: "No-Reply <no-reply@${SECRET_DOMAIN_STUDIO}>"
      error_reporting:
        enabled: true
        environment: "k8s"
        sendpii: true
      postgresql:
        password: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
        s3_backup:
          bucket: "authentik"
          access_key: ${SECRET_S3_KEY}
          secret_key: ${SECRET_S3_ACCESS_KEY}
          host: "https://s3.${SECRET_DOMAIN}"
    geoip:
      enabled: true
      accountId: "418977"
      licenseKey: "${SECRET_GEOIP_KEY}"
    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
      existingClaim: authentik-postgres-v1
    redis:
      enabled: true
      existingClaim: authentik-redis-v1
    prometheus:
      serviceMonitor:
        create: true
        interval: 30s
        scrapeTimeout: 3s
      rules:
        create: true
