apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nfs-client-provisioner
- kured
- metrics-server
- node-feature-discovery
- node-problem-detector
- reloader
- intel-gpu-plugin
