---
#
# SECRET* vars are encrypted with sops
#

os_timezone: "America/New_York"
os_ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPnKXgEGczcu8lGs+DEvRWgI4cSYHkAyTAU6/SMAHjL4 twitlin@mbp16inch2021.3520.dhcp.asu.edu"
os_packages_install:
  - apt-transport-https
  - ca-certificates
  - curl
  - htop
  - nano
  - ntpdate
  - psmisc
  - software-properties-common
  - unzip
  - open-vm-tools
os_packages_remove:
  - apparmor
  - apport
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
