## yamllint disable
kind: Secret
ansible_user: ENC[AES256_GCM,data:e/Frr7ZA,iv:/rj3P06g0fQzAS7fQufU/WZ+DbRGIHjHV1hv0hkaL2A=,tag:sAH0hHAkmDCfys3mAJ4X3g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:H8pZ1eUqK8FJrQ==,iv:zqpWSjoRPFX3HX1TH5sEs3YDvzTEB1RKNT04VQLKN1s=,tag:Sw02EF5bxGEP05vrzZjRSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-15T19:12:01Z"
    mac: ENC[AES256_GCM,data:z93TzgtacefLG/lxya3ogo2qsGVHnIF9hjHXB/b3iY9ECQMwAoeBpgLc3MreNVOcFZDk7fG+1mFQHp9w8aPtHQu+n3peGmmmvZpIgOznuN4DHUtz69O/INkVGUPqmoK4dPY0OD7WjSkwtFERCO7aHMV6LhGqdkn/ejXyuPopUi0=,iv:CvEO83w6VoCH+A5+Op0FIBK5IIvZW+9m+crVP7TaGtI=,tag:EBoUMA2oNaEdwDPwE3oxrQ==,type:str]
    pgp:
        - created_at: "2021-11-15T19:12:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAvyipBzvwpxgcflkWzo0RxOD/Eg3OpCU5gPIxKuszUu+V
            4fwD/SijytUFnQv6idrYSn+YuPRCfbiU30kPrMkeyCjLoSjyk/TK3HMZUHAwj5hT
            2JCivJ7kbFCk4Kw64oo9rWE8LA+FLFXYIdHi9xMxZhLAD/i1JswPBjlVaxHqiffa
            HdKCljNczjNe1vkdC9bE9hgJKorPY0TDhyqcJ7XpBjq1DEi54qZYdMXY9llD42ME
            0F6bQZfMcw/YLKn+Xya5xsKf4nOxTVieAHBqQ4Gok+v7QiwjM43gYozp7galkvMQ
            tbxtDymPLlxJ6ZHb6Ofpom+cDH+TEeldSWH8OqmvfcyZLb8pN+q70Aik4QMZ5XkM
            PSGbR4FJT4RGGtcSV+Sw4NGMNUXPyMmAcQCoEo+eWPgLssZ7M4Gbc67tzVWPlj9s
            WyzVQvU17J1CzCp8oStgpWgPd7oVkJkly81fqj86nTAG4e2CAyE+JLMsFvqYX8hp
            f2NujjuCl+fialUtsEVdqtlr/O3+c4XXURKjpbVDlEXiF89gBFEL+4izb+kyWgwZ
            53R0JjyavHHoYH15ni2VXJ0FibMOk7u1IO8EcoGm/cuW4519pAADJxszR8qr/MJb
            7EXsJ93GRPbVeC9DPbq+DL0jc3tBpHrA3yHz0FO01hB+XYyf+/2oyS5qMq/vYa/U
            aAEJAhCa3seCYcRFXA8Ddc0e2CX+m+zR03dBE+6YLidyPcNm98GifvmsuoyUJ9Jv
            TcxJ3ojFyPAThvr46qGeemMTvqPRkSLBpBkUH17Mrz5igEOKXXNGr/Xyw6bbeN/V
            JxBGWr248TWZ
            =98xl
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    unencrypted_regex: ^(kind)$
    version: 3.7.1
