# yamllint disable
kind: Secret
ansible_user: ENC[AES256_GCM,data:18IQMHGo,iv:lYuxXiHdQ2OSVSsda2NgmKV2pHJbM/rmoN1akUJzwzQ=,tag:FmPG1SjsEK/GqXGobgQ6Eg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HAZM/1Lt4roybQ==,iv:56K6eyqh8DOQD7bxle6lvf0okJpXG0jsGxGZEe5cxNE=,tag:cwmRps5E/Q7h2ESoXLY26A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-15T19:11:57Z"
    mac: ENC[AES256_GCM,data:OCs49RrCRIMQ9wFJsWAjWMQsy5l3killOqNdu8wAICkZfOG3hpXYAvTTxXvzUcogTs6gDGac4Dr5b1aZqgSLVUMs0A1Jzvn9NAOFWEFhvDEqh4/fbRAkDCGeEd/5KufQ66H17LjkqsXCLLO61envXaXRJfM/DElvnQpKE20NR+M=,iv:+JqaGhIbvDSG3DCzOY2Ovx8/WC4cfi6vromQNn4kq5E=,tag:XNLF3AXSvZGcKJSmMw7cUg==,type:str]
    pgp:
        - created_at: "2021-11-15T19:11:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/9HeYK4fHzmnFqHXtdq4TFNaBMCrDqRbu9C8jzLfFHWtiX
            aM4a7/b0hibBIHXYWt2OcEY6yGLRT3CxLsvHoH377/ex67K4iBIYU1yetnV4PRrf
            ao6MweJCceCKKMTXiSMvpHnvUQ+L2UHch1f4VQO9NNRLkDyUi/lsdV2jRMZxTd1w
            UWuSmwrzBcucnhGuNmsSRjEyc7iRusRa+px+7sFrZhgXZw5G9Z8ywiT4t/k8bA9z
            lW3zWpzZYEjgnRWXWIpHvHl0uo2hxLzMG9A9FTb935yuG4yD/tJN8QL2b+knKgqm
            oQKt893vKPspM4rCp5/19MJy3tZ4GePCzYuoduj/I42PM4OiVwwtJ8WmCZiho7bo
            mjZ4NNYXPRelTC05C28Sji8mILRRqjs92di5IH5BpITeRCnQxMDrF96hTXk+cXiD
            wiCOG823TeKpx3IENSyq0BRUevyK5IN0TlARAX7HE08rbirND4mRBOmPFeE25Bkw
            wWZUykDQNCemsdns9S9beIOCLji+r9GIQxnYfxfaJ3QOwjmbBb8oTsrElH+HKb2F
            DUeQO9kzRJCPKQA8WQR3oJNeVLI3WI8kAO8ZUqaX7eoHHftNt5waDs9S3Q0Ty2Pc
            FaexBa/qBYXlFsmp3QHXbGgh2MJrhM3gTTyVSrODTRjJMx/wd/5OZe0u/PBsk3DU
            aAEJAhBIxh5yyicEPsNX2rEtVyIOqz7h3yle10BVBY0Ce1wGD5oWlETho+fipi8r
            8QIAOsXjfDezharzevb+j0Z5GlxiQ9S5IARkoWothVlCS02dklP7SLhPwZe1SOku
            6V37C2T2LJRq
            =s55o
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    unencrypted_regex: ^(kind)$
    version: 3.7.1
