# yamllint disable
kind: Secret
ansible_user: ENC[AES256_GCM,data:VKEA6nlo,iv:gyDqEn8xDuRUx5wU1maJ8grcUSiS3qIzsP7m4vA1ar8=,tag:dLonYbkP+x+ysltWHtZvDw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2oJjjuhWpFRY3A==,iv:0LkE4bpHUCKUPAs9VOPKhJPbhxwn/1non97VyK5DHyY=,tag:q9t20bm6MTA+HefA6mR0Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-15T19:11:48Z"
    mac: ENC[AES256_GCM,data:Mfr8nbPk1gA5OeqOQcrFc+3u4uFqA588EC2/Kra6KDrrEWL8MDsSWqfRvHpcZ6Gg8UOuFXLSlDAEGblQB7lcsUk4FYAQ9ImfivwU5nax5xeOxqeIMpmrzOEGwZ+7S8TDiryRdi8CewdU5S+0CL79u/xFCo4QnmIhDnmR/O2mzKA=,iv:QHlVu0iBWD7QEsXT20AiPxCcCnSQUmTDjb7DxgAP6GU=,tag:V4nvJmbBDRz/Yxo0pg9/8Q==,type:str]
    pgp:
        - created_at: "2021-11-15T19:11:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/9FyHb0p9SVm+QVxeRc+Gfx4gT7Wze3ePWGW5jdBQNz+w0
            yk4+wkaEoLtGvs3iUHZ7GYMbP5Bo6doL6ZgHyFuQErBBHNihpAwHUJLp1qbhoMS6
            cLc2mRZ94Kl3nlWK3lXqTMe7PBioZRORdQiFx9eRyRGGubvx9tWY8qHVB5TdG6e+
            oarKbof+M43KopKEKsoWiZDg7gQ/QF7dLXaZGDc0JbYH/Nk+R8Y5xti7NXjar7qe
            yc08JEfx2M5Ye7VZDoi3MlcnEJo6VGWeVkXvqI99moMroKA7B27KVdJgbFOx+qUU
            3YsokIMgNO+Vm3doStysfFWYZiSl4w0nycleda6upRDnz1rFSrYBDJBPnRwn3DHo
            0fbLNbjAlcpvj0XI7309OomCPKbBJvenyuHsc46OvytwVxdGPAe4DgJwJwVDD7qH
            nQADYlk9A4vQ7dDYiFjkQ2lxiqoxH6qIsMXBHftrvHPXM30kzPHnzjwWM6XECwpy
            iHFmQYRvG0O+jqLlQgR61dqiFMnDetzn6HSTxF2HXjm1+F9GrryO9aWvTh3SYprj
            bqMk+2MH0262ljT+w5+zX8i3+IM1DZhbfZ4RLMiiZ9vWfNkWiGLRZmBKWOezG7g0
            WDoyo0DbmchXZexkhQfNZK7tR4+7Ceksmc6Qym10vmkaGGK/GkS6/7b/m6EMabjU
            aAEJAhDNawhpzkrn3Ra5HmO/6LeiH5ShZgfP1U2Z8jRWJmqheaQoeZZ3DvPJvXQq
            v8iR6eouPivOHoXc9bDgardL8mfNUoYQyRvitHXZS/noI3tysnYmXwxl0S9xWsXo
            qNH/eBNl/crL
            =uMJu
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    unencrypted_regex: ^(kind)$
    version: 3.7.1
