# yamllint disable
kind: Secret
ansible_user: ENC[AES256_GCM,data:vqhWAq3T,iv:DdzeCoazgUi6OZO6ext8hUJTYrJM2iGl3ti23s30CIk=,tag:N+yJ4nwj0w65I4Fkzotv8g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NSXQ43OGIkGfZA==,iv:K+dTNw+kad/LGqqAvpss9iIoHImNuC6XKxDNGBJNPZA=,tag:MbZww8o5BRjuEC/RLdNifQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-15T19:11:53Z"
    mac: ENC[AES256_GCM,data:6qpWZjgb0jQCo/Y9ximg2300zNbJ2ygzuXuk/g2LycBdy+03EOFU1BdlYksl0TlIEZnICgDGV4ZTVNRgq8nfQR9yb8Fkz7DUNJ02wTFVtbiQOKcl/dGrbc7WuEBVIX/F252gIEY2CCvlfvObWqk+oRZf3Z0GCBw2/gygo6wIJ34=,iv:idJSp1MgGuUEnZxHihOJMiCvAoeSDhYiQI0dmRDIrag=,tag:a1TFDtqsu1mGrfnFyhJJMg==,type:str]
    pgp:
        - created_at: "2021-11-15T19:11:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAvHQYuKHBq6h9w4vWR1WPTNmMFqgSZATK1u60MzJ+kAE5
            rloUTqkU2iAIolSWu/E/9rtngqlt6qxtO0XCm+qcvWtrvVGoWgfYPEgX5dyD88Ud
            xkvpZWq42kA141euFeKTd/J1bJfTcGbrILqB10qHlrvqCRD6897BGg6fk6npPsbq
            p3bUa514LzxHRWpYNe3S38bLJEwrMtVquxx0dunLBh8svDmx/Bmvn97uFZWtdfl6
            pcqV7OTjwtH4gYDH1FKhXJbjq4vSQB0ynhOiDGm/t9wStvLA9jov9vuwsJ3eWulE
            tKb0rrTlYxICznvC7SVeAQFjVSMycZxIShWaVAEpivuqcB3KuYA5MazlCaRH7iOr
            mVW7FRdteHV1epcL8APiczypF6NcM30Frf1fduHWgUJAQjD1lzZAlkLIdQO2jWQ/
            eyR40gyY4xm6694PlU8oQfpvHtaA3ZS53pYDrm//jTBlw886dkMgJEPUc8w2TytO
            mfMeNm+F2alP6iVTvTUS5OpdJwD/J4+4BaJq+iYCJltzFEW2iCNfQpvsglbIb8mi
            kvaPiMqQ3POp11gDHC6DCTz7px07iUcFYjrLcZeCYU5HUeRrdQYXlKNfzZATumpw
            aug4C5IiQVhpIrMy69yxJf43XYElZUFqKRo/T38nQAk1L0AofQNKE7cAER1nYM3U
            aAEJAhBvGBowXfo4E357Xpb3Yd/CaJOV365U2CCqkO8mzx3a9td1/nwlILZOUeEv
            QZjPlXgF728rWKn8o74sxhd57Yw2J+K267GRRMX4o0y80LvD+WSZon1OPaICz/1s
            YIXYOK0C1nbq
            =NYX/
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    unencrypted_regex: ^(kind)$
    version: 3.7.1
