# yamllint disable
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:DgC7thO+RnLWyA==,iv:BfGI7vjhoikHiELqZbdWhgsiwtriHdiAOgE/3vyyRro=,tag:Yi8LukKWCfxh9mVSZ7Ly0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-15T19:12:10Z"
    mac: ENC[AES256_GCM,data:W0ntOmB/TZgHYtGCZY2sbS1Awv2QDwjfeMO+NSTTz2Hdj1R/s1h1gyKhyhenuAZ7cOnt5HVVwuNjPsd8Ud4b1QR8I9luOYPJ8mifq4/j6MXyfZ3L45zPhH01G7Lj7iRsVqHsBt1YyWZiGnPlldI5hu4mFxXHnTAYHYtdi81TZa0=,iv:WU7SwAiBPda7iMpweZ4mZNV70MAKuH5Zs/MiJIh0fi8=,tag:soCFcGhzJ6aXhVg/uJCzhg==,type:str]
    pgp:
        - created_at: "2021-11-15T19:12:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAiyajSS5Q+sm6FJ/2cSJNpnqlkSwJtlQobXM1yPN0+PPl
            J+u/+tbEWJ+0vugO1smdIGLCBSR8QwbsSJbY4ZzOhNrCN2p//HPG7Lr2Q8Fz5WFz
            5dmdO+4VSlHEvzZEtWN948XGbOjsMio762VJeBVP8GO2zsv3LPse1dY3u6c3JIuX
            w4DcYe46LQFaGrLy9jsUNs783U5UDHs8IM6I7GcX/3956AkSDN1YXMX2dmeWFckz
            ewbHCEYmoZ9DktvBbO/M155xMtZhYjH7TlC9GeyYKCtWZ+n+qsjSJhHyDgPxwTiX
            3bvtOjdw1hcN3QDuSVn2bHY78B2xrbXniCgZyUdCb4m2SdJkLyar1OXEd4nJgB6Q
            XYXMjXwIJdoHsuoiil14jip89y5SbEh6qBUBQmAgZiW2BOoZP+5f9D+hdb1hBR25
            jODtC71EB9wlL2OU6YSJyMdI3t5BjZdP/VzU2rMOSv6WlcHKumT4vG2nUpj/xXRY
            w8mAyjSyTnl9gsezbykwAPZfeZi9xt0/khCiyDgko4SH38R5AhqkCt1+ncnauNoq
            iQEOJnirRLOymyOYYfTOhS3zn8yap3TipBz+Be4zGR67B7+9UWbaithz0RkXwdQj
            R14lN2jyx8ZNJ97YbEWGkcG3Y1wIBZBn5Y0LK+vaOcbmcRcbsLlXphysJMWwYH3U
            aAEJAhDo+s9sSzMyA03EiWihBVVbEJ1veOy/EQOwUXABbLZjGaaVzpQ24eXLfFYN
            90YFHfSzpxxrJqjlxDGkGQSVoH1NpRTIBne6Ln95mdJQpxmkIxzAvUaumdX570vj
            7qFV4hKRsxyR
            =H5Oh
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    unencrypted_regex: ^(kind)$
    version: 3.7.1
