---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-v1
  namespace: git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
