# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Q/L0PHzPQk8k2Y/5RoEBsg3xqMFd0uo8v8wj9uaLtV5/EiRtsxk49g==,iv:drtuldUgpdZPKKZGbzhieVg7nBQNJiV/tH9oF6/JK3k=,tag:ycvLBanqjepid37otpLHZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZkdROGFOdklkR29UMTlB
            bmdWTE9Temd3WEl2em9IbGtIOHVZSi9MQVRJCnpTdGE5RFlHU3Z0Y0t0bDdIWmk4
            MWRsL3Vrakh3ZDAxeTJOeVBoT08xejAKLS0tIFRzdW1pSXl2NHVVbDIxZWhHK1dm
            OXBOR3ViOEJxRXNCSGk0NDN3RTBWTVUKp+SkwYk6B4wIguioWtKteSpOLwJg3vbM
            1MwlfL80LgnHG/FGCQmkJsdQF5yBIyFLLWixfXq/Is/oGVceybQb7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:39:53Z"
    mac: ENC[AES256_GCM,data:hBYQk3DyHkTEOHFUKwAyxHK/L73ZQ3M0QckKondRybriWZwuKHoiB9r/p+rKjH8pban3B7t3G4MSQlsHgDuExEEe60KYCHyRDX5fgjvAKG/+Zs1DP+vowD0xbntWvRuulDB8GQHECElcjpQqlvi0bwHPWjZ2PTMmtGkugYtde6Y=,iv:NyyDAlk0VY67y9qxQRZBajtEuykkL7no0NKOwEuWzZE=,tag:GXrDM3BT0No4iQ6kSApPtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
