# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:cAYnIKQqLpe2bDZq/RxahAdDhlZ1,iv:p2T9J9O+TrF/FzAiKt06R5GheIOpNlQhrKDGrqw+bFI=,tag:svbOLfzp8+gUSUSJl2bmEw==,type:str]
    api-key: ENC[AES256_GCM,data:NiJ6yVO5jNT4dWYTtU5XbP7RkzOE6o+nEfqCjFXXLxBcDta+Tg==,iv:qU+tOcUzZzGC1ZyEscvIPY2F9b5Zdcs10P4ht89Pqnw=,tag:gHB8IXqjMtwPNhNt6bImfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-10T02:36:48Z"
    mac: ENC[AES256_GCM,data:QX2EJLdAnHdLPC2yX+MGG3FC2xof1CYrrQwWInu52dkfrnAsz0S2qc4fZeFGjDrwCbZ+q4X3jEMxarpLpKUAkyE0ahGVrbxNIElXLnDFI6ZbNsIz4F4TFrAYrVOKFnDzSW883+GkkruhY2+bnp7mzgpiUOWQiVH3/QxEt3OvBv8=,iv:n9xJzl+bIinMXVtW5Ayav5pnuPNxXkbRXnNHFE+AtqU=,tag:WUOAZUHRBDNsFEV9ocFU9A==,type:str]
    pgp:
        - created_at: "2021-11-08T15:25:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ//c1lymcOIxdmlKp85ulpDpeFEq4NLFVPh9JnXYIXr7btN
            Yt8H0/MJ6T/OkZ5oUJZrkO9Tw7POkQZHtoEVf2kKWwlbgvW+2WfHZ0xxTK6bMjO4
            js5kilKPVFtK1C9xYNZBmCrLDFKYunBNDz7sFBL9bQNsUU7MHQ2HAVG8BFw3jlTN
            rJrAaL0Bwj/TLQNAf28RlCIXLblSvIASzZqJetTO7ZEAdvaI+HlpCeE0ZMv4/rGe
            rgss24IwY1GO4GTtD92wGjzgN2hpHUW5pPN8HJ2/Q15S+ke++up8NLPBVLcMaaLn
            iPEu5rwX9EkeRk9fxRGg7UZtHI8MQjtevXEejuopg/uGdZlihA9M+XTcoP34Ln+P
            RYoAc64V1oqLEo/FcqskXmfVsN9YDIRnmrdRtq7I4jsbcuj2MFx2hf4DE5t+ml/u
            orMzVI8XNlwpGQaOyWL4qw+imUGqvnlDMTbXHx33vpf5VQyUh+k+X+vDeiJlE+Ag
            saFd6NHwE9BCYQx8TRVFeoygRmhDdmr9FKoDtCP0QyIqlBezoBNDBidBlyn8qu79
            qi+AQX9vP/OcrIhqHdpg5kyjFikiITkShUyzt5453cy5wf2Im8Zq+w2GvHouiVcp
            hucelpNe1FnwBoPCQRQT37LjMaH0YHuy8CR41s+57PKY2mVOg9VGbYLW36UlUzXU
            aAEJAhA75zEFF9SnLNX6+GXtvwCH9OTeux+NBlkeTvzY7dCZswd5KFjRUdVp2uQm
            qZdpq15kTFHbMO0oVcgOsWWGzSnN6uMKAD1sJVb/w64cpf1NAKcFV5h8Tx/dIU/v
            K7rAV6yHpuPg
            =Zs0r
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-08T15:25:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/+OxTWWPfmUaLkxZCzvMYUhDJm6dg6AXYGyOPIAowjPwCJ
            4A2llvlaPhB/S6/zBZJFIHeED79lsPoit9yQWeM49xm4f9FjyWTUOBRGgeM59uPN
            iFQ9dxjtbAztRphicsfuRmTSNoDk6DYFk6ReFZFA9jc6c1IV9EaGChwIEWPqHXs3
            xf72IADkW3rp/N+vHAlD9t3aBjqMBEAO5mu7gSjpvHhjkwtBuaUhmIueYw7GEHe3
            F7S1RJ2fqeHBsPkIih2NJ8yGgDbANVY9KbsIddvg7bD/6AMG5fLWtUricSqpHF4G
            kUVNGSKMAhJDU/RK5Gm7w8P3ig4iZYK1F2lNZEQt0HzIRTGkef/A8CvmWTDQgTjj
            hegLZoLGLMTVj1nbnq564ADz/DIL/Lcf1+x/Zm2mPNthf00jC6OAcjwbgx7WQ0s3
            4c/WI/DBd+/n3QMdl0TVmBomt07ioHt3IcnjAJHNT9LBss1V/hmZa/n/xWtgRq48
            ItYIAv2FzRc2gO4awXrKsJZpMWG3cCT+phUSqqVibQqN89IVIz6YxPnEsExXmQtA
            CC8QvFOPXHWlcRc/6CGHZWd4agFQoOdQZhcwmHuW0O+t6fjculIENIUBHeJ6DKpg
            jNa40srTopwnOuxMCicCg2Zpil3Uj54X8LdlMxzvEhmkLc/8szAnr9ilPhJ3BP3U
            aAEJAhCj3Ykv67SAJQlvbkVaTCznKpSiZT8U8hMW9oO1ggul56SffUqJaeKvywGr
            HQXydnPuf7ONopdFz5wGDCTc6WcIiAErMMEDmPv10Sl18qRKJwswNpaEngzlzUsu
            fZEbiRT0598v
            =f9Xi
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
