---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2.3.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      name: ghcr.io/goauthentik/server
      tag: 2021.8.3
      pullPolicy: IfNotPresent
    authentik:
      secret_key: "${SECRET_AUTHENTIK_KEY}"
      error_reporting:
        enabled: true
        environment: "k8s"
        sendpii: true
      email:
        host: "smtp.sendgrid.net"
        port: 587
        username: "apikey"
        password: "${SECRET_AUTHENTIK_EMAIL_PASSWORD}"
        use_tls: true
        timeout: 30
        from: "Authentik <auth@${SECRET_DOMAIN_STUDIO}>"
      postgresql:
        password: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: "nginx"
        hajimari.io/enable: "true"
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_STUDIO}"
        external-dns/is-public: "true"
      hosts:
        - host: "auth.${SECRET_DOMAIN_STUDIO}"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "auth.${SECRET_DOMAIN_STUDIO}"
          secretName: authentik-tls
    geoip:
  # -- optional GeoIP, deploys a cronjob to download the maxmind database
      enabled: true
  # -- sign up under https://www.maxmind.com/en/geolite2/signup
      accountId: "418977"
      licenseKey: "${SECRET_GEOIP_KEY}"
    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
      persistence:
        enabled: true
        storageClass: longhorn
        accessModes:
          - ReadWriteOnce
      s3_backup:
        bucket: "authentik"
        access_key: ${SECRET_S3_KEY}
        secret_key: ${SECRET_S3_ACCESS_KEY}
        # Optional S3 host
        host: "https://minio.storage.svc.cluster.local"
    redis:
      enabled: true
