---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 4
      defaultClass: false
    defaultSettings:
      defaultReplicaCount: 4
      storageMinimalAvailablePercentage: "10"
      backupTarget: s3://"${NAS_ADDR}":9768
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      tlsSecret: longhorn-cert
      tls: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
        external-dns/is-public: "true"
