---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haste-server-config-v1
  namespace: home
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-block
