# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Rx7wiy/5HS2Ns4RkiodS0g4YQkGOvce49vNIh+FkFQaFOK97jNlnmw==,iv:vT5vmsQLgyi+QpkFL55SR9k0jiznXdavNm2kmYRlPmo=,tag:uZ3tqX/rHkjhB8508afWGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-12T23:00:56Z"
    mac: ENC[AES256_GCM,data:G3VCes+V+zSRMlf86cKA/ZXNr0c9k2fuzbgeO9HFMdr+hdVEuF1DzsLySXJDuNaV6swhNZJBm5PfNhsJ/JZgx5sx+fbRWzBe4udjtAMRXdIRX/oD+cH7V2Y/xLhilow7G0dqkw6jpNfzwYkkbB/j/Gw0/BVIykWVEsKmNoNBj1g=,iv:odXaAE7DFW5kgyGKS4ZjaNih5fVbcP36vM4hErqFxdM=,tag:q8HHGBfzTZ95GuZZpeXLJA==,type:str]
    pgp:
        - created_at: "2021-09-12T23:00:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6YvMuRc2PZqARAApJ3Oh6RpzRegyCcFrqGFnpKC9iP+i5lKwGDB7XIJzIo/
            T/Il/nUSxrzIh7azR2/pbJ/lcwDuZWYse6AT6mtzN6xlr2r+mXotsjMzSl6Wpry9
            FnXP7x7jmMDgXooi5GU2H1mkZyyoAHezula6VJINgi6AhQySqV2JMEhbhzMPgizj
            PbnrTszQX8LX+7w112VmD5M2kzQtqvqfwLwAPjSsVe3Ggp7Yf74G+84fH1gqzIL2
            kDmljlKlZ86zBSL5BoINoNJVUU87X7dqok18DOIfqkjhi6nn/d8RVw67ew28fqjo
            k7xg+YeV6VMwsv2p0253TKhVWoRI4vlwAicp3AVhkhg5t+H067tqi6n2dJnX5d/M
            e4JlaVHLc0UPCmo6g4RXMzgy5qcBtN7m38dIhPw4ft1rh6WwmZWeaiP9uOubP1Jr
            a9fHBUon9pk7ybPfKhXXGw8jqyl2B04RC8XFlgvOmwBggCcjF4lvOgjbSGHyK/s8
            HrI1/NcnW6rWlexEOFlX1YwgTAQH2PVEJ7fmmBKa6UYl6cUhqpbCyjQ4kE9vjYk5
            sxOb+lmuBoJ9D1YV1BOyyfqLl2jkfFtxDRHkpWHaUsJ+Ta9ubIVLt5YL+f3ImQxC
            /BD7i/a79TTe9cJCgcqhIJWwSdWSI8IJNo2LHOEZE5/+gQKOCSda+B2cRrFk+ATU
            ZgEJAhVpJAS8YSf9iS7eVR8WOMEl9YFiqJcXcg4aQDuWa9Syafiszt2OswwnilHn
            wg0zU8AymImNNjVVmh2QvALQtXRHyMgWFI81aYKk/zbP6qOm4YYHKRCijil80Tay
            I9LHp2teKA==
            =ihwt
            -----END PGP MESSAGE-----
          fp: 86B2157D15BC53A36FBA055FCC5C3C333A4093D1
        - created_at: "2021-09-12T23:00:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9FqixZt57HSAQ//SDjWaBqUz6H7+YYQuZlwzZRwjv+Oi5r0rJ2oZ7aA9RLW
            aBq2SUwidBbR2hCLyjDyZYkcC3qjtwMpZik2n9X9KHzUVeO1KhmqKk2JdaqB2wFv
            bDHKRpPT8IFGWvfYM+rP6Cx6sky1mBRFsn7ecW9fhvzLXN3/bgypv8U+BeKBeEMC
            WzdgV+iEcdQ4Qp7CNHL/kUyKOrwl765timF1wqsA75FzayqRqQecZZdMXROLrYmM
            u9czPi0JLtQrtcSUR0vR8ZklVakz/KA5CP5ri1+psZ+evIzyClRfhsBQSYHgdGR3
            PE6D3t1HYgrPiiAXy6pjsl46oPphQ0KyNbVzIvd+Grl1hrR6hNKn1QmGk2AFrPRp
            AcCNPe/jUGFg7BMtlbaPs9R8bwqkaDa3rKSgIRnhbAU1Ue/P0fwq6klZ4YQ8pYwe
            88Lz6VmwRYjUBr0y7xFyC7tVFsgCvAbuS2XAhZhiDYETpIcEzqvFeJHazWFXRE6S
            OZpwnFf2Go+KDkO2jXumG3feGXdoFEWyi58S86sigAJOhP/Y601YRfL1ldgUPBqF
            SEbzigNpPAufECF2BEI1/Bc+eSt2q+bt/09XsOy0GsYFIY1NkL2adTsy4TqIkhqK
            PcQOLRRsE7SjfL1JNP+9Ap7fnWUkZGXrYpi2qlqHcMn6mUWKR6xv3Q/2NtaJFz/U
            ZgEJAhVensovbPls5AWG9+C+H1eEefcBXb16qGLsgAJ33bbfKe2Gj4ujhrmRYPny
            DTMbQBNBmKRPYzUL8z5/hmr+HW5fve97qsQHxWLUNQFUqddjxor9vqIaoGdvupH0
            okV6qCaqHw==
            =JW0Z
            -----END PGP MESSAGE-----
          fp: E04EE454BEACA869B2FB211472C2E881FE50E35B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
