kind: Secret
SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:UbShVUr5Fbc=,iv:cReUupijh9irheoE8pG7bs8JkgBstCdzKNuVw43xlqI=,tag:/slp+BnMYlH6rDIYuCcgTA==,type:str]
SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:PGRYD8dj7w==,iv:wUPNoLoNTV4Knp/2jslq/pmlHIFZslpHEJ2YkS+pEK0=,tag:Cm2yLQRka3Btgoe/JZfsBA==,type:str]
SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:1iGd/Q==,iv:Yb5tc4dxvumxvzsRD7e6Jb533VXPTK0el8jA8v5VpGE=,tag:uQg5DvsOrU3/6orovDHqbw==,type:str]
SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:qfr3RQ==,iv:II+Z1rIC5WsnP9QNTtqzdezxF1SlVJM9iudeHeTj6SE=,tag:f2k81d4PBIr4MkxAxG6K6g==,type:str]
SECRET_MAXMIND_GEOIP_KEY: ENC[AES256_GCM,data:/X61qOV9no4494Oo96yzgQ==,iv:q1UpqhxqapEQKYwf7qTFkVAH2CVLuqPasTxg0YW/Io0=,tag:zBIBR8duuu/p86ko8LYJDw==,type:str]
SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:ZWwGdYMs,iv:v+6QA9rk8jSbR/rzw4VzLJQvEk6HWMuSvhOZ/jgelew=,tag:mKgvY7kD3BEw1VGw1zVP7w==,type:int]
SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:Z0WCZsxdM9NmlAhfZVuiKw==,iv:gXlA00YNzih+5cOSl/rmw3XQEUyNGUGHFfwK+QH3E6Q=,tag:U69ByqvV7oGE9RnJXqn4qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVXZTd1dsQlZ1cjMyNkJp
            cGRrTnJ0VDZuRUZ5TmNONUJOOUwyVHhWbUJzCnlRWGd3TjUvNldvRUYxQi9oUUdK
            ZFBwNVIxc0FCZXZ6SXQ3WitsZ2xsNUkKLS0tIHNxMUNRUlNKK1JVRW5lU0xsWVU5
            SEEwMm43eHd4UU9NN2orSm1Kdzd2RmcKCto/48nrb9RA7mC2VP6c4ydStYNTWAZK
            rw8UpnAxblhDHnsjIJvBRNJzkU3D6J7Cx5e/hG+Vymr0uCe8WvJyXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T22:31:07Z"
    mac: ENC[AES256_GCM,data:BY8XHLczGep3JNbt/gakYE4kOFGFDgoiIBkGo2Klgia4lWApu+D9djaA6ufedsldWnZ6umCrrUW8sjqdWWN/uRdSP+f1BJCWjoiGBM4ct4f4KQ4dWD8zG/HLyyg5lEGi+EARH1wsaeH0b24HsITAg9u6jK41jYnnXzWUX4BISHU=,iv:LjI1fcn/TAQ6bYWBFyyUvo1bJfLZquTT8srBoriN6uM=,tag:pNOjYTP7uo62AUqshitERA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
