---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tautulli
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/tautulli
      pullPolicy: IfNotPresent
      tag: v2.7.6
    strategy:
      type: Recreate
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: "tautulli.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tautulli.${SECRET_DOMAIN}"
            secretName: tautulli-tls
    persistence:
      config:
        enabled: true
        storageClass: nfs-client
        emptyDir:
          enabled: false
        mountPath: /config
        accessMode: ReadWriteMany
        size: 1Gi
