# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: wireguard-config
    namespace: networking
stringData:
    wg0.conf: ENC[AES256_GCM,data:J+U40GYAcuXTW5q3U/ZqkGvVX8IR++7xA4CvDJczYO0/OTuY+f11c6I7h+edlWFOowGR+buTtGYpozdpRAAj40X3p7jy3tpvME0Jmp0ON8Nb3fZBdeROiwwHV6PHmmUAWQUxWJJdWdU0gNhtWRDPor1FjyPo2sxb0nQVK1ozVXPGlj39fCaMfYWoSiIShDR4H+BuUHxYF7WkGciZ50p0Fe44zz/rodMBBOwcglXKGLoD52PU40LDZNT8WQlb4dW28LsYTnAB7jCUv8iGGNxaJAuw1T9J7mvw+fynBX12dMsS2BhPeXYZw6cT9cfeAQs/MTG1WnVL+hIoRBfLOEVhQiJndu8a9m2yGxuylb5G39Ree9f9mNb/5wW835a88xqYUdIVGZMtNw+DioNGZf4Dd1lR5xwdqTGLj1vxj/B7Iw2JBiRcipBOjetg1y8DnBLenZou4d2rSnzUQKbRuKxcYUKuBeMUi+8yr68YT2OLKNXTDO2KlHgm+DWRyHfZPNLqzX68t9R0rO97+/o77uIbhTb/W0etAvqcXAPgPGIqYnGcU5MFywdc9cPBaX6fnde3kPeJvl4lQ9qaxNXB0ee81ZqCjk1OL5RXNE9UnWFrKi1L97FTjb2iZIiV24nVdF6Id9zKd9t2rU3DNKfocwY+LcT4sdoAagLJ3Tjtkc3XPkD1SO6f4zQYuPRuXwvKIuKq0W/AfP8r9V/guOXXLHWq8c0gHtiwp1SBPtBju56xDO0y4/1reD4GpNGwt4AI+tCtgEDEnpuJp3sQbZxPzTK0++IsxjSvy4g1JSiz2oeaTuhZbHJdPE5dmOActJxhvQdO0qxaeBXDJVnO9NMniuYnZz6W9c3zOE5n8COHi4+nTh9Yax+MR2QV3IF1Z93si+8ZfoiA0LBcX9p2Edoxk7V6rJi69Cx+umXYT1hbQdgQl9EdHsmF8wYfVONtMs9yzae0KXsFe2GKUFOsaiKL/VNwyx437JrCxPpeYyzmkAqdsjGNaiBQfi0/e7A=,iv:XIBYaxWcK65QCHokEPCxVC05fFa/1co/fq9L4ebip90=,tag:mmsFfZTb3VdLEj8vcPbQ6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-15T00:15:26Z"
    mac: ENC[AES256_GCM,data:m8ldQc4RgCU86HMETv7HcXPK3GJQeaEzHWy6JKSs1ZxMS9yu4l6opQ9G8fQExkuQJ2ILv6j5+X2sqbSPmr0K5TmvLkVfUEnm2HRRqzc5LE3SYLiD+cY5S8v4AOvWZQu3w2xSL8snCuN6xb30ufDmL2uQ+U9vxPLwzoyRPWHeE/0=,iv:IAwV/SxQ5alrQ7VLiPZgGqOh+4Xm+xpIQvp/Z3xsU9U=,tag:/HvSPurgXUaZUIJUvOzO9A==,type:str]
    pgp:
        - created_at: "2021-10-14T18:29:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6YvMuRc2PZqAQ/6AwtRbSuauSj3YbR7DAtWf35RCa5r/++k1fu/9sXesf3G
            DOvTW0Gz1Q2IYjQofwbbmtq8IEwBjJL8pZtHCgWktX8USi+22fc8FIY8sGe8UhYa
            qIgUeX9uhNYdzzzKPdycSGqLRl7j9DGkAURGzvVXxd9L1hnBbp8DNaYXsi2Wpdj1
            q0I42kFsEo586FUe89BWQ4a9Y5sORRyMBt/THDEuHeD9akDieKIFoCKfjZORzaOG
            90ZBN7V7RRz9Q4bMhmH0iZV2i7xRnRHh0cuj/0JX2mI7cAV2LzAHKiE9j5o/jdsG
            8WKqd5oF1cHEBc53ym5n0j4hDKCzyZajO1GimUyK2NdlodaNP6ozS2x8HXR9eoFn
            HeDEt45HUUNVs1m3+kdzq6uiM9cbxt88Wr8QMWDND+uFalvdFCSe4T0vDBuTINQd
            KwKpZQPvcZpxBsmdIfQbiIVTcH45l2xwJza+yDeryqJbqqm7fRg4SIiMHt6YSGr3
            njaU3dL7BP8YmRkoXy3fsAbRV9CGNeHWdCIyi6gqPRMC4yn5KINFND9zbzyfE/SF
            vpwGUdDfwsduGuutosGuzuKloFUGyI3vXGtThJaacunfudHNBvfWjS0FI3wevrDU
            VhBAv+gqqCr5O2fimMxOOtwZC4dnZjbdPBTOptds7jTTtBchqknMUS/NYiY0H2/U
            aAEJAhVc9xkBo94pqGWjUFQfIv5+Oeije3jq2XlfM/vYgXHUzdGMLVOOlnCh9OXg
            PLYfjRsB5IMrLtYPh2lzkGjXFxH5WkhKDQHeb1DT16N0hXZjdM95DL0mf7xx6Htn
            xrMUt+G8x00Z
            =Cvat
            -----END PGP MESSAGE-----
          fp: 86B2157D15BC53A36FBA055FCC5C3C333A4093D1
        - created_at: "2021-10-14T18:29:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9FqixZt57HSAQ/+JPA6ZM0Rn9PXOb3pdtVJfns/W96JII3tLSA1FG1vyq7m
            3leBxzP7HA6XAWVGWUAdLf0M2XM29omaqrqU06TBMk7ReULwPDKxdxQhxVeTaNSt
            volO1Ou0ZKB7el4vsFGq8xzlR/n/+t6BBeIGcUkoMjWo8G2wRcPYylizKBIXbcm5
            HGyTs5xX6LHUZn1zEp9aDY+GN0dcAAwXPo/ctrBqrh7HBvgpIEw8QYJ31dlz62DH
            JBlj42w1AZdwoweCs+1XAr5N1PkFWCSkafV+/g0czme2euidz195g+AIPm8KJF00
            AGR1591yF1fLGgjcPKvT7TGkXlXWVDts1uwOseDYyfZRKzZaTKCRzBMvziVN3dLZ
            sWeQMsZvyF8wA/N5iet4se9zxJEc/nFSQc4QLHvl4UiVHmhpplRbozK3bCV4ifgp
            D9+722YX1mniD2Z7DdpyoKMBUG7cJJYWcnfrD7itogdworppW3ia/isB4jzcP3dp
            GarYLTKRdLn2xOJOzYdTp7wmWHADz4kzJnPRrsZR4I9L726XLmR9cx7cYfaX6Rv2
            ROy3Kqvh4zUz+ovn2O10P0QckoEpJegJYDO06751C6p/nCT3ef+8EHG+gbn5ttsC
            0oP8qDTiia+sZv1sAf0u0i/mR0Hp6KElLgzLPkwg5BlM3Z2sHmO1IT26OtNznavU
            aAEJAhVtIVTXMKPE56vK82OZV7GopFrXeXthCht7O62rSQT+vxshfwx8oS7B5R05
            gRFte3aCNPI6aQG7dkd1iX5AMbJtG57IW4qiRhbGLK6dM1DcEtT756TbBWmBS/+O
            8Er4VT2gfkWf
            =7ELK
            -----END PGP MESSAGE-----
          fp: E04EE454BEACA869B2FB211472C2E881FE50E35B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
