# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: wireguard-config
    namespace: networking
stringData:
    config: ENC[AES256_GCM,data:8Wty13tGhY4pTVyjvJS0FwpvARAci78OGFxxEFSVP/7BdAv4eRu9I6lqC6E0eRDxb+JVBKP3VF0aPR6xlPoco1K1GqlzL8WlI28iUOeQ2lOmgCRG/+TSAnsiMUgGBlUrVJUWPVirgJpKlo22CR8LV8kBaq7+ZTDAheozyCAVYzOtaURvodIHpNSFaHJEXu9R86LLvV4lylB5luHEVLaBr54fp3Pw/Xhb4LLHv0GJ32Felawam3UKGOll344lT3KtEqpKMEcEuZZRpafTbSC+RXlEsuiThul2al1QAWrrmWa7RxllNPcd544FUrhYYQ0QGa/UHfNgk0mGC3wZmS7zO3QuRMk2ApHoiRzjxH5y1XW+YjZ8AafnGqndjfL6ucgCXHGaZ1HdZc+wiuLaHopI8PV0W8ksHiZvbfomMtybOCmPLwmRgWR3zjgQ0/Il9zSu873e7qtpnEoF/NONlYZ2PFWHXX2ogvv9vEklAW4ZFJtxvmaqMoik6++77YqVfyfijDtLS5fHceLq/KW6nbsyDwsrbmr32KA59wjN+e0xF6wOP/KIeHcqsV8Hcs6M+gRiu8m33D2OLh0gijRrr2igHX0unr6rq+ZfGE22IPWXAoVtFU/BOQlYg0gjpoI4shE2FPe+VxbykCFM+PsitT8+IwQUga0h2q9ECTm48iNbPVv9104VrG2brvpquvo2wQsdCIwg3cQJ+kLH+KCBaWj4QHu0DBQhRJoDftBH28RGrvgJNsIXPUrwmjT+l530VMNDpGUcLJCbPPbFyR6FDgBtniSBaA6agNXizN3xRLr3fwr3kEVWEA4KDJ/EAunLNAJo4wsse0k/G+t1JMmSUefBmoVtdHgBOzzUUYys3Ah5RRMT8ldM1WCPgAIBCkqUel18Ea3ZOp6mVrAfm5R/sESFdT3pFPhn1cC3o/O+QcmnbsWkDa/nrLqnwz360lc3gwetktxsEVoFqqHIEZa9/+FKDXNguR4FRgiEMDWm/MewnMo2+tOFcohieF7w0L6RZzGB2kmCHX3cJ6UGKX6hZ6FdyxwCS3Joxo/XSidl/JVENTyTkUKcrao+j5T8PpkOryJR7XIzl81qLxPMmVSJ2Svj2wHe+P0/vyIryp5r50xaRe6uiXLFYC34WvTOOgGBebnSKyQokJlV1wQqg2+wAY12u8X5HGv7g5CAtGV0B9Y/PF6KV3PCCRwm/dIjc2iGn4PEspjJ7OxLUaw48YBLzqQeSeTB0wizdoSDUlk0ttRzKwLUNFyHv9UsuvldEeoSvXDko1Z6Gt+PK8w2irsEx2qzHD6h+tK8xys38qcsIFyKdsvGLyQ0h2FnMEz7Z8EYykd15K6YhRclRoQ5VWm7X5zev0Boo4sUxOCWVCM3hIc0UQjCIaLP0kXXCe0nMi9RbqqbkcIHU5TA9i0saiBJcsoy9Qu9XO6J38ZknfIcefOIAV/HFdMpKVFX6pzkJt+90D3+jlhV,iv:1dqAqt9uPNUWvcpALgLGmPESOc3/afFgBNfhYkr03uE=,tag:qW3jGJDMTwP8DN7EDUKcbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-14T18:11:55Z"
    mac: ENC[AES256_GCM,data:5/Lpd0kvdGojqVjguyPOBCc7RKAP9dkKvKjlHkL6LvaOSOFGzPKSV7nVVNWtovofya7XWuiK7s9CvXVHbBACRaombmBPRxoWPKkOWpXyEZ7B9bmfMRcFMWveIFqhm2MeHz1U6buw7CHXWVtePnF6f73w7eyakQcyQ3c1KaLrJ2g=,iv:pg9HYBs0UrFfNMFZKZDhGWJMvBvmhxWbTedbibt9U4k=,tag:sj3lnOh2M5vtDwOzgKgVwQ==,type:str]
    pgp:
        - created_at: "2021-10-14T18:11:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6YvMuRc2PZqAQ//e4amoFc7+s88cWm/LffAL0vJt3P8lQuMr20nj5RQMYMX
            cGz5memKwvUTumTjykxID7hrMLURF8WJCeKx3qkllDNijHX0m1diGUCMp9JK7hLB
            sKMicjBvn7ll6F2DKGX0AfruUhX2OEAKb5Vz5c6E8qUYRmoQX4BNyZE++9ZS/vyg
            5PYjRJ6wO4M2B/3iLpHSW+g5Yf4L5fO4Ro9agj6n86ItMlz6Ph7zM1VMWGN/EhZS
            B02Nv7khGLa3dKRNitMNga297t7IQrNfOEVqJbohPyZwXqIermzQAhIrujc9u3Ku
            Qiz/84WGFoUHOjF6mbJ6lMdriPE/TqjDZK3SdMAvqB+AZ2GE06sF5VhfHB0+nsRy
            nNhJRRSL44X58U/0f/E7haXzAqEs3Dkx8fQ3Uj75zmpxmGW8lGA9ZEQxZmeJln4v
            Si9MP8ZPbH+r2JAkEluVARANPtfYP//3nS+qYD3P6ApUEsuUUf6lSwJh/yC3xoEy
            UpZclIUCbWdMB9lmyVdvr5mfsqOT8dz2VczvNgVa2/+RVs1MKVcSfBe2gs7equz2
            WLEI/0KtrHRboqmicR244EtYaIQdqoPlX4IdmP5Cvg55G15gYdhL8uC+A8CLVBPO
            6SxepeA3UVpZZ0rfK6oiTvZSHioALHqm7acWcoJ1Np4K4PlVt0cff0etN+wqM3PU
            aAEJAhV/05M8XxboH8w6ZML+QbnyNyd17ngQPqcxocwWUPKlprvao6h/LjAXnjPg
            0vQZMyw4rkkdpilp7NTHLknNrMroGiVThiBXZZ2tQG56dQCT5ZRW/kxhMrRQlgyd
            J3tC7cMOGuk8
            =9HAE
            -----END PGP MESSAGE-----
          fp: 86B2157D15BC53A36FBA055FCC5C3C333A4093D1
        - created_at: "2021-10-14T18:11:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9FqixZt57HSAQ//XIQ4fH4XRZRFzFyyNJIpwH+2hKLmzqSPBdAwQupQgn9P
            pK+E8naLLPtsbfWzW0P7qxxcp/0rxdxyy5gCIAXDok1wDfqhSgoekl7UB/uCRz2b
            8wwI/4g5DMp7DJYWm+T6+jXlDtf6fbnNVVrhTX4pkxyX/oc9X2i7VqtKoMAZ7rfG
            4JYbzxWZvefsVkAe/kgg7iZMfe2XLG1JSWttqcjhCwS2QKs2hvpW7iEnL3h2QyqQ
            LsiPRNR97eR/0L9h+yVBrhOhjOiyzpsmeYT92truS5c6zy2C3G09GC7pnLiDfx8O
            n8FiHfaCPO+DSQnyDTQntGM6TYqVQkOlnXVI83yCXMaEHcikHuYXc98bIoHQ8fZE
            vr3sieZ7pFc79DpMNTkQU2zYXiIj8OlcM9Ax2FjAYoAcIqy8AC7+WSp/pTFe6hdB
            /GPTPmboyeunZWj9nsqAjxIGbFT8c3G6eqQsNu4XSpWKuFoB9sCG+GaHcd3OC7kz
            UBWx4BGLIcu5kl4GC1KDXbnJsLYz7svZ+1aklP9LC0sNN4BAzTMQS3mbwpV22d2Z
            lVzNZqChBNbQN/BzbS5S9IHz9eqLi4DDmCat9yz0ueFYlUDpZZFjnRC+bhmHUT4L
            wBhemXGU0uX9GkHrysCC1P13VA5CHI8VT92a1XAzuePBykyvMpSOr+2F0mVtvzjU
            aAEJAhW5Lw32PMJ8HduJvzi4kjZpsa7MVYkDUSZKeyx2pCyYiA0Ro+sYsPzIaT3t
            cQWnzhTcVJG5E0+dY+GShs3jw4KtDubc39PuunAKDh4UI52h3ccS+sE8o1hkdmnl
            tvStVnboPFV4
            =0z4x
            -----END PGP MESSAGE-----
          fp: E04EE454BEACA869B2FB211472C2E881FE50E35B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
