# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-home
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:voiDBHIXh1mQN6GPSJdGHyTNTUES,iv:n/hA+OAU042KQOG8s2pZbCdfoDxVx3OuXJ0drNBjbFs=,tag:cLL0HExjFRRMhffKWVW2Bg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:25l1vd5uNjt94YVeg85/+i5RCwaR36E3hcs8jBDkg3mp3lVZlQ==,iv:Bf0A2RzzjzPXh/AJ80yCciqf2qMZx6b4BLDhnIbQ+nc=,tag:/eZDmgSewhCxOsmcy4yMVA==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:647s2G8x8Awi6YZiPrEYgrf/Kj4jyZkzSfBKrqpUGfM=,iv:neW/ke+ys4mxGAYP1fexZPLniK6gjj8d7rl3moAi8xY=,tag:XsBZQ6VRy3NIOB5FNj0rlg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:aelQ/43Fg+0=,iv:ISLfnwor3D77ckfBJd9dnP2lDkeXqgWdSZC/Q8tuQeY=,tag:dh8lTpU+eg1QfZXXFpoQtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T15:26:44Z"
    mac: ENC[AES256_GCM,data:32Qih101/1nXYlkRnc6c0pN0DWIyhdmrv6MCKRBFaVbtY+2jm6pO20NvycDPt7I/Gh1GXs2grV9yXpQsLin8QllFCsfwM5UKgP8gHzrbj+IraL/+HovC6DSKZ/U1fFZvTLy9+aKffBqTExMSWMHEMlF1FxjrphayIAmhldG4HyQ=,iv:6A/UF5klfj7cBeZv1mGV9fI+OdDTet9k17+A3fzu7rM=,tag:xJYqwZak5meScj171cicSw==,type:str]
    pgp:
        - created_at: "2021-11-08T15:26:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ//RKaruynlhZN06E8cQcXwd5ggWkvUqHTr+znOGy0cFa3f
            L7wgS/YWI4Fvjt3Du4xlZ84kiny0rOpSvgXwT+EOCwYYjjiqjZ15yaHLPhXXUcNc
            LDuzywWHmqBGA0mdf+wwJVyLLDpcmRbT+HrSnhtFHbnOid6SsckVRT8lsP7BUaet
            jY4kletXeRjuHdwBpaTZge75hgLskhW0Z1Zfto2QO+9H13ivrKkfsH2nl/0ckgH5
            qPcQZHG7d8FpF51kHubX8SyvRBW05HhsTKpt0IAKcMDYb27itkmYfupyvU7BvG6I
            kDSNL2N59Biku66uflkkgyJ5FZN1jQ+BEEcWxx4cvmtP/9nkayCBmRasVuaXSeXP
            nwAEMLwMKpRr1Q03jdqDwXhpbIPU0seRwdgGngxsGANB1oURi2N9G2AuRwfTEi6k
            cdorXOa9RJyVjqi5RIGThxxGRwxQq6CxSbTt7tuxONKLfHNGGThJS2Cu/q6F2dtx
            XGaexyZ8DnqNbnHx1gEFXgTR8tuCEzeFkCbfGKE4zab6UvOvZZLtOMLYu1zSQm8n
            /3avGd17FL+1egi/+Fk1rXnW/MK9uXHR6Tyd7bvdlc8r5AADtGzCNJGmRrX/ppML
            WhrXut8WRIt21CsOOF4qaZkgSq0OYEPIZxybe9KdXmmaLLYsH571ytPql2t227/U
            aAEJAhBxUglvWOQ06/Xa9xx1RhzqoSHDnnkWQDe/51/p/Qo/5XZpqv1oHlZ+sCAR
            oOobZczpTop1Z3cJPBYHGA8GtMNphsYqsnulVAT4Gpr53F8NkGa2oOnO8PQ9EM+x
            jJEgLT5LqXhd
            =S9eg
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-08T15:26:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAgNiNg8VumpjHn4flowiYnbD2Pmla7mNCLeag7jAC4hVB
            U3dwLh5bJRFItChgWApGKkB0fN1rNo5cklYE5uFloZ41o52KHp+7PsBBsXDu4nre
            YguyjIzA9HEo4VdKHb+FffhDjQhOLlG/g+ND0chkskM0nrj/qfcGtl+P4pOgwUnl
            NDWIZzG9c6Ib5uQ/DmsRVlxjvVsfCxq09Oi8Vc35OUA7b08c1RBVFAePlp0oY2d4
            s8fQ8DrLsjTvd6Q75mKOk6ypXiM/lRi2AcKYz04sKUAfoV83vDmzix0fd9GGVycA
            v6m1DFX022x7q9O4vX5MPlENSOYrTDK0F7lSh/LhH/MtVMdVda/D7HmODynKE0lV
            UM+qOaL16AyZxOhyRP2RLQPoJdNk+2d2VWRiLBizfYoarL+K/5UnT1TXhyiqgkw8
            X4W90bcQQ4aXjLDX76DID8GF/rR19BOjNu1ebBVp58ATJrsgvQvFQDsIB8rtFdHk
            VcG92YXVQLiwQSFCmjHvwEk2MeuZvf/slkzVKCSdm+1b9+zMHVuPDPuH2cfJGjYs
            wERqu2FgmeoIFHqPC/p6VFVq2zH3bkear5wVgu/B97nRCH5ZfxC51ADUzS8Vob3e
            faNu62IW5wngi6GtdoDTjmWMgJWphvq+LphFv3ySTTwCQUbG1uQl4NcPzYY9vaTU
            aAEJAhCs+QA7shRh/j79/IERUlUGy/F8beTL59auZYAWxs7zljFlZARHRA20O4JJ
            4vM1+hhhiTGlmV1PZVKrDv34rBFMq0Orr3vmNCIjAzQuh8I399dEhwPiX/xQOrZH
            W3xnODxGodLp
            =fIwA
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
