# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-home
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xH7G7svHe+o3d1ouof3U6TvQyGZW,iv:n/hA+OAU042KQOG8s2pZbCdfoDxVx3OuXJ0drNBjbFs=,tag:eqBHtQ7S4Z9Ov+g97uDheg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zlcVrigvrMXMD5t9r9gvjVsQjlUyvqifpBGXHq/dc+TJsNx6gg==,iv:Bf0A2RzzjzPXh/AJ80yCciqf2qMZx6b4BLDhnIbQ+nc=,tag:buOCpx784L6TJ8egO7xbAA==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:2HYHVwDuRUdMpHwVPBSmZmo2QWbK+XOYsX+Xkeyare4=,iv:neW/ke+ys4mxGAYP1fexZPLniK6gjj8d7rl3moAi8xY=,tag:m3CkBZJrx1rK0YeGQ5CUGA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:jOOIOZvLX54=,iv:ISLfnwor3D77ckfBJd9dnP2lDkeXqgWdSZC/Q8tuQeY=,tag:saueoY2rgCyrMy4cM673RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ3ZYaTJyOVVhZ21ESnFi
            UVAxWWk5M3EydXRsazFEWTEzVGdTSFBYN2t3Ck5SWVlERHNQRHFKZGpUNXVNSTN0
            ZS9ZTFNWdWl3ZnBLNlp2T093UWduUEkKLS0tIDB3ZExlOXlkcGM1UVczWWpGcnds
            ZUVlTlMyVVJMU0lSY1VFZGRKR0JaQVkKbatbN65l/VbbAxv8jDU8XZuN0ggoWGjN
            TD6JUFzpz+jxtGbCC3af7eEt7k4aaWBCgO9E/4/9xWh4G+fZLv/h/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:39:10Z"
    mac: ENC[AES256_GCM,data:crz3IlYCfChyzvl9XDwOOpEjzaO3FNwwSuypUjLCwO+tGxcYEljhNTKqszzBaejNq/vHByipXMblGUldMdelrZVdUzygKsTSagqblUY8qeg3U7iHQeXNObXk6sftTL5N2N8k9VbCXj+/jhph3SmqcP2D2OYlCO0+zx9C9PvViL8=,iv:3MF3/4V/2cumErdRkf9jSTf2pbnCLJhMFMgafRMLH+s=,tag:3p1o42xR3FWM36CQkMZYiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
