#ENC[AES256_GCM,data:SIvuXD4N6lIUAWkfyzGfGoc=,iv:c4JmJLaZbFvjcj9LQb/374fepUTDrfVxuYrxL2YXLlM=,tag:dzQotKdG+eaCZfVYmGI2TQ==,type:comment]
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:8tiJOhZJkRjj/w==,iv:kmj7EQ6ptfApmCGdGC5qiV8+KLxSCJLE6b+bbiGcoLA=,tag:/7OPW0SFLjakW+2fTxuxAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NHRsQVl6SWgxajhuRWZ0
            ZnZtb1lLYVpjc25JcGdLbFdRT2VCVWRUTTJFCldja3JvOVRCRXNoeWVmVWZmT0JZ
            aWl2VTNEbjJHOHhyWlhjdXFocDE5MncKLS0tIHRQU1htOWNxZVg3R2hNSi9vdjIy
            VzZUSGtkaElLTDFEUW1yekZYQ0hsSVUKhmzcSH8i4GIV1VWlP6C3VQbz8wq5XDn/
            gColtk6S2otZ+RzlkoecJQ+ruGOvAbliStzm9v6IY54sJhd6ba2xNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-21T01:24:13Z"
    mac: ENC[AES256_GCM,data:BfSIC0R1pWbNELMeZ/tpPv7XbUWKkJGfvkNxGX1Pzob2+0TyRfUdSrbizDg0ICfMY9YTc0ob/dgUjRHPVC1pqP5HwtMtYmpSZHhn7LTHzSTO6s5wdcadToogYIIeAyPUJ0kbQyhZXMuCleqHGsI1MF3a81H1Vz9xMtw2jreD+Wk=,iv:qRffNFyHba77oS03HFN4A+RPvMe/aMlHuQM0CmCMt1E=,tag:DswCkKM2SPgKUA6SyH+SUQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
