#ENC[AES256_GCM,data:FOK1O5GO/OMF72mqn4c03VA=,iv:9gngK5OwfnyCxuHMVmDQRh9KkKz7/OES7A2siK8rQm4=,tag:+q/0lLauOs58+ngGnzRQ3w==,type:comment]
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:TYxP7YWk/EeyDQ==,iv:be02p0azopFHwBunXad8dKeZA+AHov47D4P2RW2q87g=,tag:Ohu9l/hNMPUCEB9RaO2XkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdnZDL1NsUnVoaC9LVXRV
            ZXZDeHNLRXB2NDd6M3R4b1VNZjJ5TGpZc0Y4CnVlVmR6RUhXWG96VWV3c2tjZ1Fx
            MXZlRHZ2OXFyS2thZkVveDNmVjJMVlUKLS0tIDFNZTZJMGd4R21CdzhwUnJGVUZO
            eCs0dHNDUVUrRWlxclNPbVNhSlMxSlkKRYMyVQrCorGkLBiBR2HtdcJ+uLUdmSfc
            K+qVAXmreNokpW5Ly03sHmjE7n2c+bP7gG9vDoma+jVFmAFQLn2bTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T00:36:51Z"
    mac: ENC[AES256_GCM,data:9zLQ14jT0GTtRbSjN+hip2t13QnG0AtFPIsuYCminJXF3Jq4jejcaLWHZ++XLtmrJbk7LFKNAFdvebWnk5u3hDVFbIia9MrAHNoFiywaZNMa5giP+XXBOkrBQmaYOIDWRkYwuktQYsc2bcuJAGrfBe7nDHDPLkpA2pROFckW2nw=,iv:NauVx/QAbig+Ywb0PnbhkVwwujByUqeNvF56gyPKxWo=,tag:H5rnBYHXBGTGzijQzT0XJw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
