# yamllint disable
kind: Secret
ansible_user: ENC[AES256_GCM,data:qz7dQN3l,iv:DdzeCoazgUi6OZO6ext8hUJTYrJM2iGl3ti23s30CIk=,tag:l8h6I5G3EHgbXxmRnyxb3w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UggZCtNOIbVIsA==,iv:K+dTNw+kad/LGqqAvpss9iIoHImNuC6XKxDNGBJNPZA=,tag:q2qnkBMJ+XQ+AgsC476oeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVEFweXgzcnNYeEZ2NVJS
            UnRaOHBhbzFEa1lxa250S0F4RGxFZ29TUm5vCnVFWU9YVTBPQ1ZFQzJaS2trSHZ6
            cUU4c0FKSVkvdlhiWnhGTHc4dUthS0UKLS0tIDVLWjR0d0NpWU9VN3VjQWdoOXBz
            RGV2aE5TcCs1dGc0R3oyZkplRzVSYkUKOK2MN7Esq6HkxSCb1+VzieSxte7rd5Yo
            UfHNaA+rRMfL+9BtRieOGSrLcLCTzMw12yVYLAae47hoccyG/oSVZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:04:38Z"
    mac: ENC[AES256_GCM,data:ovN30TXD9V5zzzwqlPKohL+81/5UqHST7cHYhuGKvUDZlXACFa1XY8bKRuqM1/XgBg1WFi7dvsoxr03sgB1PK0DiDLgGoubjHZ3OGknFuFGY7/FTly+amXtZ+3RBbRlLMGSa3N/+4vwxVvcngMZ4cGpnZjYmk5zm78PgD2dBjks=,iv:P7yNV+oDPwbY092KiJA6TE9s93Dxyb3OJFCdTEJrRN0=,tag:lHCTwn9hDeaQqSYz55RxEQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
