# yamllint disable
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:9HTSXWf14BIUuw==,iv:Kwtkzfo0oblUVcgHHt7j52ibNptus5R1X74WXcnIBPA=,tag:sXBAxu9BFhB+o+KqWeb1Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-15T04:39:56Z"
    mac: ENC[AES256_GCM,data:sGenbZe4/7G/rCFhQ7QIuE3NOIr7J+Okp4ICy2mpZnQ5FO6tv66DTtVtVhZ/5Itz3OKIDJ3HENzaMaX7E25MVCw1HS+u9fe9k9XxS54wLMKhFKwl6Fe7y5BbQgLq+kQqE8zw7N3hLXDr8SMdZsbr3tPswcxv9SF461gwLQafFAU=,iv:BBbGK5qKVIUw57NxOBLZ6M23oBxtOU4lW6wmlGCCYRc=,tag:UoiGdOhL/7CJ+M9Slv6+uQ==,type:str]
    pgp:
        - created_at: "2021-09-15T04:39:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA04Hh5gxi1K1ARAAp3RqpZLMPd8VYUHaBP1gAEnKLoNLe6SWoZ0sejcUsmEY
            KG4EezcY8KUHEYRYOu1Uf4ZSAa5vReoA1kxL3VUapfixIoheRxPTift7jGVJugwl
            Q5QWbn0ZTRmihxVZ6OhkThvD8eZmV//yPAC3l5VcWF9nv82jyRJJBbHUcjHvYtOX
            CAwBSt5WDHR0D/GRlaOqyUWNtpTdq0lMNoR2xM/KIE/2Mx7gQY80TzHILs+Qr9re
            ZhVDhwDvPj4ryZewxYkqZ6mQSPdSGe79RM7fikB9gIIVvFEJX79jgN3h1nHGfr38
            7uCiJPsSFQzPjdPSmP9BHUpcyiD7Y9k+LmOY4BQYpaPFIm/aAI8JQtVxaipgqDeO
            vSfZ/hFwCXfsuFkgFjivKjqb52YXbbBr4b2nLlyh6iv6i66KeOl7s6j6TnazbGmT
            9ajSklU93xgbimspIvA2pVdJpRU/A8MUOuGsADC3Y24whfJjlLwR/ZEl+yshZWyJ
            pR2RS9wtSAimS/Zxj+mEvujBMa8Te9mnCc8UEkpTp40Y2ja9T8oDNMz/kiiKeBA7
            9eC3MyPHGC4eYuB4035q317HhRz2PMeszYO2H7U2T635iOjZ4GIrU6iWkZEl7N2K
            qwpkRFrVlYypP+dTsvVhP28pM5VB2K0vfQNPFPfSpo9KmS+TCKAt6zONDC1b2WLU
            ZgEJAhWhPdUroBP/2b8Wm6dxhEciMr47TcNJMsIDQJi0aY0jUFVDhaY/JeW0ER0y
            yY5EuXBNgp2cKmqRmcu6uOgwuuJrz3CV0O7zFPYxmELZd7IyXvMDD+S01QyzVEiV
            EMbe0QJ47A==
            =jvm7
            -----END PGP MESSAGE-----
          fp: 16AE3913B4C05B587909A154A97B6D4ABCDEF447
    unencrypted_regex: ^(kind)$
    version: 3.7.1
