# yamllint disable
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:q67KmfJP8uA0ng==,iv:GiC3vv7T335LnRvwShuPIUoM66WHtOZZmBvdTE1i4RQ=,tag:yJjfjousS5duyKLoH4Ac1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-15T00:35:16Z"
    mac: ENC[AES256_GCM,data:DA292rhhM+0YzmTeU6VcX7o5bT6/Dv1huvIjkTQHSv84b1RaDbKQCkwSgHdm+Fuv19dvbwafFF1SOKs7xIdzugTFz1WASWNK43kYjpH2bLDwEkNrhBNTZe9mEVBQdbjuuvYpPRS2RTQKrSY5E3M/i+8z5hOh2d01PAR9CmFjPgE=,iv:09YScFjLmW4erPBoR4o9X/KabyzSRncgyhKchMVqthc=,tag:jdePsOTK+m6NoisGE2g8eQ==,type:str]
    pgp:
        - created_at: "2021-09-15T00:35:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6WIilOBxyWkARAAsdfyNGFopLLhrAqs7RVsJ+hf+xabQLCa+cPAHMZc9P0/
            2B58r51vWolyndBME0ttHzBpX3zKB2lZePL5PsL8LRTniCoWbleFq6zPA3PaVxGH
            qiqPLKDgzQv5UwXAMU77Msk1T7IokjNKP4kokM94kPHOdSnmrXfDEmdpx3R3k0nM
            lfeAD/RYLhQsmSEHNaB6nZ2rxqrMzw94oVykHBf1LpIRO6yWS0btl+03lTrCLI/3
            yUJei/vu2p6ahzdiPmo/vUvUaiJuiK6vM7PEXu2VuOJr3Z0mP+pYrUj00JbOsHUh
            RIBhck402uyvPnkXA0YQFkmbcffxJj3+ypEv25KJZ5a+9IK1idvpbgqFCC2Hss3u
            nqaKMrTMhinsCd/J+cFDi1VcQCBFClPi5B0wcPDpEwtVVwEHoYe7SqhQY350ABYx
            VSkv+WIHwzl1lcZT/PNzWBNPu2GtcBbWmnPt8E22wpDdp2+KMHMcoDaOD0l1v9zo
            JNBGbdFfY/g4pNRR/MIOQAp1kz4Yfkr6AM4uK9VT/05uDkSxB5EwGQDgyxb+UG7D
            l4H1GGFbertDNkUCwo6SCxwbdIBXNzJNTsREG04VfOLx3GyJabDTSbVn20shRU6A
            PtlUB+KZM8P3tNt6CfJgLn45gj4P0LgCYwiDIxWb1T9cXqObDNx++hDNtjefVaHU
            ZgEJAhUePaUaQhbOF8vWs+0ow7FR3wdO3XBSHZtfuQYrGkqGm0JhczpoooHg0dqm
            eOUiQQvyck0wVLzPoE3/YwYTQlw4AM4dorJTq3alfd3L6DkWVYS0pF9B+g8QG/IE
            C+zoExLFrw==
            =sP+7
            -----END PGP MESSAGE-----
          fp: 6ECFDEA57C701C60882FC1617028FE4C7F94BFFC
    unencrypted_regex: ^(kind)$
    version: 3.7.1
