# yamllint disable
kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:TuQe+d2qJhndrA==,iv:UW6DAAZgIy4XIKjGrOSLzCSVZGYKoHbZal4d+7rGH5w=,tag:JiF54/0oJ+TmDjUICeYRPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-15T00:34:19Z"
    mac: ENC[AES256_GCM,data:X08CAQd7vcB8UjY4bN5EaEvmbYevENP1dF3D3SQp/Ugea+O/QhGydeF0r5kVVuMKBSAtdGF6HUpHoFy58HedKftCzNTio1EjGCYHQyZNSruXC+XNdlRHG2CULghg2qStPuoq8XgJS5StQybDjsZYboMlK3YCB9wQNEYY3ykQpfk=,iv:Q0xOxHPtKIObzRve1eUS+5q8+yRf03yMBFXNUWjEWx4=,tag:Ys9c/G+MBrXm+Kr14fhUlg==,type:str]
    pgp:
        - created_at: "2021-09-15T00:34:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6WIilOBxyWkAQ//SJdTivDoMHj90Bk+jAxVky5iGqZF582+drzqJEkMNMlh
            LDLBfTiqJo+Iq1lBURWG2zhnhPQdVxtNv4xZnkeZ6/6zw23554pGMePVeIrnBaGW
            zpkobUztInoEDIkQjk2Lc5meSk1IQEUEzCWmh0hE36yhW0ma5KWqTIbCkpXQhdf8
            Gknf9I9BRWZ4gQzPmkb/0k9mgNi4CN9VWER34TsNp7m/Cw2eTSASUUyzlwKyZ6bv
            bNJUcWZNUkIsA91rs10OmrVwYxdzTIXCK5QuwTZQIc4cW7/w+kpw2J2YgF9aDxQA
            LXaj/gr/oV6dAjaCm3SOWe/0WsYMujXfJCrIsaE88o9zuv/FttDT5JcG20L5Zked
            AUJaEtIAapgAboOwrHs/1GXO+GCjNUmU1i3wTIJ+YAAwcbYAI71T0K+fGmsipqcS
            4m8gySBMSCMSU96nBMdvdRQvqB4QBgKWe64CCoJP9jcvkWbDpyzlojBWCBEM3Zw5
            QPc3nMYnea4hOL/o+Z9uD9os9V+TAMvC/EjqWWHBl+48q5VkECyhtcs9RA022s8y
            cUUJWswwusOUfkSQqpzUdR/XdDpVuDlTDpxSxys6wyuB0lT3H0IWwZUq9tdBguSB
            UCqKolj4tjXZ+kRklv6JDu5EjAwWpaqAy4WDU6k6qqCKoMJCGj1gCuAleHbfm8TU
            aAEJAhX3JTz+y/TqhixNK/RmwU2UVSOmzMfd5riwGyGIuOoLdm1cgsigm4/uVxGN
            ML68A4iFCXRJS6ATMmwWSBkpdsLfBZxh3kSl1mCJ/JVWxJnwYa8PTtDZtEh/N3VQ
            UmmUlU20M91Q
            =ZOV4
            -----END PGP MESSAGE-----
          fp: 6ECFDEA57C701C60882FC1617028FE4C7F94BFFC
    unencrypted_regex: ^(kind)$
    version: 3.7.1
