---
# TODO: sudo zfs set acltype=posixacl cairo
zfs_install_update: false
zfs_enable_nfs: true
zfs_manage_filesystem_permissions: true
zfs_enable_samba: true
zfs_enable_performance_tuning: true
zfs_create_pools: true
zfs_create_filesystems: true
zfs_pools:
  - name: "cairo"
    action: "create"
    atime: "on"
    compression: "lz4"
    devices:
      - "/dev/disk/by-id/scsi-SSEAGATE_ST4000NM0023_Z1Z0YT0L0000C3488ZVY"
      - "/dev/disk/by-id/scsi-SSEAGATE_ST4000NM0023_Z1Z1AX5E00009352M314"
      - "/dev/disk/by-id/scsi-SSEAGATE_ST4000NM0023_Z1Z20YK400009409AKQ8"
      - "/dev/disk/by-id/scsi-SSEAGATE_ST4000NM0023_Z1Z2HE1G000094175LNC"
    type: "raidz"
    state: "present"
zfs_filesystems:
  - name: Media
    pool: cairo
    sharenfs: "no_subtree_check,all_squash,anonuid=568,anongid=100,rw=@10.0.42.0/24,rw=@192.168.1.0/24"
    state: present
    owner: 568
    group: 568
    mountpoint: "/cairo/Media"
  - name: Data
    pool: cairo
    sharenfs: "no_subtree_check,all_squash,anonuid=568,anongid=100,rw=@10.0.42.0/24,rw=@192.168.1.0/24"
    state: present
    owner: 568
    group: 568
    mountpoint: "/cairo/Data"
  - name: System
    pool: cairo
    state: present
    owner: 568
    group: 568
    mountpoint: "/cairo/System"
  - name: PersistentVolumeClaims
    pool: cairo
    sharenfs: "no_subtree_check,all_squash,anonuid=568,anongid=100,rw=@10.0.42.0/24,rw=@192.168.1.0/24,rw=@10.10.10.0/24"
    state: present
    owner: 568
    group: 568
    mountpoint: "/cairo/PersistentVolumeClaims"
  - name: Tyler
    pool: cairo
    state: present
    sharesmb: true
    owner: 568
    group: 568
    sharenfs: "no_subtree_check,all_squash,anonuid=568,anongid=100,rw=@192.168.1.0/24,rw=@10.10.10.0/24"
    smb_options:
      browseable: "yes"
      create_directory_mask: "0755"
      create_mask: "0777"
      guest_ok: "no"
      read_only: "no"
      writable: "yes"
      share_name: Tyler
    mountpoint: "/cairo/Tyler"
  - name: Matt
    pool: cairo
    state: present
    sharesmb: true
    owner: 568
    group: 568
    smb_options:
      browseable: "yes"
      create_directory_mask: "0755"
      create_mask: "0777"
      guest_ok: "no"
      read_only: "no"
      writable: "yes"
      share_name: Matt
    mountpoint: "/cairo/Matt"
    
zfs_enable_monitoring: true
zfs_monitoring_capacity_threshold: 80
zfs_monitoring_scrub_max_age: 8
zfs_monitoring_email_dest: anthonyjrabbito@localhost
zfs_pools_scrub_cron:
  minute: 0
  hour: 0
  day: "*"
  month: "*"
  weekday: sun
