apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/GzvW7RB827q5Tw4JFjFXA==,iv:Papiw1BMMdrVvGg62PY29h9RI3LFM9Fv5Yq5EdQL0dY=,tag:cU6smgU0oiL7TsWgmh8D2g==,type:str]
    SECRET_DOMAIN_STUDIO: ENC[AES256_GCM,data:4j4YytJxZt4NE+oBEkwMUhzmzQ==,iv:hAqmiZWl9ZT0ldOLDyRUc/QATAIqDkN5bYniJQai8gA=,tag:xif2P8dYD/spJYedCtaUdQ==,type:str]
    SECRET_DOMAIN_GAMES: ENC[AES256_GCM,data:BKn6nsE2EJyht1BJ,iv:JOQ0on2XLQ2m1nNG6crDj1MLavxxyBSoxY/tPozsVCQ=,tag:FOP0LNl6uflC+MAEyZhfbA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b86svb5+XCzPupSYR3ZtdoboqcZQ,iv:sxDfcXEPgr/qNdm2L/iYMjhN2nmIuU1RS6sKCdoc3k0=,tag:MVfGQ1zBTz9h5bbtXuRq1g==,type:str]
    SECRET_AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:VnO0pZzrluBqHZg9i/KRt9wEKtyRBqelgADChUPm5gcSGxUKFns25xO4PsL1Azf0gKq13A4RBFcjVexuCGaYwybdmYX0,iv:TuIpK7Asnm+RMZqkrKVxp8b9c4E2HXlTrBqskQUGoOs=,tag:fooefbmUQDXHwC3rAH8hlQ==,type:str]
    SECRET_GEOIP_KEY: ENC[AES256_GCM,data:erbPUItB5pkOzYXMa+9yJQ==,iv:bCsWLfEhOMpBPSB6+KlQxUWX5spbxHT2eCrMK7f9ow0=,tag:r9Y88sX6+buSWMIn688FPA==,type:str]
    SECRET_BITWARDEN_EMAIL_PASSWORD: ENC[AES256_GCM,data:z7SpckWUKYuA2nFiajwhsUfjYBrSN3+Hq+/ZAD0omOcNWAVqAdYc/2IvVKe0RPxBDKT/utRIGLrZ36lPDaf1tptsmcZG,iv:ZxFxAH+4SmqlKIDDRU2GQB7qYUK1sWFVBcuSuJX2cCE=,tag:uHFX9cyQH5t91NJptP2tBQ==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:5cU4iOm2ltb/1GE7ZKTwOzQ5PlOKm/MJg6D49smZyU8=,iv:zCjQgomsUyJAXsVO4XdfCTeN/jfCZs4oaDYLhVKHxkg=,tag:F3nGffDA9bK0Fp2NTXANHw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:KG9NZYCLn5+XS5gEEbqkGIpsyXq4itqLVISO9l2zbaLkWIRVBHRa9NS8EefhuztwTFfzdZysfAy/9uEbI3IARw==,iv:h9cK13g+1fiEw5VslaBFLTcGcxgZgo9eVQOZqWp1P78=,tag:H9IN3YFhRFQsHYIfBHvzPQ==,type:str]
    SECRET_VALHEIM_SERVER_PASSWORD: ENC[AES256_GCM,data:4OOpYOwXIJx6,iv:pwLymtA10oEW2w/4CDmz1pPq7WFZePw24nusg976deA=,tag:HM6BuJXWK/Ki09+wrkn9SQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:oOs+Nf1wb/UCAtzNpjHanXDrzgAyid/iaxDodjba6W70wbh6,iv:prwKkkW0MPD5Z9iJd/1G3fkhjQSNAZba9faUrd6SpQU=,tag:7AWxRw+yRHNhzz0jHG7tTA==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:va3xyu59nkQee46b1p08PtKFdenDRhlH6XiUzPq0oIlDf9zI80Hp1Xc+us3KnMRlKcI=,iv:rAZiAXahjbrRI4L2xfTFytTTxELGyNEI/BnX6h+SKA4=,tag:7eSX+yRS5QQciRmy/7xT1g==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:Aso5ZQjBmPKHuO0PEyOvPQ==,iv:gPZantL1GRi8rGIWM1xI/NKTUEw4xbpvxsQ27d9UOXs=,tag:DMe7oQMyuA0q7ezrd1INaQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:ZJPdrsMV3FjbnFJRMo2dlw==,iv:cfv7hetzwq8MV/kYqL7NuECzjyRClM00DbLiYo/Xd9E=,tag:G61BQj0UhuCxjgA5YTXUTw==,type:str]
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:DWbUZlLZ+7HwbnPi6taltegA9qEI0eZZoSKaGsB72aErI7bhsczRnj9nqjS0aEEiXZOT8Q54akupUQa+4jLz/d0a5Q59DgRPdXpg5TwTpqhXaJPpBj0Ss9yGmRAc6RmW35DVhle8nIPQdZIz19UlOiEov2h0ONwiyo4k9k6V,iv:MwmAm8+vOheRSrY0C93mfAP72CElTovnDTMtb4yQMF4=,tag:2bkt0TskQA+6IH8aGhvDKQ==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:OMZGsjLQehhPQPXDKYMzIryvuBroHtEWAYKDaq7b7B5SuGL81Ja8uvRPaSyVla98pSqj05H8cTgSfxM=,iv:RoiAWZ38BMYRjBQLtFfRjPl8eE4B0Zmq1eHgT5niG2Q=,tag:1EhkgTf18X0MiV1QLjeb/w==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:Qw1et1MpJbPhC6JNx899+1Rt,iv:sq4XIrA6eEvqBSMwTTTpO/iXORTvXlYpYglkiTDmih0=,tag:wnt+Bh/8AWuNMGUfDu/01g==,type:int]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:SWknBEL9jvnYtnY0r0/MXG2R,iv:8TTFR7ySTXu+HfPyE7FcwWRz9kSqgsfAaQUX4tNsjDU=,tag:pluCv4r3BguDoFLm/AMkIQ==,type:int]
    SECRET_UNIFI_POLLER_PASSWORD: ENC[AES256_GCM,data:yobEvK/CSwRxjKWY,iv:jw8TOb9mS7I2H2BSfho5Pfji/XjiTViv7Bk6JaAFIWI=,tag:ECzVOAeDEEzt2vsPx0xdpQ==,type:str]
    SECRET_S3_KEY: ENC[AES256_GCM,data:QfW43nxSZlmT9Ep6HAWv4JFwAEbDDSWnM29XNWxn0sw=,iv:z/PM3UH9mSb/1wU81sFXX1vCA511XE+LDYZF8F2v6uU=,tag:QrZlh7HMjehFoWgNjNoldw==,type:str]
    SECRET_ARMA_STEAM_USERNAME: ENC[AES256_GCM,data:3x/YypJ+a/n8cRCw,iv:mubZ1sjP3gWwwDjDVdHKSDH4CMzGu+AN28SNTadXzjU=,tag:q6LxJoIB+9jq5UzV9FdSoQ==,type:str]
    SECRET_ARMA_STEAM_PASSWORD: ENC[AES256_GCM,data:+SgqDx8h2fC8G/HtALNdBw==,iv:36LUGJF2BvfB5ViREXf+wkSbSiXTr9KHpX6IzObpPmQ=,tag:Tkq37UDYfN/h14iDMfabvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-14T21:08:35Z"
    mac: ENC[AES256_GCM,data:SDZPMn0AVj5Nqs3JxVIyfvQxGi7ZFFbCKKZDWEHDnUWuA6JbSiN9hxgkAzXHVJmobNHh22QppRI3YtSXIlPT5pxAzwqx2/74zuse0YPmry6ogBef9+bG2pyTpr7XeF4jLRyXVlSI2+vshpjNIxZSDuPwtI+0JV2SNtp/TWYNBEA=,iv:FgBobfSJeuTqLxBPogz9oZZRBpfk1Xfm5JhwL5nfvsE=,tag:Nqg+5DmRT98ikEzJwti1/A==,type:str]
    pgp:
        - created_at: "2021-07-14T21:08:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0HKexEIXzLaAQ/+JQj/TucRRlPcZw6i1oE7/jpL4yBtJf2JTyvRKxDkkHBt
            XWQ9szjw30ZY4S+/o28sVm7lW+xNRtTM2Ef1py25luuPdmmdi1qqTHSb/D7xSNFD
            7m9dzUoGqCCTYaLmHhj2gulqLVuEtkiplMLYaX7Qc0tjr3J6vdoZjo/OK2fG1tlm
            794nF0nWg109Ok5kvWM9NwFnXm8cqZYRJSY2o3Max/hozvK+vr8cGVRZfj40Ee1/
            A3LcmEjz4urYjsit9V+put4EdClH6RrOzYKmxUiTzQp0gYepnMXfoez+nVXFg3js
            fd6lRNoWqBpvW58iz+JIjYoKtOLQTaLK5QfxhJiXrRjhk3vlO/yaJDpGcj10AXbo
            +E/YKZXlKpRpZtS0rS9W5Z5VEQhSz9VG3r5dAxA8SqRETv3NZ4yn+TP/XsgbCHcZ
            kcGzqZnx6HHuBMNToLfh5bWURsNWlLqwoiU6kVAvfH5bKGs5QfC+dV19EFmO9JKo
            0CvKQcfTnR5zQS0RiYnugrVquVNmekaRiuLdEk7KtqRhsqWSk4y9HwbhpR4Honot
            jrq6KjbnxY4WYhyyiUfNdRD/NX92KRZNb509Fp9dXWQcRmZGKBwu4E3K1FkB4p03
            bHsHEPqQu+fv+eYzTNYlmrHju6Zjm8COpHf9BmQefrmIkrFSfNKZ4T4x0MIvbFDS
            XgHnllnkc6MHlSblzJldJLVHaHzLc0g8e68sXhko7KvBZbFpPCRFK+Ykw6lhD0Hf
            Au/lePdHwdw93wcwBmM00oEvC2DstKGSmv/x+esxyShxcJIA2Xvk/vbS7HwvV58=
            =Lhhk
            -----END PGP MESSAGE-----
          fp: D721131F87BC17CE0E6F99388A116B32DA75214B
        - created_at: "2021-07-14T21:08:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5YfjW70/vgQAQ/+KxAvwpbAKswnZUvaCAHMh9bJYHBjknS5IrcHqCp4SCtg
            SqMAXuW6+JSNfqk7n+gkiIJSO/i+PNW0TDNKQ12lmnUx6hmyfqe7V7t/Okr5grHi
            AG74f32rHzC5fO3HCISucuy8bl191Wb5TNtOpfRME6RXCv1yyoo4fkrrSkPq6h8j
            7rD+gSQVxFvFhi99oNmJ2zNzMkEzR77iu2x5nv9rq4ikC/ylTqs/WrzhVL8k+gkV
            huspP0aOySI7AWNNarhA0kJQtJdJit7wiMkLOtfKFsS/csDJ4C1JBGnFFMoTFZnu
            kbZKPBaYS5qiMoeZYH8XkhurjB6f8V5UgTuFJeqiJQupx8rIpZdgUrk8ECThH6YL
            ONsanVy2ZJcyMvq861FP3JdNaMuwmAjrClRm6LpweBevX33j0TIg5U0jZ1j6Q3vO
            /bbwG5CoUl3nZwnfvYLkLYy1ejNGuLkkywjUPbnoyynfPRKK1ASboaPRc1Vh2Xev
            cJCiyq3re7oGURSfWeh6rEvQ9TF7VtQcn9SSmEWjP3lQEzui2RvYLsiOMpq5wp6v
            knIuUXzo/VEbvsYNWZlQQl5eq7/V34JHuhM4xJjZS7TvvQZOjRcEB9JFbVB3hiSm
            p6PVGKhuKSU6X1c1w3XHn04l8nGcoHIomTGzq14qn3iAMM9egDR2+NYFrnTAaorS
            XgFNgOfVvggu3Fpb9IYLULyF8h9rWT9+3MWeEfj5EYRhppCtFXSA16qXRmG9MOIS
            seoEpDCWXwVMRyVNrxnBAoTW9eXWbGerPYSEBsO8oZ3FJ24UFDh+Pq+J9GfsN+4=
            =N0gh
            -----END PGP MESSAGE-----
          fp: 4C7DAC4D585EAEDD945ADD39D979197BBC17538B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
