---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: neon
  #
  SVC_BLOCKY_ADDR: "10.0.42.4"
  SVC_PLEX_ADDR: "10.0.42.3"
  SVC_NGINX_ADDR: "10.0.42.2"
  SVC_QBITTORRENT_ADDR: "10.0.42.5"
