apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/1AU3GKrDNw+QK+JebV+zw==,iv:f7LTpqyZqpt+nO+jpR1ETvd2lqUtyqZzWkVnm9W0rOo=,tag:n+f44XkJdxY88AchNkB2CA==,type:str]
    SECRET_DOMAIN_STUDIO: ENC[AES256_GCM,data:s/1j/7DezzaXcFJrA/4gQcAuXA==,iv:NsS5rSKk/sMp/nAu8k8E8A+MKZH08H0QzHX7U7W02o0=,tag:z2okTP1U+BaPnNVl/XkZ5A==,type:str]
    SECRET_DOMAIN_GAMES: ENC[AES256_GCM,data:kJhdA75TNNc1WlOL,iv:bESGKEzTeM5bqjNxHtWaLDU9SzZtQKH2l1nbKsf5Geo=,tag:bj1W7m1zsTi3lO+u+xS55Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6eMbFHRgEqk1VC/a1P52KZENC/W3,iv:N0x6BQa0iCPNm7zAYdYLDN2yLcMbttfrbVKM85ojMIY=,tag:0RMJLbn9y0/o9DbnzlOJ2w==,type:str]
    SECRET_AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:X8JWQSzmtN75vH1RykioEe6JSzFHSIHZoiJJgzkd1cWFgXWmPvNIiJbq8p0hWGGwgtPgHrH61nukVtm1p/jM/eqpVGs6,iv:8mAg7s0BC62iICa2PLu3CxL6Ts3ki6/fYIp7tnv8n+8=,tag:ZcFvW74TBEqamX922EGjZQ==,type:str]
    SECRET_GEOIP_KEY: ENC[AES256_GCM,data:eOaiJVfZsqFRTJa6rykkjg==,iv:CNOLqDXHnkJ6qBj0CPGwmmlqPbixQQuzQLI248ZuGNE=,tag:zrZ3I5AHMLQcPpx6iHRnrw==,type:str]
    SECRET_BITWARDEN_EMAIL_PASSWORD: ENC[AES256_GCM,data:uEpSjyX6d/InxrhxGxmWvDZNjP9CDvBlZF9e0GNhp5bXAD8gLuG+MQlAZFZhJCAAq2sF5mFdQLX4K/HJPyb5OEmYPov6,iv:oHKdMctqGAn2kbGjgbK0qny7rlyImrrdMz79cykqg0E=,tag:eIUhMou90yg5UEfRykTwmA==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:Xus0H3wKEeT2xibvMyHijLTBqjaz8VP+xw52tsjzraA=,iv:14dcL13ag8tVE+/czRPdMeb/PwRvcrpZt6eZXNNjFy8=,tag:a25W3QjBMbkUVXcURkv7jw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:rnS0oaPK3fr6X6trbI+d8xYVZwdVURKEmO7WzuxDiaWsiiFwunou3yJGtCvXrwhHnJI6p78fPzk5+9IYVTNQ4A==,iv:mrGNgR+uXIVkh5oz529ERtxtmIhsGT95ugrdNCXu07o=,tag:lKJlUl5Cb7Y0jI3DQs6PRQ==,type:str]
    SECRET_VALHEIM_SERVER_PASSWORD: ENC[AES256_GCM,data:7yBQrYdfvF+k,iv:9AiYM3Z7e8Ve2euqQzRL3/Mb4HAionpX0ELh3v5vltk=,tag:4DAN+Mr1/BQ1Xf9GqdZ8PA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:srfbHgR4INbrdqwUXbs8zbFgqUkSbh9vvgf0e3iiOy9rcwiH,iv:rd4LUsMmMFJIJnOcaBjdcz0Y62RzcdmtnBpj95h+Ptk=,tag:FPRnHXTs9vdL2WpxXkmnsg==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:dSD++nTczI8+T9L87jzFtGI++6e68CV3tmSfAnOLCKhRz89sn+nD+2OztQ8QiGA0Sew=,iv:gq/CQ8SQVWm5ipW1Vf5kqJdUykWHUIE4BQ/aOgTccas=,tag:E9ZZIkLqziemWa8xQr92Wg==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:RsWbHO5M/qT260dPc6vU/A==,iv:ITAknvbruHAPFk+qqD0brYJG3w7QbmlrK/I3WbsMTP4=,tag:h/18gReSE3fwG0kw1uWVPw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:4DqiLDG3TTD9YwZjkCfQEA==,iv:kN9WBal47Ad+JL3D4rBKNj+1ykmvW0ohH4UyvQLZsBs=,tag:ppzxzw591OtRi42XSW+LCg==,type:str]
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:cg1y3OEX1i6dPNodWcXgMOUFufsnvjb2u7SiUWqiWCqrWtuUcO5dh/6Be+pLg8nWg7nsgcF1zU2q2Uvtd6BSe333lRZu/SGo1x2NnkCA8ozr+QD1ehXcua8jovwoJoirvOMw44oSW7o9tKS+E06ozvKazGgx754t5CARJ8gH,iv:6Id4OZZS0h1Xyijz5vxupfBasO6jBemrT5VqGbZWIAc=,tag:qyG5URJR5G1pPJ5WWWrGbg==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:Yt5hJIu8j0xFyOTMFUfJNFXvrNW7FFvLf/uFkUk5WxVkKnIUYBm0CMnLF+xWXfGK1vm+4T+CYSkGWQU=,iv:lR1TjguABn6UacamnOUTixmePu/TxzFSK0AL/sGpCZg=,tag:8svVB+KMEaVjTfpEnIXfhQ==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:GnJaXd48kcMCV9IcJPVLUx3j,iv:fE//lljpewE0fuD9ObCSKrDoClt7xP44tRJ6ZCr3O1w=,tag:2zhqXwQfZwMjag0tQMCZrA==,type:int]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:S5GdNoDDhV9DLiU7haAP0oyz,iv:Yo6hSURVZW39EGQ8Qknq32uztqq0UcLj4ff8sz+gTPE=,tag:XixlBe6ftLz/nobZmcZIhA==,type:int]
    SECRET_UNIFI_POLLER_PASSWORD: ENC[AES256_GCM,data:FFjeecm60n1z5MDx,iv:LxUG8XcDcGC9zKjeJSHh/ZzqB8meYX8Z0WrWzvdg5HU=,tag:8T4hS7g3VhMlEPAZwNabtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-14T21:00:20Z"
    mac: ENC[AES256_GCM,data:3xe5CTpY/zPg0J2eBrsIDKnSsBLxL8BJr8jVLpELokCAHtsEGYNYj8i/I2GIlgPev9m9XcD3YrG9ntbUvx6oF6VF7hxQVbWSxHX9YtXnHCL0Dc7IPBPDOQDHVChp350SP390+7jKSqJuePjQLFcz9wkQmnciBB9eTBbZks3YdjI=,iv:vbAI3gqtyX1znSbSC8gshRBQCmTQExYwfHWtO36Z9o4=,tag:7dBbJm3ik+xZlTCfP/glig==,type:str]
    pgp:
        - created_at: "2021-07-14T21:00:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0HKexEIXzLaAQ//XtPWrdBpCw2rAiLc6d86s58l3y2uAhcj+KVhxtz9mjCg
            O8Lm5rQR151cuWvCCbeqVx3j8lfP9TKmgOMA9LoDgpeLHIV4RH+fOLLjxn44gAM6
            IblAMeACTdtmmtzKT7gYjzgCnSy4XvOe86/nIKntNWD7SuoBhT3RiwSF7cZHQTtC
            cF3sG1qpCEEYhVAzXEWgngQH1TMF7O+86DrfL3Th6Bbr9qN4xlvz0V7rYMbAy4MF
            P1FlBQmRhDZjNsSKwj1LI8UkaeGx7rxMg0OhE9pBdTBPfuq/pqhJQD78YEXatHYl
            vNOTLAlJ0W4XAKMEj6T9rcl+ABlw4FvkSBNXo7BNIw7jc0zXpX1wVwyUgReu2rlN
            e0AKIkRwWpsXKJl3dZVnQe7mNWGBEC5izFtXR1iHCE55kQZO2ZAUfiawVqzmI4dS
            hJS3fq8o21JuQUTFbXt1LdWELpRNehd4n1ywelEb6epTEr/sOIXaiLd2fuHWyegE
            63HaP/ItmMxRWELJPRkAqOGW7wtlHhjlDTHEaWhV7YbM2hHGgajrkOKPf/m3eJgV
            4ViUyzYDlv6BAScLTHOU0ePJTFhlU1kDfwE6yUYahUc6b9Tq7r7QroA8R+mOudrc
            46ChYQz7WRk9rxUxlaIoQ/M9hU2P5zqVMXFMoFnrqZ03/PLgYKuOPJmfY8UMVMjS
            XgFj633h5/8g0EKpuACmKFCqNFbnS/61sC5X95UeqyhRbZIFuFyy1mHtYdAvIS+8
            tnR1np4mXZ/8gEOcY7vklHnJGCgFUOcpSitihAjHnW4/szO9LEz01IV8usK6Xb0=
            =/3Nk
            -----END PGP MESSAGE-----
          fp: D721131F87BC17CE0E6F99388A116B32DA75214B
        - created_at: "2021-07-14T21:00:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5YfjW70/vgQARAAsikOLegJbYwMJBQhGlj2fXJElqtFHxvOMzDUa4v92LGP
            RhXD610ID2URO29m060zedufMvYjoO70Rviq06rWfEuukjrE+Qo6wv6teufpb9dS
            dZc/HaadSIxe5LVmhfM8sTvAtTIvv3fDfXULGenuy5V5urdqeGca8P0qdp4HWtWr
            Xdbuo3xgsprg5Il/8fVhryOQXLLubXhE1QpnRkLZeShJRUutlYqcK2o0BmMoDGSM
            Tjvn7qUmhxchGKYIoUTByligmOZv+Ka+vvlcgCp+4Sm0GfTeRoFjHoPKKUmkkcAZ
            tWtD5A9yTZvGC2WZOD17Z41UKRQ0hc4kHcxfS2rBY7ruuWrk6CKzBSTclvP7nMQ0
            WBOmHgED8E+PAHXAVzEsnTeGb5NoK8WBAkfazy1ZUbK/NWbvNfHey+mWJZ+XT1QZ
            R8dVU3sFmPqcugzlcpmWss3wIweeTbTSPpkOkQ12hORbC142GoOCgpEVKFRmIwjz
            y0cz4b4o/sq1SxI/V81p7pSpt/wV3ikz281N7WfXeXhBUVGOLN5DnLKYpsiQy3sn
            rH3iwO+YwcDJItyOKCyxH7w1lman42HKS78DCO0XO8L+nrxRoF75SY3o0hTc1KU1
            UEKUqYU0lzZezk4D97e10uLhrAIuKcSFsblYW7Y4Xj4uKBIF5zYLOhORVovVcnfS
            XgFL7qC3AHEV3qa7XvJng6hVgTHcS8FvaXfIftQCuVxEiH9lgKUMtRPEusLG4z5Y
            2IXg85jjCPPbzyXW5EZlm9Fy235XSUHkVgshVjL7NYLcxdvNPG0NNvwlaicQemM=
            =7K5a
            -----END PGP MESSAGE-----
          fp: 4C7DAC4D585EAEDD945ADD39D979197BBC17538B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
