---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: 192.168.1.147
  #
  SVC_BLOCKY_ADDR: 10.10.10.10
  SVC_PLEX_ADDR: 10.10.10.8
  SVC_NGINX_ADDR: 10.10.10.6
  SVC_QBITTORRENT_ADDR: "10.10.10.11"
