# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN_STUDIO: ENC[AES256_GCM,data:BxYGycsCqkMjI8KCXmLI/+gkHw==,iv:xHX12Zpk11mu6ZvY/5cQJfr6HRJX2r8LxP59jWNoOOQ=,tag:eYYi5pDsOPVToAXPHDwtaw==,type:str]
    SECRET_DOMAIN_GAMES: ENC[AES256_GCM,data:wZtYTLioKFY6Bs2q,iv:E8Vtdh8wR52ZALfWueFVNnFB8jVbzz36aoeVgOIZwjw=,tag:BfHbIXwl/dfFReVQ+lDSGQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ggc4Sq3MnSA=,iv:2yTGCzrosBUnYhbbCVhbEv01pYMA+wpSaEQwKCq3s2M=,tag:CtD1Qa5Q8HDRSpnkPqylVQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MH2znzz/w7sTos7DtUTBBDcDpGfS,iv:yMS81uL4MAUsvI6NxcNNBlfrB5wcbaPH0ii+JzGyh0o=,tag:bjtjb7uOAEMVEIGrBjN2Qg==,type:str]
    SECRET_EMAIL_USERNAME: ENC[AES256_GCM,data:F4Zi4PIbbQOzRH+zBYhgjQ6QK7mmXJ4MYmGe++KDOnQ=,iv:u/mWaHKWQGrWPjgBXTRYQR7ErEYOFfgkkV53tpWjbEw=,tag:bNkFTlA1n+35MIHcEWDBzg==,type:str]
    SECRET_EMAIL_PASSWORD: ENC[AES256_GCM,data:GwHavdhBH0dgCnx4/duYTxtpUlWuSihk92kNBIOQc9I=,iv:xnXfCF28HI06hirE+N0k/AUp5OdsY1Jzek2l+LScBOY=,tag:te440cAUrB355oj7mSW1ag==,type:str]
    SECRET_GEOIP_KEY: ENC[AES256_GCM,data:1e5Ccn/mpNyHOCBkDYtYNg==,iv:rEEq9QDB0A88g9qmiwFc5XW3IooRnAosV58Vz4O2APY=,tag:NLyfflCrn/gUUM8XNUgktg==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:yY+0NS5Xxo/zI8RssJxFGsxNfAE66UA6e0lXR+B+QRk=,iv:+cFJnFEbFSwpL/eBTAh8/3T65fzud86k+eSVTqSguJk=,tag:aeFHacKrzs2msxVeHYuNtw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:xEo+AEjCfoKpE1fz6G+1fb+POFQi/DOyiSh339IHsAbVGfK72CtLsXb9k1cVV1w3TvqML2GV0NPKtuo4gkhCUw==,iv:+K2fb62td3XvBPmUJrHbq0B2EXigoFajFOf4xKSD/Yw=,tag:kXvPW6A69nbPO9/9/zJioA==,type:str]
    SECRET_VALHEIM_SERVER_PASSWORD: ENC[AES256_GCM,data:+YYgu6woCpzG,iv:nk/Lvyx7mgz3XuXquEGHrTQafzQeZnigezIAd8/1+Mo=,tag:lEcUzc40k9mPh+o7hcL6sw==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:lAs0EUQFq/OrEx/mUHA3ksVgbvLtSxyp0J0DQXgybEBS9B5g,iv:cX+wvtHBO/ns81pITkdWk+vEOHsrwhxWpUd0b3w2IZQ=,tag:JAJvSTX/CYlA426hIgzi6w==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:ap7fRlYbpJzFm5uPbd2wI+VAuWYQwWuWImcKDhEunjO/VicgGU2B+NC+dnXZONt+yr0=,iv:jN1Jwc+/is3faP/6EwCt1ccvVGZ86v6AprqC7J7sgJU=,tag:KDEimVXXbFBKn6DVG6hSTg==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:a4GJnBCc+PUb6kJsVGxdBQ==,iv:A+3+xmIO5AqVUDmX9pDwGHvHclbkZpVh1seAW/GLass=,tag:0BmfrK7J1czR8WAky0AK1A==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:9aqn3X7MsFjysWIIxLeKpg==,iv:53XGB+xV+d7fSFNuejuZF9n1Lbp6Q6/d0/TDnXBp+nE=,tag:LoDdftN8TQCwmWi1O2riHQ==,type:str]
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:HkxyQOK68sYMpqHEbzdIhvHOWqONPAU5JxfIs/B8KIGZ7aV9IeUqJeQezAfnRDu0c0v7y1RL1K9XClAnfu5rjiglcx8wIHeyTh+0Pe3mFFoixsqKOA8lbdTNdcm2YUS3oow6mmgmQu6Wd9aCe1b+OqRLwsBqIZN+ZjpeKYSK,iv:q3gugMEnwlgDg0T4G01NfH9BpQdWoSuOeN35z7Txcoc=,tag:AmamuP1SgSvw8k9jeFupYA==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:OUN2PyjeV6xpRRSll4TSCcSTUKoH9HANHcLtu64MXPfbJXVRVqA3VtE8XGeADei2t2vNjlS76Oe2+M8=,iv:s9sIXr5+phkdHQQthEDmc6T3xjV20o1qViWYPH0VK4A=,tag:Ng8Oz50cjCS1578lpCnDcg==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:MzK8GC3VCRVIKZiywDuhL41o,iv:m18RaH754vVvSQOfLr+iu/yznOXfkXZ5Ucs9MCHHg3E=,tag:Pt4i1Ec0bphYtGJfxg/PGg==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:hTsAXLAnnkeBiRYptyL+/qls,iv:ZnX8YGYi/gsO5oK+x5YCzqxoFq0ueWeqj6XXVMIqToY=,tag:tgMJ2nlHD3jBHVcIDgQ4lw==,type:str]
    SECRET_UNIFI_POLLER_PASSWORD: ENC[AES256_GCM,data:L/xqLkUW5KxelGfvMhs8Mg==,iv:H413NvhxZfUPHBCZGBvjW8JYrxkOVgmrURJmTH5t0ts=,tag:Aokvw8FQg7DZaGvW26CNqg==,type:str]
    SECRET_S3_KEY: ENC[AES256_GCM,data:nEOFuTcJLqf5wa+W+skyAG8FQWlr8jy6xHJ43UYs2PA=,iv:13Vqq/ufNMsOnNbuCEm5N8STpOTcI+Q3Ikp2uOKgl6c=,tag:oyXYgqfPrzZg2dtU3nubcw==,type:str]
    SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:GARrH6QfrOJviwA1jbwmvyS4LXkoHaQK4+0kcJ+c0ak=,iv:7kTfSO3j9X49ytFg4eOR65jgJbXnkzPP9uLjGey/b8g=,tag:idglrN7OgvkdVZKvPJ1dWA==,type:str]
    SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:Ss5tMm6/WbWNzCyjkQ/wj1J375O5YsaTXsg42YdDtps85KtfJBt9qnbYS0x9ZAMyTXbOXTUlAkCGZ7fqhKwzF4SYfgh1dE1ghSxsnXWJMLNh6mXYhhITPO4scF9Nz0+/OC8PlsDBQd593MJl/xgZycSUK4R1ZM7H,iv:w5HQNLIDJ9EYGoKRIOGm+Vh2eCCMXmtWL4VpN0o6wck=,tag:hefMnqz7F9yA+i30D8CTgA==,type:str]
    SECRET_SHARRY_CLIENT_ID: ENC[AES256_GCM,data:+1V76k6qv8uHRC+0EwHM2qGEWSTcAXSgtf9Nq2DJopYK8e8jJtjkJA==,iv:OiAmEmMFwOVQfrIPglLl9Muo8stzzBVPDXP9mX+GnRw=,tag:6F2yTPah/xhy59xfqU8MoA==,type:str]
    SECRET_SHARRY_CLIENT_SECRET: ENC[AES256_GCM,data:IgGoRuOdSmt6EkZgYdUCviGYHbm34LkJUmm982lhfWSWQXEFjzk5i2sTL/Cv4TX6VEVW0V4Hl2uNaY4VJ4VSi8luSGA+BOZyFKxvTbjAY7Kp3uhGaqzmxHcR+uYTKtX5cR9DYGb0nW00RNLLACDB5Dt7DMkJnIRC7ct6Vun4KR0=,iv:qbYqDx36oYN5ogl/uocCPfEk+go4vzL99VYSETZCEAk=,tag:QzgB3VY4uG+2S1zlBF1L3Q==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:Fs/chfbJCr7eoktmFaRaYuE2Y1ldGezuC05Ah9KUXwuvur/i,iv:3BVx33RSUnUz4xZTcOG7ErWYJm+XBjLp3mye7BluuCU=,tag:WgELX603BO2We8liqNH7kw==,type:str]
    SECRET_GRAFANA_CLIENT_ID: ENC[AES256_GCM,data:CtaKsLbdyv72rVkjP3JaYt8heVyoc1jyxMjrGHNiojpazbzBzOZvFg==,iv:PNeu3KMr0q7DvyGMws2YRJ9cfAB0xg+QpzJf2JIOJro=,tag:Y+UsnTPDw8tBF6qh8EwBjA==,type:str]
    SECRET_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:ulpWAuk9/THl3XuKrsotsEe8wlPgzAmIGfzzhETB5G+vFqbCEfNPix/5dySVC5FK5QiEwpIIaMihhRp7wYOvu+7kK8TRKpH9Yr+4B5uKg/veTGTSkm7ZVkRrr+YLeyDR8fymj757W3fIUG3GRFBlNxnj6n5QBBYdInIVqjBGbKk=,iv:slGPvcy+WnjpRXuhOUzpPH7TKRzTZbG68Tbm+yoIYpY=,tag:fA7xtsbY+CcVjpFDjlyTFA==,type:str]
    SECRET_WHALE_USER: ENC[AES256_GCM,data:Uv0e0nb+NQ==,iv:Aadg/T2u8MDA8nnoXrw2LXgxljC5Mi4fGt4IdbPen4o=,tag:HDXvPytoT+sczADsTs7+zQ==,type:str]
    SECRET_WHALE_PASSWORD: ENC[AES256_GCM,data:kk8sEd5aBZgfiw==,iv:hHUkfoqOgXWhjUYkB23UTxE15IGjWJ5quDOzm96vLYk=,tag:oLDXzRpqy4g4Tkne9+gsRQ==,type:str]
    SECRET_PAPERLESS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:oHsm9RnYpwX1Yoo07tLQm7L4J8cfcZvdIih41FJY/Pw=,iv:c+VVOngs8fE+CX1z1npGONPTV/jX/J8ZIdoM/ndsBhQ=,tag:aw/WtnS2Omjof2xFO08muw==,type:str]
    SECRET_HEALTH_CHECKS_KEY: ENC[AES256_GCM,data:NH9N9YcGoku8v0P28kM0jVZeTiJpyHNXBLd2Jkb3+AM=,iv:DHW7K2LgYz5wCfClkvob7cA8A1TSOnHTqrx5VJH0YrM=,tag:xFrUvDL0hJx+4k8GxobA4Q==,type:str]
    SECRET_HEALTH_CHECKS_SUPER_EMAIL: ENC[AES256_GCM,data:9KKo0ptawBnBYgjvo9tHFtwMsOlP,iv:mcqkbVVzOxRCyVGjRb3SZkBblp6XLm7IzqQxjjbWE2o=,tag:Zbd7KFehVPgSxsrDQlEmIw==,type:str]
    SECRET_HEALTH_CHECKS_SUPER_PASSWORD: ENC[AES256_GCM,data:K5wLPptbDaF41fleB3s=,iv:cQS9xR4ZhpJLB3d4vgKeqlfWiC/gT3YLjXX4Ayb/U4k=,tag:am+oVEk+feKED86PIl/qsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbGNDa1BlRWlVNU5ENkpR
            STg4QUUzeFp2b1c1NUtJVFhlRURsMElWZkhrCndKYWM4cmo4em5Va3d0cU5wSlgr
            MG5GejNGcHZ1ODlZWDNPb1RIQmR5YzQKLS0tIHZuTXFkbTNhb3F2QjFzaXdIYVVz
            dzladFgzWk1xZmJqbWtNRmVsMFNkcm8KYmPi4m1dd1UTVjBxrg4R6WdoBRgjezTv
            hRIb6YVUCnz1FPVrIUhJhpvP9K4BaD3Gg50QerwkgQVAUfFnByP7SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:10:43Z"
    mac: ENC[AES256_GCM,data:vnRzqphp3F/o3JP9xJS14h4I0DQlTAKsGc7AMX9qBZGTUHm32kLS4jwNIrAWsKA+D3XvkN9aNutCCCANXwOAD9Us7aFqSXMUQHJ2WkEA4cavfmyWoNLrcwZZQnpokYqG/CK3pA2mhbI9yv6SDYG0dO2GeC5NVvmvG6YlssLqOKw=,iv:im5RNtz1I9sz7tET99/KyNo0rDijyX9GDHTvCd6cpEQ=,tag:0564BtlVepal0bMt+W6GCQ==,type:str]
    pgp:
        - created_at: "2021-11-29T16:05:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/+Kp5/wAmgaUrCW0uhcvqbRxUXs7FBCLniP1h78ZBgL1BJ
            ItTcg8rhNge/eImO3hqqvXtE5ZKyUaSmhJHsW147rP1Bh+iIQOIdO4XWU6dFoatt
            XSpZYb1+uyAg0jQx5uRmvwyYiNLhfBJiG5+RCwZMAKxiMb/8CMvIfxyu6ZA92Nr3
            6nZkauCVWcsTceUHjwos/8O9+2aDbp1DkuN4/CLElaJ1wLEqY6SzOZvkupzVaKOi
            6hDnDejvwXxSuGVTUA3wyeRt/btl32Q+lRMB//8E9VKRxeDxFtLxG3T6DDqcTaXj
            WW5fybWSJniaLHCp6EkcYHdDCTlXvd3AYxUwNH7CLtMRR2YOmyKpaKIhUk3lKFZM
            LKdOwCBTSgamcBubpWB2mxP1ytq6OtQsRy+VqHVtDebawch5COadBNCI3r9jvNfk
            ELO0ilvANjUHVk7ByJ8RG/pkgaohKux+u8B+GEFEvZOn2j+C3OBKJyZCTqU3HJGp
            +fK2Bm33qmw9HUAhh8RzsFr5SxPWQSwb9EfCqhCFtbpU6lwbqFirHoZ17UpuUHLd
            piSvXq63mlJ1jqFVOBmqODlcMducFCAMaH14pcfVWaSj+uyoYBabyRq7d4FGlCpA
            wScfyyCmITaHCVyDH3IqCzqhx73RD1LTFPYb2gTGGgUV2Fg0j3WDYgrZyKal+z/U
            aAEJAhD8ycuKU8krX+VWew8M3WzXLVaZMf1MDnomeyrZfwaKVeusGwmQBGokXP3b
            62g2UASj9HAH6Mh7XEKVJIHJmnXKpE6id7KPcqkfVoINhGfGZgpnNIwPEkIJQ7Xb
            kgcYNM8d4UFt
            =jjqR
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
