apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:d/3u/tdN99lWJSlIsgfwNQ==,iv:KBeb0TUeZ6aaF4cl5/uo/sgmQk1lQJtEoEK4vra8rD8=,tag:ZNB5/mCxrnrRAi1FdDWn0Q==,type:str]
    SECRET_DOMAIN_STUDIO: ENC[AES256_GCM,data:E4sx/s0E93M5qlkEtcEy/629JA==,iv:k4CFInteEjVj9S1bYTR2aLS1VlPyxn2HRiZ2sMDFGzo=,tag:yVJHbi6jVqtSyYSqM+ErpA==,type:str]
    SECRET_DOMAIN_GAMES: ENC[AES256_GCM,data:kIzdMm6ihT/AMxwo,iv:7yPQbwUwVEQSRUyQf2j32jOJ/oo6g9ypnhv2NG2Ewmw=,tag:xmUmrZR399AZX2QNVTwOSg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8FJmoN4tGqgujU/nBc23rCvu9jBY,iv:vfXEoWEJg657gEZYXquukfMBggazGWcFV0TIZNo6QVg=,tag:Ys7j+FoEPVXq4VKRHHzAWQ==,type:str]
    SECRET_AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:Rv74J2/KsUgmunbvgKTuTWvv7TnjNubKVjptytgmyA41EBkt6k5vNsOE5EQ24282DvW2jOZxNRYR2MB0PCRUrQefzNSN,iv:5FK2U0TkJN6Lna4jE6TMwA325lixsYn4GEjSj0Vwq9w=,tag:tIPHgv1FkhYHjC38/X9KyA==,type:str]
    SECRET_GEOIP_KEY: ENC[AES256_GCM,data:NPq2II7QFNDYSrvdM8xcIw==,iv:LY5tbDQJgTJcjIku5RIVO/OTB8T/qoyyC3W+ewAjB08=,tag:WiOCr62U0Hwow8NWqGrbHg==,type:str]
    SECRET_BITWARDEN_EMAIL_PASSWORD: ENC[AES256_GCM,data:G808fTVClQ288l9QqssxlpHQng5GfErLbvkj/LmjgVGzCZFRDSyYVHPVuljzP+B/J6mVgklGGu4JGuMATO+xg6Dg4uyk,iv:91Fn0toQx/sol4s+Veet2dHE/cNgtZmz341E8V9djX4=,tag:NvK7vj8KgaawBkvq2JlwSQ==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:0L8GQytGp4DlbXaNP3VVMoef3wKiJbwZN/QquJcoIIw=,iv:jxQyJCaAaV9MiUdxMcbWcHQnKSbrU8AC0YsxMXpz6SU=,tag:nwk+h2I5hy52nJ6FHm4rBw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:YpGG4fXg7eBJPOfTguEJE2vKEWkyN7iIVteTBGHgv586CxJNxRX//hiMKO5Ky8gH9Xg/sLEjOva5h+vT9NNr5A==,iv:RswNgEjb8ZhjWyeJbMy+srOdP/R9azRcn2085vUxlHM=,tag:eofWBsD7/HyGBYFmc+a/gg==,type:str]
    SECRET_VALHEIM_SERVER_PASSWORD: ENC[AES256_GCM,data:qoR86mIbxLpA,iv:flBqD1zbUOJozjE+qZmconeKqYP23DtuJ1HJiYWZsBo=,tag:ATOr5T98EKk2Qan36+Mnuw==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:D8nhPtz25h/VSGSN+esOAsjecWtZ90e0sdiLlRaYs7gBuZMr,iv:JruqkJZw3RUZPVTih0f43L7ZnDIFdHjCKNZg5bOVdjE=,tag:/rzFORc+w5Nmw7f4BzWtuA==,type:str]
    SECRET_AUTHENTIK_KEY: ENC[AES256_GCM,data:BO4hoTlHnH92KNWRSpcKF2y08A+BZ7EmEasMIfU74UUwtEYMnw3cTQEEBQverbP05AM=,iv:DbuUFlNGlUFEIuZtU1Ou0YJ2BiL+8hGT4Lnvro+1TdA=,tag:8+VlA6qbyzphlUTrOvWgvg==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:3R/RRz1OGL/aHShC6sGazQ==,iv:U711cMfyqymntEGGDhxULqrfYZkJx5b9Z561hxycVuU=,tag:zphchZNvd8CtUc0tzUOtBg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:nWxlH+g8Yz40eYJas//USw==,iv:TH0DacMOf6hGLcX04ZBWFuoMPYcdJ25qcBVhvHB3tIg=,tag:WmOE8qeC/jOBDzjaHsISiQ==,type:str]
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:rNmDgNOytUbyD6cNHq86whxX1ivOTA4guWQwZ8KBzLBg30HZ638tHgrdE2S7zdEhN6OE6wDU4xGuu62AzafS2g5RA1z7+Uqfqchyz1oTMc3a9+VYzeNkIM7D8nclvEb807bSQP1JFWJaoCJ6NaSM/j0tQN+RXTSTwFX4kXcK,iv:17T0uor+rci0eODbQd3777HusQr2y2Wjyq7g6aU/z88=,tag:70n545uVIVAnxXV6V7QKdw==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:TBBIpaixPHm4YWtxoLYG+Br6XW/trhKOFg8Z5hTqL3v+e+PA8IrMXDfUWmF1DNBh4St4Ab4yUCQ5GTk=,iv:8iwDhsmzcwhTRJbw5Uv+3V2alMuu56ngzpCD1ErpivM=,tag:cR7uWTUAOjdFfszfAK4bVQ==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:fPGxJUToNPPdxKtsWB9xR/2/,iv:mMpcljxeNMUvVO+2LzZUpQgjhrvo3DoInFzC3U+A9ho=,tag:JScCCJhhGUgpUjlMvt67VA==,type:int]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:fl572Rwiu+55vsc6+wkb/p2x,iv:wEkWIMo8JnCEl38jGJ0YbtInUrzsfMmNieRBPLUjbGU=,tag:vbMQtXQLogu0pwbz/8mHHg==,type:int]
    SECRET_UNIFI_POLLER_PASSWORD: ENC[AES256_GCM,data:YsmWf6n/estlx+g0,iv:Gs7ZyijzyE0MQSdfDsf+CNdiNDrtjnX3Xdj4TzPCfts=,tag:pISIH7oNljF3eU+0NTVxHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-14T20:18:07Z"
    mac: ENC[AES256_GCM,data:Q3VkUucskjJV34HfO70/uStFQDs4I645yNWBd8UGEKmKso4OvUdyBOpf81zgM2/WMYStds3AahK06EtkSD2HwpVxU/3Xc6ydOZLNaV0u6b3uycKixjuyea/kqWxtI0c49dWHrJmhqJWLKkveyKqUATfcE36vAbNem2NgaCB+hFc=,iv:7sBOkkyyCrzNftX/pJZWRjlqEjNX0DCqznm2YwAi+5Q=,tag:N0jTOpD6Z/Q/3EHnz5V6Zw==,type:str]
    pgp:
        - created_at: "2021-05-20T14:25:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0HKexEIXzLaAQ/+KM5d0OEdBq2Nw4sbyfh80TtxX35TQ8+mKZR9JRZS4uoI
            8K44rig+f93zv7N/WnkFMgnnSYtZTSrTa7PCSu3bcCQ33aFuZ4PNprh7FjsCuOGh
            tX6nxg+gKj2wn3aOF6VpC3LUSYxnXHnijj7aty7gdmGFgd5+3SJVLS4Q75DxkNkR
            jb1WQREt3Mcw1wqXR73wcaj7XzACrQwS/U5xufYFcEjbO34mTOT4p5L0iZC6ZeUk
            WKiF66bxrQOBL8ZyjH2euk48PHUaa8nByyx0cOumtQhktxMWfDxXvGfnXQa6Y/Cs
            h7srNn2FP9EL/8W9AFtICZx2MMvtMr/Uj5nwUfV/bPrdKvcfYH7+wUrv/EIwrYMa
            nzzbL+x+HS5BAfiWWG908jJhZxJf4HnkcB+yvLgJGDGf+sPRlpKcVbIGUGcM3lJC
            yIjvggCCBGQnI07e4Z75Y6s0yR7MAOk6OvgsN0f6kbnlSa4eNVp86stTkvcxvN+1
            ZhEPypq4eif91dru9T73rAPO+2WOLPnjyYRcY4fq6Ja6A75uYPOef7OQ+I+Aav/P
            JpPUSlGH29GW2HzVJ0MRFzk/nbF9aggP+RaXWhOJ+Z6zvCYN3es75BLxqeb7DQQa
            h20i+D+LJ9xWxtG2+LJAx9vyy0RySXuCIX0+coTfiltGjDJenpo8lyyuMim1qdHS
            XgFCyC49RuAPR+z2NM5dLp6q56yvp6t4mqpUjubsUx0X0rMllRvLb9zdR5rr1VFr
            mMx5Mm9bcL5P2Nsfalq4KpUmKZh7td8eUI5BisiQWOOema4V8x9gk1RmdTWT31o=
            =awsB
            -----END PGP MESSAGE-----
          fp: D721131F87BC17CE0E6F99388A116B32DA75214B
        - created_at: "2021-05-20T14:25:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5YfjW70/vgQAQ/+LInMjhPGl0quiIGGpWbmvP+2tgRF4KMp3IRSGqyqiPnh
            mFmqqxLWjvNiR/YGW7zQ6KdTX4MEiK6DInhgTbqnQMYEFvzcgWIO64CPbTV1ba5r
            IZwuDhYeXFjaZtBWsaKX9BFu7wqonv93oDZwJBzzSbh4KhEtgqaUT20Nh4dFF8QR
            Jx7QpO39WkqkFPHpnJJPABwlsmFMsKixhw/5n5M+qkHFNuJCK1A+T1vwdoW7lnyV
            I3Bak7din/36s7S4pucEC2D9Z2qxC4i8CrIy91EWn+xS7vciaKoCPgcpUdJT9Igr
            KSer6s2GtJTj/oMcL9+A1VYJ48DzfXVx0pnLKoT9/lzoSJcyA8OhZgdbxXylpQbX
            qenxmTHypobFb/Pmb/rgxCUDQ+gUwnvUjUk7gKY9WrPsx4oc9bAVo+ng7eFWdCqN
            jiXsnUFUdicACRriz1QV8Oojo9VckqB4IEFw5sWzY98HlOSYyQ4XLt3G2eL4B4td
            I1d9k9LrdiElAGTsTgNOkRRPzHGe2rWooCc4//LbGqqrS6bYfyXORvf3uxXvHHbe
            45F6H1YlgDvNknavKirdP2STtT2GB2WmoY4BX/7MWAJTkKPyaXvheztYYxymAy5W
            1OIrB7qOhhSAh1F1W+kGA3dQxPC+EAfkGWYUkapWLiCJ/hLZ2JgagHDlwDkOyd7S
            XgHAYEuKAoMWYqmhycc208vEPE5VdbcdnDv4NbVpGr5EhLRvEFpO8Wc/nkmVhMmU
            9VVeGxi04VM2TYu+16/DFpjqT42N5lsxGstECyaPCO6Bmvw92pSoXc9ANGNaxT4=
            =HLHI
            -----END PGP MESSAGE-----
          fp: 4C7DAC4D585EAEDD945ADD39D979197BBC17538B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
