# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: arr-apikeys
    namespace: media
type: Opaque
stringData:
    RADARR_APIKEY: ENC[AES256_GCM,data:ryJMveIJVghlhhqGeV9VPFoxExgZUI/DbrTQRXcyN2Y=,iv:iaN0cPNEvU3Av2Snj0s8pXzOVnDFCe5jyhojwgBjOMI=,tag:YGFqlh+wNPUTltdzl1dfzw==,type:str]
    RADARR_UHD_APIKEY: ENC[AES256_GCM,data:LPJdzDdOyvuvmhyxGuCGXa0EqfpNUUGbW/LujBjQniw=,iv:oxN0koAQWK8sbH59g/wfIjj1zTLGxrXVFFn6bOWw4DM=,tag:vsCOcacaGdgpKMtuxv0c1Q==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:YioktL3ZIwkiu4Lgs9fBjajB/hz+xRNLcsuqoBOyXN4=,iv:Cg9WqvewSw9HKEsvMWifsgxbFbul4pvd+b6yTeHSOKg=,tag:OQBZ9FEr9LYf0s5ANMQtlQ==,type:str]
    SONARR_UHD_APIKEY: ENC[AES256_GCM,data:TwGl1raOPIYrgg+QPVMLZuZJ57TMD00QfUz+Qam7kuw=,iv:+1RUDwFsgHz9fNxnvC/UM1ljn/lN0I/ym24cM4YLx38=,tag:opPkegIMabcQAnzAL44kFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUdISER0a2g3THVKV3Vu
            dlZwOHNpQi9XemNYdStMUzZLYW4rWFFaUkJzCnR0Q0tKVXMzZ1h2a3VCWTN5Z0s3
            RmVvU3RBcG9jT1N0VkwxMXk4U0tqMXMKLS0tIE9CV0twOFB1VDl0a1BZL2UvYkY5
            UndSbDNWUzg0bmVDOU1rQ2xtRXZXR3cK4lwaJ7dFt2Rjd3gK98KGQi21AXIcio7t
            Qf6PjJ85NCayWcTDJ4eQochXxjliJoQ7l2QoBgUubCe2SQ8OgP3xIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-15T16:52:28Z"
    mac: ENC[AES256_GCM,data:LfFOQ4d12tW7XuGs2FWKVquwbBaMKBdXij17hSkJC+IG6wb3R/9L6dYhwGDYzXzYjBNYegUvBTQl1xetiK0QBgWfR2M9ZWPf1QiT2B6GMxdfIl4Mq8eQAOQMQiCVGYMhgBuRTrwmWqjWtXFKmauYVVTH9R24SBXPcUgJHLGGxUQ=,iv:2g2wOsxu0d77cQzSbkljyZKaZk4M3jiipBhO2Qai0hg=,tag:78oAeilZ1yCYfW4xsOuDOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
