apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: external
spec:
  type: ExternalName
  externalName: 192.168.1.147
  ports:
    - port: 9080
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
