---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 15.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      pullPolicy: IfNotPresent
      tag: v3.0.6.1265
    strategy:
      type: Recreate
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
      #  existingClaim: sonarr-config
        storageClass: longhorn
      #  mountPath: /app/config
      tv:
        enabled: true
        type: custom
        mountPath: /tv
        readOnly: false
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /mnt/user/Media/content/tv
      downloads:
        enabled: true
        type: custom
        mountPath: /downloads
        readOnly: false
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /mnt/user/downloads/complete/radarr
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    exporter:
      enabled: true
      image:
        repository: ghcr.io/onedr0p/exportarr
        tag: v0.6.1
      env:
        port: 32123
        additionalMetrics: true
        unknownQueueItems: false
      podMonitor:
        interval: 3m
        scrapeTimeout: 1m
