kind: Secret
ansible_become_pass: ENC[AES256_GCM,data:GV8Nrn6agGHckQ==,iv:6sO//Wka5X7L59GVDfql/58ZiFES+qPK2z96H7m+/Sk=,tag:kE4INIepgwB9E2Hpe8qGew==,type:str]
SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:TV0xp4iXGzA=,iv:ILmMAcGDUOdTz1EX7uf6EjMLn9Pp0bbY4USm9Ug1cMU=,tag:t33eWIxMgLj624K1Xv+RuQ==,type:str]
SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:jiDqfST9TQ==,iv:4LzIz2uK6pkUsK5TDvS4yGxkL9G/KeYxyXgqQW/tX5o=,tag:/6TQpi7Fd7G/GNfC0CQQyA==,type:str]
SECRET_POSTGRESQL_USERNAME: ENC[AES256_GCM,data:mFTDQ5AaCNErZyjPYiXfXA==,iv:7yU+7+awU2emDDxsfZsCnXYSgI/eyItwW03lgmpsjMk=,tag:KXBJEqNDYS1cOJNXgQU8Yw==,type:str]
SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:eEVh5zzFwayxWg==,iv:BqgCpj+D6+FW95bHjZCFpCqOx7XAvOFVXI1NqVnJQUA=,tag:KH8iuRfwp9NxCWtws8+B8w==,type:str]
SECRET_PGADMIN_USERNAME: ENC[AES256_GCM,data:9ODQctT8xfN6dYtW9/Peig==,iv:a4HSJmb0BhyHKNKljRXudQ8jrD1LiOt+TrN4wQK1yyg=,tag:PCT/fGBsK+uHDwYLuQ2FNQ==,type:str]
SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:+xhUC5GEnyzgTg==,iv:WkI42KMrMohz5nffWbGiLXrVkeFVsHddG9Dt+sOJFg8=,tag:VxAiNHJ8SWZrzyGS5argNw==,type:str]
SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oXmgKoxowB3tA+PwoTWWJ0dPbqh7,iv:UxStXSKV+RhM2hS5UHhUZ8yT2fl6wwyS10eNwl6yq5o=,tag:WLicWfyTepsET4qbxFjAoQ==,type:str]
SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:EjaLmy8/qVcbvq//YgZHrzxXnIoqVFjL687gXsCwAl71s7rBsw==,iv:073ddcmqpo+UJgpV7kVom+Y90cyBjsKUI6ZZb68sZdY=,tag:Eh4LBDFNChgcfn6Fzknc8A==,type:str]
SECRET_MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:QFfqXFzKM3oiZg==,iv:BSHsH5T2YoYHN4Ujs1opU+Uc6S/LvRiSze/AEshOPMI=,tag:v5LlcTNWNNfrb4zpHWGW0Q==,type:str]
SECRET_MINIO_ROOT_USER: ENC[AES256_GCM,data:GdSE4FOw4g==,iv:AeqjjDONHbyNi2jT7vwAnPnyjsApk8vr9aRbU9xcvAU=,tag:UfzldXF+NO50rQvhC64KlQ==,type:str]
SECRET_TIMEMACHINE_PASSWORD: ENC[AES256_GCM,data:i6L4cb9WV4HPAw0uT0f8oviMDaJCS+lq6DWBSrP/l2Q=,iv:8+c8bccQkkeYEgkGzbi5ClfV+TOxedHCuN/GyD/wQno=,tag:47qeLBqMfnLfMN0ve5Yn0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSWVCYnZNU2o0QUR4c0dB
            YTM4STNhN2duK1prS2NmUlg1aytIWFdvb3lVClBHdkpiUDhZQUV6V1ZWcExTUFcw
            VFhUMCtvVlNkRXBObXB2Y05kMDZ5SDQKLS0tIDFrY0ZNUUljN3RFaDVQK24rVWQz
            WWw1VGVKWjRWdEJsMnJTTDU1aUJqS00KFPmfeX3J10uIEv9XoMuPlMRMXDhonaCA
            YX3K7cXUz/IrtkBxFef5ea5DaAGRCz4FPgY4Rc7hNz7mLZDl7xmzwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-11T16:10:29Z"
    mac: ENC[AES256_GCM,data:MWKbmpFK7Pu+8hScohn2257DchjF7hkB36C48wYw/GodkjnPVoXUbIwTWVQ7+HOuHMCBPFb3g09SmL0S6SdyNX2pXO57iaOuOFiM7vzR06J0bGt9jX5VfP7SP/AAAkZICxjNMpLmTEM0/8uwM9btmCbpnlymQKh00sFwIoyQ3H4=,iv:lQljTc1PfV51k9MjKgTYzTd2z07MZqKP/VGqzn74Oug=,tag:tr2JI6udCcmYAIm5Y1WkZA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
