---
#
# SECRET* vars are encrypted with sops
#

# -- Base Docker Directory
docker_base_dir: /opt/docker

# -- Base ZFS Dataset
zfs_zpool_base_dir: /cairo

# -- Minio Dataset Directory
kopia_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Kopia"

# -- Minio Dataset Directory
minio_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Minio"

# -- Nexus Dataset Directory
nexus_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Nexus"

# -- Postgresql Dataset Directory
postgresql_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Postgresql"

# -- Time Machine Dataset Directory
time_machine_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/TimeMachine"

# -- Traefik Dataset Directory
traefik_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Traefik"

# -- Vault Data Directory
vault_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Vault"

# -- Stash Dataset Directory
stash_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Stash"

# -- MariaDB Dataset Directory
mariadb_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Mariadb"

# -- Vector Data Directory
vector_data_dir: "{{ zfs_zpool_base_dir }}/Apps/Internal/Vector"

# -- Vector Aggregator Address
vector_aggregator_addr: "10.0.42.6"

# -- Vector Aggregator Port
vector_aggregator_port: "6000"
