# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-icb
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5OwhgEM2kj1OVEiBvDn0l/2Q+1T7,iv:NyWbuO9YiZu0ZwHR1yxJCb4nfCLIgTIfTUi9S0b0I+c=,tag:8powUPOkQIlCZ2qCqZiZDQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5qIyFcEp33FCwwUEr6boF929drndw1duIDbxOuD2MtJHiz527A==,iv:GC2xGb7uw1BbxlSVioZ2xeZiPt0t5rpekHp+W3VGvho=,tag:3wxo7H5xIiTJNctqqAb0RA==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:GhDmzZ2G1s+B2R24/Y8vuGDmh2UBZ2UpVGGcN1iypDo=,iv:MbDt0bS1xCQqmHU4CuWju4+eGjeS3mXwednazstu4gI=,tag:FCbfJIE2xqqQ1Ku3383JOQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4zuhrpd3x23ScOQg,iv:hGsB92lWeptjBYlA17XMDvcloqAldKrsuiZdfW56R6g=,tag:QV986BMFzQ/b88RLLCjNaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T15:26:10Z"
    mac: ENC[AES256_GCM,data:hNLaDeSuoBfSmjN71NBvTg442Y/CDM46m4/l7DdjNLfMEi4/Hvp7CJthxRniLLQk1E5VyMTqQcR+LZEHx+pyRL7XfXhti6yLH3PMwkCQab4sQxr81ZoljmJgag6D67K/pAeUBmUzwNolrwPNw5lj01rRvhpzXShXUdJnbQ/qf+4=,iv:QdqaeKyhrtDzU34juBchcfuRJWpWMQy/cbDGX9IGzI0=,tag:m1fP9UyFBf3Tk1rjK6Elcg==,type:str]
    pgp:
        - created_at: "2021-11-08T15:26:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ//fqVM5Fb5w1kBTADLRmTohaAHmyFoNZc2GIeKqTQ8wd/X
            yjXVLBMCvQ/S46v3gFMH2+k+2IPgr8TuNON58mBsY0PCuq+bfcgbcDiNTUZ7zh0r
            2IVc2/YgyBaKuS9mFdvLhhjSqUVuMNbmqKWdzBYAnoRhczrOPXd0SsvP35sxr+2Q
            xxCvrpLYDwmySdnTUZLFyKo4zIWONV8U4QE1RCa0fYp0y0kkc7FpARLygFRQ6h7z
            MMPAm13OSHEYrBdspoxJkBOyyf1MYhbPWkGgaIvvjaBlrkSI3HEOp0khPVH+lm7r
            A+bGr2koAFEx0BzoPl2QRMZNFMtEe/1D6utykLA8Q7LzpzQrYTNmyNdqqzKTDk9L
            AI+93FDdqQeUX5Hx9zvfM4BE52cPqSzPKTAUEu+3vsZms8NuJWrFAe6IFYOlnxw+
            wna9bNJ1xsVMsURjSzBElK7AHMTSBWffOLdV8TYUoVmmrCUxEiKQd4r0oBoe1za9
            LoeYgvEuuVXjP+qyb6ixj4c4rvtz8e6wyQRmmMxWEo48oLI0ryj5/EErIP8257lg
            fFjAqE8BNKnMr93KUYMZbp0i4fMePo9epcq+GQsPnAWcO3PmCKCb8JTl3LrzHdbA
            bGz7J0jAzaKU60tIKvzoWDZYBEkMJqk5h4vstsZbhUxlwFbGQ2/M3GLCRrhiZ/HU
            aAEJAhD0k40JaO17/ZOo/cmze54sGteDgGZopyhJ6n/Dgb3ZH/BTiH5zU/Zu+E5/
            +NS0slO4AUadioG3h1Wvbay80oFpRcKwK1AvJFSYr1+rGu0Q6L9+AMBnZq44uaMe
            IaGcrajI5uGu
            =k1RC
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-08T15:26:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAA5KN/FGJKOqSqNUku6jgXyPt+QjVwDo6+Q/C7xQUyFpl/
            JlX1Evnpo3l4vxfEOssXzU0cZixgvunsUnvefDxjh+goGHIJuGGCVCW8bP45S/HP
            3VwP6dqx390NFxFPkc5eWOpl96XGpdDfZLZ2MONzufE/2XJqpeQOfAg9KS61KwaH
            fMd9xCqdxYSMsKVufmnLy99cGa7n9q84lP1nE636T458+fgbSI+WlpbFn9bdMFMC
            uji10N5bv9teedaXT7Gf8ZJQzOmhsN29UYqXxf45HcBmX1GPMqBjTvU+5VkZQ8tq
            IIHs3AsL5Bz5LRINLMmJlKQgVgDOH8FYaBAU8VRSCUGvm2ya1kuF7GUXoKwODtyK
            KmboG06ZKEy9LeOS5+Bw/1dJFGRWm6GNvW4fgPmwnqgmIbPGGoeR6g6NU/iTotg7
            8EpIZa6A2rwCdh+RhY538vxXusrTROso6mlGyZiC9clGarii5/26STiQlZubdXur
            +Y0webtlCp1duIC8yl1pGBhB3UNx+ZV94KqgdEmLTzD+S5db1LU50synpS/WzDyU
            VcJgvfKZXCPQMdO9i/NZdHvpJKP3A+Y8i4HByEjor6HLrKSc/8BKVACTebsMEx3E
            QcsT4VRcKqrtER6vae0iwywdLxz7hKDUQFO47VdWbhReSSuvkueyNIXM2FSJIwjU
            aAEJAhBI3qJ6Pi7Dr50b/u5y9xZxl3V2AI0QrtmcR3E8XYDLfvd9cxXAgG56ma8z
            ut0lJYdx1n1YeJUMj3QSpBkb++0fGS+mbbhlgC+LJ8hoqeP7j+H4FGJ2AQqqcgnu
            WsY3DcomQ20C
            =a1Cv
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
