# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-icb
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uKUY5jIei/yPs2esYano9+0W9Sbb,iv:NyWbuO9YiZu0ZwHR1yxJCb4nfCLIgTIfTUi9S0b0I+c=,tag:bZ6jB1H2CTXnPMuQ33hFZg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+vPiHQgmsHrxUn2ZolHEIfxf5D2VXQ3TSNoHkRCmODiycHBn0g==,iv:GC2xGb7uw1BbxlSVioZ2xeZiPt0t5rpekHp+W3VGvho=,tag:Xcp0YIOmEfFsG/9szlmJ6g==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:n35M0SxqUnebmg+m8rLOEtBNNDrEXco+2Y1aOq30IDE=,iv:MbDt0bS1xCQqmHU4CuWju4+eGjeS3mXwednazstu4gI=,tag:5jyZNOAkBIL4vNVoYZo4Zw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+os+y+fQrQnApzxX,iv:hGsB92lWeptjBYlA17XMDvcloqAldKrsuiZdfW56R6g=,tag:o+hx7RHjZY4v7XqCIOCvOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeXE4TzhIYys2U1R5T0Z3
            b0lIWmVYRlJyRGJ5Sk5wV3I5QVpXREZCWURjCm5QQzczQkdHM20wMXNFb0txL0tU
            VXh1ejZEVld4UXVldWZjUnpxbVFCczAKLS0tIHU4U2h3YnllZmtXVHp6ZHFWa2Vq
            ZzVEQkpyK0VmWWZ3Z1N1ZmFBbFZJOFEKjkgGciBnBegEn790rzTIpNJVQwLPkP+o
            B6VKn0crIi2zPk132U/G7pXAeLKu3gISKiVu+bSCDyQ3Fw1atbho4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:12:20Z"
    mac: ENC[AES256_GCM,data:f6tFJ/rY0qTzmC2x02VBFM+tnnRo99d6WUb3+tjOZ6Lfptrpup/CS5+iZNlMr8OhGDnRw0t0K5w7a8vdtTLGgEo3nbG0AZ2h3jMaI3cJ+8SVwqEf1XeBw+Za9SMaSsjnDYl0GRyA9ea3Y9m8pd2bD67qcCoDp69WHlk6Achw4Ks=,iv:IaDQc4O6kpT6deRgb94rEzJ/TpLi38tXOCBfXUq0rAI=,tag:OP+SM+irs/GMC4YhJwNhMA==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/+OunswhE1QArmKOi7YT6o7jaIAGKSaYNZyQvnpn2mRn/U
            1w8jAxNBYEROsg42a9yHHQcnb0mAdikUoVoCKrlMYKcR8OEjaiD6ec2FN5Rx0rsy
            eP7+Tm2NGrKXEDLJvWAVDOf02jZy3m2AwrcGqcVf1JB5BdyD+Az2ZpjhCG7RYpE7
            0amkXNGVFANT1CVoihLNohpcwZuMgVvWOmZ8MIhJyfpfSkIo0AVlfEqFogTStC2b
            KMO3kVrXm+CSe9LFXHMeHJeblXijhr92UTnnJwTy+LB+0J0czHcddAnRIb1hvhoy
            fQglEjWwDSQmVj+UBd45kToFQVtJCHOCExipaInd6d6bhQ+PziasLINqBA+FxBhc
            A4fzEThCFQmQxUpLgR6Lhh+TFQFPXTOjnGoHIyttORlTPA68OCIg/hzX28xSBIrc
            SpJdL6pNAL1K87cPMKOzS2GvNMDn2oDGLCxBz66IVwhV+g0RJijYHy8kNcjnZCMc
            QOtgQe/2IRqsJrJhzOTEpVwnZmwOsB0WPJJeJurVvnQUDlSq/RK/5j6rEOz32SDA
            mWTTLLoD5qvQC5D6ftbP3wd6XMU8GBtIZ6jaqoVYKHNkcfrI/D1uKiomTGXAdxzG
            czq19zIxI86qM/gnWMfRluQBIqbcbMqGRWGZXcN3dzoBAGdblzCyHTedkVEzCL3U
            aAEJAhDpdlMdu4nbJBApXhnuoEgqnpHijhD/yUGMaHAsdB484iStNd3OlQSxnX97
            laeyYIwm8N0O1h+uZg323hHT0PrDGNkGzdafBwgBIQuejPE5Ds7MlNKP67FdQhOH
            p8f+ynCvlECX
            =RdJW
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
