# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-icb
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5OwhgEM2kj1OVEiBvDn0l/2Q+1T7,iv:NyWbuO9YiZu0ZwHR1yxJCb4nfCLIgTIfTUi9S0b0I+c=,tag:8powUPOkQIlCZ2qCqZiZDQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5qIyFcEp33FCwwUEr6boF929drndw1duIDbxOuD2MtJHiz527A==,iv:GC2xGb7uw1BbxlSVioZ2xeZiPt0t5rpekHp+W3VGvho=,tag:3wxo7H5xIiTJNctqqAb0RA==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:GhDmzZ2G1s+B2R24/Y8vuGDmh2UBZ2UpVGGcN1iypDo=,iv:MbDt0bS1xCQqmHU4CuWju4+eGjeS3mXwednazstu4gI=,tag:FCbfJIE2xqqQ1Ku3383JOQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4zuhrpd3x23ScOQg,iv:hGsB92lWeptjBYlA17XMDvcloqAldKrsuiZdfW56R6g=,tag:QV986BMFzQ/b88RLLCjNaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZlFOS3ZBSmp2cTJONnBV
            YnlQalRVVlZQOG43OEs4YVBUc3AxV0FVbzNjCmpEV3cvUUE3NDU3THEwbGJZU1U1
            Rmt2T0NRV1Zadm5OM1kxc0xiSGVQMXcKLS0tIG1aRmRuQ0xJazF5bStzdUx0eW5X
            elNPUGdNaVJRWUdRNkVLc2k0Z3V6d3MKD2Py6hBIowA+s17t/agr8JfqAZiAkHfk
            eG9AxzdRkqUb0IUAn5fqlrdLXGMyOh5YphAbzHr/107oFLWy+e8myA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-08T15:26:10Z"
    mac: ENC[AES256_GCM,data:hNLaDeSuoBfSmjN71NBvTg442Y/CDM46m4/l7DdjNLfMEi4/Hvp7CJthxRniLLQk1E5VyMTqQcR+LZEHx+pyRL7XfXhti6yLH3PMwkCQab4sQxr81ZoljmJgag6D67K/pAeUBmUzwNolrwPNw5lj01rRvhpzXShXUdJnbQ/qf+4=,iv:QdqaeKyhrtDzU34juBchcfuRJWpWMQy/cbDGX9IGzI0=,tag:m1fP9UyFBf3Tk1rjK6Elcg==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ/+ILnzmVs+vNt5jD1wSK51bUDI1KFJMjsfrjfTwGa/Ulfk
            ebT5qYe/y/WtErm7aqgqgcZov+/96xKYgFZHDxJ1BhUgnBsiIYeuywGxoi1SMwxs
            EfYgYW676dIeh+I9xqAb84nB5uvUHIcvb/AaLByeNFnFG/VrJNW2WWguIuiyahEb
            BXlETRFWiuQCuqFPuQaHBQYeozHBdUMjwO7a0N+d8/9k81+YkvkclSAnMTon1pL3
            nWW6Q9NSo+//5noypVlQm6+oearY3/bOX6FrYQ+uZLTRuZARd5Qe2dbe8yjmG0JA
            6kueieDOIfDHRVBGj1kWtigdhlCcoY5Q9bMvbcUGp9v8y+Lej0Od6F8Wi6fdTMBX
            TaclFXMD8B69FsIAaF5NSohZ7QaPrdtTnfJDep5JDKCS1YsoCcX9MMzBmOFwqzsE
            4Bfx/aN7xMOHKTmZymQvIPqC/fgCUTKUFcAWl9VBd7txoQruSwVIvby/pRcns4ZY
            Ls/1mY3beGGWTJPZGwwbxorJxXPL+amAnLEDRZwSgk1vFW+tKjtS4vYn+iiJNEz/
            wudtIF0N2pw4vWEk096RvieSO2WvvPOQY02AHuxegkW22UhAsdoRA6sGRje3uTo+
            qCyeci8vUMz1/ejpe8JDxI39fxPhoe4KSo2hWRJV/HBrdKOSJ6IoBk9xQJBByA7U
            aAEJAhBh/K3AjvgwuRLSehffRud1enNs3rXByR9HzRoB9VaoYxZpHJf3IkHEWA1q
            4cP7FxIsXk6b0g8Sz1w3fblk9bqcdLU9+tPJDeKC7EjjidRTyoBLXtDfgslV8FLy
            btwPjEmfW2bg
            =JAlA
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-29T16:02:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAxIKJKL81TiLb0V6/hVktRz5SSsaumlSEjq+9R+NwNC8V
            NgIM3m7F8nDsYemYF6IHDFZMwltIxANiX6XZiLOiOYn9n9tABiYefaZSu7itazmh
            DRhDKfjs2C44n9BM4CZBz+389ZD14Gu/ESrUssJBrFrIx1mhI83E/nOBmhKEh9XJ
            XXEANASFXxibUuFfG5h0Xrkw2AH/7isFtqixM6nr7U+LONyEI8aECwFwNJzhSM0X
            2/rtWah8i9us9X1HfyIFsClXg+tF/BWzwCBxT5okUJFyU+78cUtqJyWJZnbxKF5g
            zwDjDMAe9ZF1+NWy3XAZIjWKlasi4VnPwmnhJ33XmDqEbPJtGrvmonLP0Tszg8PY
            P4AVf2DYpALGer5tN58pGo3QyHgwjUhcNWHxZdVqRnlXOAy6xJTvhL56jW+OrVlR
            D85SxCXAEGItd8d3Yi36i4YomutJiN1XA0l/UsW6kJjyBxwPFVuVaz+FH663G9uq
            k6MpDmi3QlebUFXCHh9oxxuQOEmeXDthHCoQ2hUgrPbtRiUMWt9dzAljSkocnXTg
            pNsxH6akU+fLcj+5Fbrti/07R6cDHery/kp9LPLlH/WtnesEVYbWKbRoZdcgTkXJ
            ls2GDt7bPVlve7bVCKT1PS9UM+f2ny3XzVIXIexTMbJsyMkIH8XUDr4N+VKSxULU
            aAEJAhAQAJ+AA5vTIgsOuWd1g0RLr9YpMhjDncLSb8vXmbqHH/VQ82VZjLoo+qtr
            WwpFsZeuD2wd1SxH6wGLmySgmcWHHMc3HatRe+NyOWW5L/DEZkq4jzQSMf5MKeh9
            sd+y9tszfEun
            =odqN
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
