---
- hosts: idrac
  connection: local
  name: Update Firmware Inventory
  gather_facts: false

  collections:
    - dellemc.openmanage

  tasks:
    - name: Update firmware from repository on a HTTP/HTTP/FTP repository
      idrac_firmware:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password}}"
        share_name: "https://downloads.dell.com"
        reboot: true
        job_wait: true
        apply_update: true

    - name: Firmware compliance report using HTTPS repository.
      idrac_firmare:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        share_name: "https://downloads.dell.com"
        reboot: false
        job_wait: true
        apply_update: false
