# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick
    namespace: falco-system
type: Opaque
stringData:
    DISCORD_WEBHOOKURL: ENC[AES256_GCM,data:pRamc24jzZ1LRPD1FnGguwYNeg+l/auH142sriCS0Ax96ZrQzWmFwV62+iM2+y8xv5qD0ayFunT2kGltAWgelkKUW4uPV4Km3JpmDdUYTKfsOMwJhbRx6hJMcEwJD91sGXlFQKhXeI3PHAG2FYsDM6jHnHAMfLJ5nnN/3jeS,iv:n58hBj88tVZJNrkoOGRYJO7/KVlE1yO4K98KS4dD7nY=,tag:JzIjWQkMbfWDH7lmQTTq8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ3BrNE1MQ2lWSXhCTlZo
            T3dGMEJISlRsNFcydklDelFGeWkrL1NVT0JVCm9kaUJFUG5lMnloRnRsZHRGSXI5
            Mm9WU2pLYkk4SnNQNlErRXZTMXU3TmMKLS0tIEg5d0tGQnozVG84TmcxSlRjNkJF
            RHBXYkd5UktmZi9hVEJkL3liMUV6N0kKEpG1JOT0HjMKs1tHTxx4rY3MhKoSAs79
            1sc2EI/rgmZWwjifUdBPSG+t2YNopsA7FjvUBuJsHunDIFiHMPcCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-10T15:41:44Z"
    mac: ENC[AES256_GCM,data:oOs0UgPyChQBIRplfnoVUcQikz+bW/yr//6iuRi0RpKDkESWCxa5i6CVpxmiTZjkDJqJ2bEMCga2liRjBEuF3SEIMS0ojNly8k9IcsIj1wr1SSOB+Oe78yzQO+4PiQ6hHrAgVMFqdRObfYkvfXK5EpZvi0+kjKG2uldILL7Uov8=,iv:kLyyoEKt5WcnC+QMdm2duu2kWBlcIEVt4J0Op0ZAt9M=,tag:9kg/eQeTdY6J/OuYWJWRag==,type:str]
    pgp:
        - created_at: "2021-11-29T15:58:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ/9GBjR/YosY+xnjj1ZVN0VUpBQFDuZXVadL0U/I8J2WEnv
            mXtbQyOz8fGsAICsuIsH6sRJBOhLb8HSFExwq+LEducgCKnTmrzhohxo/o1OAuXr
            zv7udSSuRNEACinI3QWLIvZ44Qu7WVpYsCmnfK85IU9FkEbZC6uIokjv8ei3Mzxx
            G+sAC43H9k4u7iDwcjyEzEel/eY6iU21ECg/p3G4xZbywLhCPSPvsP6y0DsphO8B
            yxddw/NQpOqW7BXiJgYqGHgwjYHwn6USkAtN10tTufvgQTECw9wFpQ+/3kWsfH0S
            DGWyjZsT7I5798t6KAqwYiwZ96n98s68QjIXGtZ7PYvayjUklIyexx7G+mhZ8q+i
            OiKwUStOglrX1s2K7B8txDbs4Gf62naRNekh17BFXl+OmcinwHq7Zc/ud/fZxS+6
            tqUdvDUo4vX8uPTS+mdc0U+6zRWnzH5SYHsS7VkiwfS6CpTewBq8Gv8KGgrtOLH6
            k4VbYdG7ampTRhSDWB/0kRRcZOS8tY/+e3f9YLad7P2W0GySlLfSHcRsgZYHsDEJ
            DH2FCA2oE9zPx+AYl+YkoPyAdCCBc36K6uJUi6w803kwqvKySS6apZbbB3JfQCXd
            T8DqavLRfXMtTUCAFJ9nv5MvW7wOUa/bcmOHpPo+IqGcnz2Dsnys5l5vWUCI0+fU
            aAEJAhBWN7SqusTEgx/IsdiL2/1OF468Z0EcnAvC7NjRKnTY+WQawbd3IURR65hK
            5UZmMSkBkfFsJLXoVfUiUCj7Y6ThvTXOI+hSGvFQ0XFtLr0WeFcx2p3OPSRYayQT
            Rjaxfdj1WAUo
            =KaEc
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-29T15:58:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAA1bz6xZhmgUdAGh5y01sSB2A8D5VqE1PIj4UEpUzpotyF
            5haH6rXEZGZ2vJn7sONhv8N0OIRiozcwKQXkexvaGlt11PVkDaBmP8GSZkpiGwPw
            VM+JNrtaubsV7o7hcZ4LwMawrmKPyiUAW2NCTRUbG1AXTbfmBEjZPC5V7Vqi888u
            wfYNDbFqsilKJQfMEp5FTNMGx+6pKBOZayEM7cVrl7UAmpumWmYFUYHxYsI7/WAy
            GfqXQ0+/K8n404okiSgsmQnw8GjKDU4DzXIYrkZlSYv2pGjoq20QZCxl/ZBrxgUb
            6NxZnueSA/Radu2Ap9N0sh9dspaZZSBEymKIIz4TdXV6usllJTMi7nmCbD/vUB78
            KOwDTiqfd8z62bVe0KtMm7fRIa/AIi7YOCO6WnFB5LoNua/pmN85CB6Kw+7xq+IC
            hRY7MUVOHFbwmML2K4SzPzJO8gqUlnD5MfCCCdoWYc3vjh4XlFpphuYqlwzI+iSl
            2QnwBC7XLoxNbfVGHWaY8AuLrWkAxgiTRcLXgqwPGmFqQaivjhitDnvKC2WVQLfD
            YY1YbxWsirfi++3ljjGDQvMcrOnkWnc/i5gYi3NXGLxOeAp5n3F8JahquMs6DpDP
            W+C4cy2gm/6HQGVme5XBXry5KTcaOr/bdzPyZvusLVZQbQym0+N3uT45o8Fo+sfU
            aAEJAhBe6s259OeYLejtLwSpy1YR7wO3mZaAEptNP+K8qR8Ff7KiQ5O9tnHqdRkW
            UoUs06GmqGm/K7950huediQPCVHBh/KeSgsgTuBYXJgsOr4HRdUkEghvumpXu3E4
            j5KDjWFPrFhL
            =FSX3
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
