# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick
    namespace: falco-system
type: Opaque
stringData:
    DISCORD_WEBHOOKURL: ENC[AES256_GCM,data:4EqNDaCbqWC/KgWltCqdxVm2ZO4TDT5EZuFVF0FsNOH1psU3PuI2rTaq2CjvaCTyw5Yhp9U2KG2vhAVmO6vbgXfEH4bAy17qRf3o5cprOh41qwwU3t27EutZu1SuH9xC3x8wQ08g25hxRs0blfw+2cQYqMIQ6RRm,iv:1+O2305a+wCFKFFOjMsL1kFP9QdOTNlOsi2grcQUhzo=,tag:rYKjkgfTqf5AK6BEolcF1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-10T04:13:35Z"
    mac: ENC[AES256_GCM,data:/H9vR85vZB59a9paBTUjCSqe45u1ROcOHlbf3dDNZXAzOdrqYhzElhhhm/GSfc9SFYC0v76IV5O0j1o8wvY2gY6wUbysJ3zqIvjIjzx0P7dPK208jeccYRkYgXyxN/mdQyrNmBOCaGFpJ/j29CzVrYBymIJwJp14jYmbwcWrLbU=,iv:8//p35B6TP72rGM4/7svSA1yIsEn2pjUvD6HpLRWIgA=,tag:9m6UaEk2NA2S4LGG9C3a5A==,type:str]
    pgp:
        - created_at: "2021-11-10T04:13:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ//aFqtEGP9bZ9v06t2H72rZcEU+AAIWM82USrKDYrQVwja
            WbSstv9AR0PZWHR1f8yBrOETyjmdJohCzSB4252vtBnaKUizq/dw5AN2/MVZOk1t
            sOwwGWtuPSp5ls+vwwRDSwPPU4fiMymIS++Cm6CUc1eoY++FFX988oY75BIl9L3j
            TlbWcgiBdm3PRG9NyGwevzKtE3P8HyH5IOLnKzXpomnMg74RXPB3H5yHg5L8onh6
            UHjwQZqoyOKEgVCkLsrfO1ZQUaD8nHCznR3N40zQHzIPcrDsdD54sYl/62vyKh3b
            rQn/q8Q9+b7dgfKEha8wn2u36K1Rdc0RSMgVCb3tITfFzGY1VdBS27zq2RVdT+cs
            TFPOx6r+Zx/n1XUlpKdXVCsWIiIB+cOKMS/nBs3+KRAwBNqyrDVPO/rCP5m2cmfp
            1nnrpsAtaw01zFaYlu1WPduZS8L0HhazhUAi/PaCcUVElzwbUOI/fut2vbATJiDG
            1rxZtR4S85BLyt4oVOMWI5QVffKg/owN8AYYFgr7g1p70TAAvXWOApCaU9oMH8Fh
            bxXv/4d3XXww7GL++N/hFzV4QmV2G81XBbvmHNckXxT9GCgGnYkpTevmlg/CFZQK
            1AyREVfNDIqSnYhILLIB/dYKxu3F2iwzp3OUWTaxCeH7JRP644Ekvjt2yz+fStfU
            aAEJAhB3oDve3724FGhavGlaD56P1FZW32jXouGY+XYxkdeudSTEeWsljxCcuWXP
            w2rH7TjurnNlk54iT7l2dfz+RTHPRl8EPoDX8i5zUVOZ4S0D8jiVNYWSdvljKYFN
            ojUd175Bjv2O
            =gwzQ
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-10T04:13:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ/+K9kT7Gnuwq7FxdV+MT/S6GOzHRGU6PU+lukVYa+HcA2f
            /NiHxL/LscqgIABaUHVIQHKBjtzQWqPClC6rJrUbOOeW53f0UFGYhyhXBbIZ5FTc
            sN+qArkyDfpuNhPFPLF7boyHqBDZIEqAq4zo4v+XjQfdSQt0jNU22FE08NgWP3T2
            qXPrcsm1jqFKFe4avk85X7lp+Xf/fEeg2/ebAx4bw4m7kJSj21fAPZWJyE2d+3WJ
            CSlgYdCpQfYIpD03m/GBtFUxJElrfNDKUnqIXVMYYc1G9xgaNj1umPTfYgHEUyV7
            bBfR+Chn+T0J9sfnCfKX9Vao7tE9BmZxRzN0cHMTLmqIVRbtc2XQRw5Pn4vZC78W
            2BrsWcsFBecIqwyXPEzdGikWHcO5g3vRsRm7z4teUVOvjQ4rk0vfsZtEkf5gn9fM
            HAvtPZHuOqnVKCUmCsXyE3BxapsxmcNnPdzE0LrG85w6d59SOe6L7PkebSDNDkDR
            /JJ1lHxX4EXkaZiPAr96rA8D2VpFaBE0hMGgccr9mxsjgeZmtygttYZWB0M4xt+7
            Nbbom9thZgc/m4LFaTtvBLY159KvnCFzPBvCm/hF6xBRhRt5HZeRzgL6o3gAN+ay
            spNWxJ7uiPnLtpilyt+JMeNJGhAAJpJyXFbVoRtNgMUUD94lP0bq8ApTebAzQJnU
            aAEJAhDcY7nFmCu4uA8K2IsJWucJMmx2cPDRpN6CAe0HrZrIBX/7KPlXUEVoqPJg
            1kKBc3jwzZKqUG8gk1eQHkoFpSJi8A7vHtEGuGAHwuV0VPmdGCkvnXBdvp3IyVEW
            2dQs00fmTgOv
            =8TPh
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
