---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "bucket-outline"
    external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
    external-dns/is-public: "true"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
  name: s3-console
  namespace: external
spec:
  rules:
    - host: console.s3.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: s3-console
                port:
                  number: 9769
  tls:
    - hosts:
        - console.s3.${SECRET_DOMAIN}
      secretName: s3-console-external-cert
