apiVersion: v1
kind: Service
metadata:
  name: gossa
  namespace: external
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  type: ExternalName
  externalName: "${NAS_ADDR}"
  ports:
    - port: 8005
