# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-studio
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5ceap0qoNL1UJMgMqaF1DLIKvknT,iv:JwP0S0/FdeV5ivWj2qKGnTGXGEhGki9Dcc8YPdlb2xo=,tag:rN6Mp09AVeqgrvrNvsC/Sg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:GwgbEOVHO2WyeBjCmhNNDGlcXUQTuarIyYzXWK+zJ0++ZXU6VA==,iv:nRG3f0cuoh0VmzTbl0a3bEEUqZgCb61RYSFkbqhLx1w=,tag:u/meIxYvZB7gGSxdkySC9w==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:MLkF7UfBHylH0ThmNdREx8pEqNP73YnuX8+4oc+okKY=,iv:7a1ACNiXVJX4ODE76Uc+2sHtTAWd/Lg7ygYDZhvhbKE=,tag:395OTa0fPQf7tbYzCUllnw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:VMiN9uG9TruqzTADIdks8U2LyuJAcAvE,iv:o0S4RU/TDNkGHEJ7y6o2rGnYVrmafzyrBRxAwNDKQ+A=,tag:2WrzKmyl6VkBSmmeshSTEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUl2M1NwRUtyeDJuYVl6
            T1k2akthWEFmU0JxbHdMbjh3L2hnU1U0SmpZCm0rWHczNlJHWUlaNThFSU5FVDZB
            c2kyK2VZc3ZYenVzVFlXcFZQemZsR1UKLS0tIHlxZ0E0TFZEbEt4aitKMDJsV2Y1
            SGJoS0U1cmxxSkJ2M2NpUlJHRXVnWDAKZ6Jvl8+RKZIFAnDcgDljxoY1snkHMoOQ
            efkHMrWyThrKZCKR3SAYEBMVd/xIsUe7RWRR1MXM00XZhdSlbCqcbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-19T18:58:00Z"
    mac: ENC[AES256_GCM,data:0yGsa2Hic+njWEx04qm+ZEl6+6sFb2uR1602pCrH2grIy+N4CwuvMUSCZpMB18NZl6NQu4ERpV3SyOY1Z5uEcEzkfjDET6SJY23lrGzVuX/TtiG8WTVQGHnQddvgirH0SjkvAynvVofKvq6NpTdP1db0rIoCazeURvmXxRknqbU=,iv:dsGFtfSz/x9VWhTSfxk41eJr+HltM+wqgLxQZemnIFk=,tag:ZeYsp/0XGYmM1lIT3aZRUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
