# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-studio
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:o9dB73omb/Q/VZfD3Jq8fWkmwvdC,iv:JwP0S0/FdeV5ivWj2qKGnTGXGEhGki9Dcc8YPdlb2xo=,tag:6U57Ea4MacP4upt1JpcDhg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:C2zI8X4ecSViJMieXlxoaB0Qt6BzSpZkQ7xGseV9F+oFsRVmUA==,iv:nRG3f0cuoh0VmzTbl0a3bEEUqZgCb61RYSFkbqhLx1w=,tag:YVe0YKRLM9W4kirgySC98A==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:7uzfZkO8Z8nNf8dRwjGuEo6mftw70iqijYnzYQwpjB8=,iv:7a1ACNiXVJX4ODE76Uc+2sHtTAWd/Lg7ygYDZhvhbKE=,tag:yTPufNIQC6snyjXxUvlTHw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:rNcTbWlDpTe/E7N5mU0SI/q2Ow==,iv:k8HdUuQ6iKVfXQhIGhE9Vg7NvrD5ro7CObwPq9Uv/vg=,tag:V1hY2Urz5Qu06CX4rw3NzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbWt4K1lKUG1acmxBZFpC
            bnJ2aGQ5S2RiakYrdkQ4WGJjREJmR2ozUjJFCldaSHJUa2hSN0xiTjJnZklZd1NZ
            TE9zTG9PaE5hMThVdWJqRzd5SWtFYjQKLS0tIFVJbTlTSm5oZXlWSlRIU3lpQjNq
            ZzBJeWkzN0tSaVZSYlN2Y3p5TjVFTGcKcqP5Y3Yb9JxIBg5a9VYj2DfX3dkp0QNT
            PK/elDLeq2foT+MDLX8ukUnf0n/STCaZMvvmmnnt0NiqzelDRZlvSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:12:27Z"
    mac: ENC[AES256_GCM,data:clMEmFyNzsopDoY15oy2dAWQg314N0KbPnHAa3DO0VAXhRYllcoxZhbg9yfu6MEdI7w3QlxeMNHW683UAFZffVzAdwe7saJu3QKhobC3xz00wkc3GJomUHxO5Pu6sgUFfQnzzh2ImaLq24qajAGaoROkHDSTmLfNzO4ZoHb5Eyw=,iv:zuJrkkQlVIuRTQjfDMt1r0J1P3zfyUgBBABxs+jmGbk=,tag:oCGZ1fkSrjfcFctWFhz9gg==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ//e42JCDp8MKEhV9axQi5CX5jI9cE2iCjJLJhbH95aCH4i
            xj7eSESpNINsoYdIqEMZWXbMFE2CxiSE9BUX1Xo+u/FGAOt3KJ4GPeckjkSwPpAD
            GDBXcXBd9XN6apyxme3CTgsaXblHn+e4kXE8tY1Q3nKgwzAGgExO3fUhgTTNg26Q
            qLmMiFGjmGcIjo+eX3CBAImSnjxkjlqB86gPymgiuJxIMqn4lTKX3ZIGU2bjDBms
            kdgNVDbLqjqECd5mUlEfGmiQnvqYDNNI+VYsP5wgz2xeUerN+5LH1KI27dT11Z0W
            1YF05siHl90onOCQPxHhZWlcjEUJm/tddJLUvSvanX+YQPVEz74RK+HDFHjEYgrh
            7cCbNTOdsHZPIlk1EdcNm338qwcsMLMs4GO5WaPsamw+f+sES43CvSG9gHzeLZxo
            UzdvcF7bF5InUMf2uXhLUS8Zt/CUBs/saP4SMIsvKg8pYYvclqri2ocReBKcxkzT
            68/aEda3zlZ5/2VDrdmLUuwPhPMF6FyzrrpXDmbJrHR/p/XOmcEPFdqlHjPKWlk0
            yI7gY0VelZcisHAoDALev1Kh5vKeB3HYzZLipAPbJNcQszu6xt/l+mfzEiXuQdmM
            Ke8IfKRwI+6PRC+4mBu2FobBYkQfV1v3qRMUAr97aeaz1BG7Zt06k7dhKBHdWmTU
            aAEJAhCS0ErbryEhEr3071nWdvOX3qZnXy1B+br01acdxkPGXg4F4daLayINrYDW
            1FQOu0b9oX+20LKKo03S7lakh0AK0bUhN7jO7eKDG5HElNe9PO+Rzn22D05tBAUi
            QiWRDR1EEsd2
            =iz7K
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
