# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-studio
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aZ8/DJGYSs14BM2BERE9s61QxK4x,iv:JwP0S0/FdeV5ivWj2qKGnTGXGEhGki9Dcc8YPdlb2xo=,tag:WU9qNkNtE6dnBwwIEJlR/A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dkVwQd5O3ycUEY/5DfHE+llFnlRWxYzxDq5ZTLouvl6YlQN/sw==,iv:nRG3f0cuoh0VmzTbl0a3bEEUqZgCb61RYSFkbqhLx1w=,tag:dHB4MPtJlAjh8Hdn/YlYtg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:BbolXHa6ODjMxM21kybEHs8r5oenVu9Dot1rbSt3Fo0=,iv:7a1ACNiXVJX4ODE76Uc+2sHtTAWd/Lg7ygYDZhvhbKE=,tag:jvD2DAC1xZOY3MS2SX1RwA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ZTBnXw9BrLY8bzIJsIEanGTmUA==,iv:k8HdUuQ6iKVfXQhIGhE9Vg7NvrD5ro7CObwPq9Uv/vg=,tag:TDJe58ltEx1YxtJ4GhE4BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T15:25:44Z"
    mac: ENC[AES256_GCM,data:snhi1FiBVI47A7+SE7zC+nfnEvjIMwNzPPblicFdzbjbIQblK8rIWa84PK04SzuD3VKVor1BOI57I/CjAWla9r2gnBfnpAX1pGug9ZPjm5Wx3uWfhAkgGMF7QOkHk6+JQFGl4iYKJFRSE4zJyYImpZ6h1d6hAUSbGjDr15LrjeY=,iv:sKBcralmF2DYtKBGHw+3ypIws9OBH7Bc4I3CYBXaobI=,tag:H6ZZwco8HnYJxhQVUFiiWQ==,type:str]
    pgp:
        - created_at: "2021-11-08T15:25:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ/+JSrGr5v8NFMta/x69iKLcDOqkV6SXhQyovp8FCJtfgm0
            gTinW6Ne9KCwZQ6Kl49FjvH3FDRjOcVZvu7f6rNZVW4EkQqXTXHcsygQqgPlS7Lm
            vA9hW0bE3R7xIEYQwFKv35MWnlprHpPBBQW5cTAcR4l8Hqfay7ME20qPUjQL8BK3
            8mRYAAGjxVDs7MNy1FPSdIMdYTEuNRpFMAbYPDGbV3SPYqmVwrRemqgmxyeJHC+Z
            ye2FQrWFlmkdHlMXofz68T3DdCYkOA3RhzCUSM9bQowUq82ZDmxeaZxWy7s3XRT6
            8WD52qKSixG9x2QWH+oN1ie2+tFiCwyrZBcZJcTRA0+Lp5SZnHPfrGCIxb1+dS8G
            Y1PhldLMzH8PPI2CtJ+D8MTGsqjEKijgSnH+0WzAo3lpjJNEHo4xO4O8dRPW61fc
            wjq/KBmamkLuurKLupcrqeD87CbcM7KkR7GzDphaFMczEU9HCOMKjHjyORPhp3ao
            yau06AhLpax24rKuYVad7aAwer8pKigEHiE42WPTIeK1Aq4aP8tq6sNbZwVkPYUY
            v7EjdH9ht08WL5GpauJL/i+SvKLpwEUdE+U6kk/nXJPChqdP9Pwk89gZsb2xUieS
            +blN6DYoJ24+UkYOLQfLI6fwcu3XYZHvuntrWq3XNdb/d2HNOGKCZm4/Yrlr+s3U
            ZgEJAhC3Mr849vaKeyBbQ6PTai4Au89I00WALTHOXpxqbps8Cjp2RZfFQvSU+QxK
            mURQvekM02lTnOPNUkk5+l0GZHHpWkBSrjfNwKASISsiUvYcdihQ3Clm3/n78LGY
            k8x89CX6uQ==
            =HuR7
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-08T15:25:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAya3vz0coYGhD474DrDpWUNzYfmlqwkeeXuef2nF14YP7
            zwYrWKEx6NI+YNPHYDkCpjM22boJqf2y4XIiTDCJgl0T6p26sNNwztIQFIH0LJVy
            Y3O5oge/Phe3oYIWd5qjeWWgTuKOQoqLZcJOZ1cD89HxQ/eG5YgkvcMUDyIgxMgn
            GfXMXxD/tfZqmmUlbYAurq+GHOSrzaDOHjNrA77ZYPOrN/0rQSK6aizUk2d9f2x2
            GHAMZA9pQM6qQdwjx4TBmHHPEojRC5lqATxnzvUQ34ghhcDaePtr27eesJZzKMiW
            T6B3YyvNCjLdXBq8jPXZqfMg5CbOv4qufCGpGT8D4bIa0YO1GOLr3a/MEIJAOjsz
            umv1QelGSF34aUmikBVYPVGRAo9Mx6VvXlsqYmsGkQKkZOIO2MYvtm+4Rewve6MK
            JPoFPiPQ5KEPkpNgTgZeB6bFsanju+g0YhZAgbDUqOu8TwQnnd6uNMQepFgAwY3E
            taLrpYUuhn5w6SxAkbkfTsuFUNh565qWtI/YJXc6iz4+Phye9LRKOcNHNAVX3O8b
            3TXemLNR58dz0Mw5pgYSmzT9R/4eiPduwJ8ira2nR6byajTOCA5vvtficzxfwhzC
            Y3NoqJwyJcJsiHapd/f5bwhoUqGQGbMTlbv04OoyphUZT4vDriHwFUP9OxoBIMzU
            ZgEJAhAzuov2gIwCR7cR65SB3VbyGV3/4l1e5Bi4tWfjEltSucnVuJ5tt5vRfNyp
            QQerXd8zzvIosIJNxr9f62iU5gBAgi3w5VQ3uirWwCIjJk9sftBSxcG/Fv7tklPK
            opkr5hYzDQ==
            =1f2h
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
