# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-studio
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aZ8/DJGYSs14BM2BERE9s61QxK4x,iv:JwP0S0/FdeV5ivWj2qKGnTGXGEhGki9Dcc8YPdlb2xo=,tag:WU9qNkNtE6dnBwwIEJlR/A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dkVwQd5O3ycUEY/5DfHE+llFnlRWxYzxDq5ZTLouvl6YlQN/sw==,iv:nRG3f0cuoh0VmzTbl0a3bEEUqZgCb61RYSFkbqhLx1w=,tag:dHB4MPtJlAjh8Hdn/YlYtg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:BbolXHa6ODjMxM21kybEHs8r5oenVu9Dot1rbSt3Fo0=,iv:7a1ACNiXVJX4ODE76Uc+2sHtTAWd/Lg7ygYDZhvhbKE=,tag:jvD2DAC1xZOY3MS2SX1RwA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ZTBnXw9BrLY8bzIJsIEanGTmUA==,iv:k8HdUuQ6iKVfXQhIGhE9Vg7NvrD5ro7CObwPq9Uv/vg=,tag:TDJe58ltEx1YxtJ4GhE4BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMkZIa1VjWTlCbWJIbDNW
            OTN4T2syVHZnWlV1bVhGWmY1RmRyRlY5ZTFJCjdINjF5WGc4UlRNbTFscVFkSCtI
            bHV4Z1czVGpMYjExYXg2N3Fna0taeEkKLS0tIFp2L2llMExTemc2OVROblFrMWZF
            cWRHc1RWaFphaGcyb09aQWRTS2E4YncKkB0EVQoDv9yEnD6g2wUtJfHF1ITQW+0r
            Xdjrmbhw/Nt6TzcuUWMlZPgdoz+GEvX8o9fQ6mHoyyNXa02kxAEv6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-08T15:25:44Z"
    mac: ENC[AES256_GCM,data:snhi1FiBVI47A7+SE7zC+nfnEvjIMwNzPPblicFdzbjbIQblK8rIWa84PK04SzuD3VKVor1BOI57I/CjAWla9r2gnBfnpAX1pGug9ZPjm5Wx3uWfhAkgGMF7QOkHk6+JQFGl4iYKJFRSE4zJyYImpZ6h1d6hAUSbGjDr15LrjeY=,iv:sKBcralmF2DYtKBGHw+3ypIws9OBH7Bc4I3CYBXaobI=,tag:H6ZZwco8HnYJxhQVUFiiWQ==,type:str]
    pgp:
        - created_at: "2021-11-29T16:02:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0JxiGeztV1CAQ/+KPvHKwvu+iD4GGSPvzR4s45OlSd90cLiYjri6lLy4LqR
            sODWoi3f8ApdkF77myQEPeED4rQN/IMcoLuI1CDpx0zW+kGvP5jbZ2Sai7IDni+w
            zkqZQZFXDVlABJsMqiQxBtdreRugDWRh1qdrV9iJH1VT/HPZA9+1TnmrDCWECOET
            t21AHnjtrcmWnvd/a5MuPMgpBhBp6KYuhlr2qFD9kncX7L6Fg/m1729fLyvyOlwQ
            U2y4HKUC6t6JF8sIK+jt1k3Otg6xnRWZebIicQEOQxMAXAR73VnrC4vl6LMAGLAD
            n8ILWcT13sF2h1m1dpKBL76Fi5qfoLXu5Fn/NviXUJd731Pt8tKhiXGZPy7m+oT/
            5LfYjH6GGex0/6Gd3KmSqrtW9PN2bhm8IpFlWTdVXEQGIKmSUnOVN9zm/3+Sdp6A
            ewNLOhVPn+zwe/fTddNprOlIq/sm+cNVdyJukm1GAmovC9cTDk6dnO3IVfviLVyd
            3/AmnIt2CSH0eaByVfpvPEL7IS9fQcaO02XWAxQdxEhebaoVvxeQZQRotUDUPP5B
            wTtUQVZr20y6Tbv6Dgrzv51rQhttcpYY4lgkLRqsHNMrGmT1aVM66nqz7OaMl25u
            7vHIT7urbE3dTC56DI2w1xn4p8FBqrlYGj5gQy+JZSWGI6gsklfmkOLvEhJfs+XU
            aAEJAhA73srdFVicarP7BiaeDnsPywcvmStF2v7D1IMJWTROuUb4vWpfl8thhTcF
            2CFzVPeJeUoLRGeFkcPEGVarjMsD3WT0px2S6iQeveERF9oYe2U3gk0R8I/iE3pv
            9IOy3bRxpYWf
            =N3+l
            -----END PGP MESSAGE-----
          fp: FA9B76A1A2A613F2760642200B6DEB2FF6B015EA
        - created_at: "2021-11-29T16:02:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ//RnoevcjZl6aa3A7m47bJB2AhWvniZQB9LH8kKmX3ucPF
            r4u90C5aVT0D2q8NBk0sXvLCmQCshdMXFjW2X5GqVw6wi+fkIXA6+O5gf6rLkAxe
            3yfkY3du9ihWxrRWxkDTmfSDTDIAhjfxaNtKT5aqj8Ys1a8g5j3O1l9Ypa5l3T53
            nWEU44arptSh50m8e+/d7W5afmNa45dEn/wD1Vu9Xs5ydEJjlv+cm1d7j26Yr57B
            5dcoIZuzv/JnIU04Zb6rBMMpF9zoakI2SitmTW1wDzQnFB5w4wOAXowugUCElW8c
            ROH+nZu8lfQnrCMgdyog/le+/p1vgkgs0VjXA2NZFfEIK281DqIDAjEzAUVdtk8l
            HlEQRxJkBM8VaPoLe2qPKAtTtRJB3A/mMVjSY/qLophM2fmdGqIn1hi43HaVJr3r
            dg+6P36pjQS7rVTO2RZ8Ny8uBEdIj06NLpCn/p5x+DKQ9LgrXCVpeWWqD53N1Kjs
            B1FFvwrO+d1WJCWsl8bo/dKPwi/TqsGwSXhMZhydGyVl+2Z4DEQpfd2E3EZ3Lbic
            3ER7K4aOugVif/rbtUVUnQMmOUPjf6pg6/S7gtUwuSZ3DGPPuKVLWHI2fhnvS95q
            GQVYkzmgrA/sFZhXFisuwr81BfnwuWN8FfOKzyGfM6C4+xCZDY/wTQN7K1JQdmTU
            aAEJAhBFFO7ia7lK/1gqj+XIw8MQ/8JJ1GF7S4ITaI6bn9J46bKtgRYlbFHG/Lvd
            nuwHlFU/zpmeEBHmiwRagRJEGqQaCKICNiG8lmysyv0GNISRnFN2X8hEnqzGpc2E
            Gs4ROh6kdvr9
            =5Pfs
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
