# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-studio
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5ceap0qoNL1UJMgMqaF1DLIKvknT,iv:JwP0S0/FdeV5ivWj2qKGnTGXGEhGki9Dcc8YPdlb2xo=,tag:rN6Mp09AVeqgrvrNvsC/Sg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:GwgbEOVHO2WyeBjCmhNNDGlcXUQTuarIyYzXWK+zJ0++ZXU6VA==,iv:nRG3f0cuoh0VmzTbl0a3bEEUqZgCb61RYSFkbqhLx1w=,tag:u/meIxYvZB7gGSxdkySC9w==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:MLkF7UfBHylH0ThmNdREx8pEqNP73YnuX8+4oc+okKY=,iv:7a1ACNiXVJX4ODE76Uc+2sHtTAWd/Lg7ygYDZhvhbKE=,tag:395OTa0fPQf7tbYzCUllnw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:q87UIJtb024+2g7rL9YmcpoSJw==,iv:k8HdUuQ6iKVfXQhIGhE9Vg7NvrD5ro7CObwPq9Uv/vg=,tag:jjr2mGyTQ4xBVSa/bx4sLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUl2M1NwRUtyeDJuYVl6
            T1k2akthWEFmU0JxbHdMbjh3L2hnU1U0SmpZCm0rWHczNlJHWUlaNThFSU5FVDZB
            c2kyK2VZc3ZYenVzVFlXcFZQemZsR1UKLS0tIHlxZ0E0TFZEbEt4aitKMDJsV2Y1
            SGJoS0U1cmxxSkJ2M2NpUlJHRXVnWDAKZ6Jvl8+RKZIFAnDcgDljxoY1snkHMoOQ
            efkHMrWyThrKZCKR3SAYEBMVd/xIsUe7RWRR1MXM00XZhdSlbCqcbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:39:23Z"
    mac: ENC[AES256_GCM,data:1X2iH5VTbV2WklKxFaFIfamG/7I0449HEsB94C/OBpsW1I/Yyf3eAVNnNlJnUlRIQgSftwM9OUanXtJth8YBGzBH1CewNS/dkciXvQY6a4VvUckM9j6JXMYkMikopmPehaO6QtzjIMTx9xEus7QFJWBOUN3LwpnDtaaGrGzQwdM=,iv:yCnGrA7B1/tW13XuFlk1GScbPDAMw8Wv9wDPw5f0Jok=,tag:BMfYg3djgGDc2GbvaYH+2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
