---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - default
  - flux-system
  - git
  - kasten-io
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - tigera-operator
  - tools
