---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth
  - calico-system
  - cert-manager
  - default
  - flux-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - tools
  - kube-system
  - website
  - rook-ceph
  - git
