---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/jackett
      pullPolicy: IfNotPresent
      tag: v0.18.729
    strategy:
      type: Recreate
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: ""

          kubernetes.io/ingress.class: "traefik"
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
        - host: "jackett.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "jackett.${SECRET_DOMAIN}"
          secretName: jackett-tls
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 1Gi
        mountPath: /config/jackett
        #existingClaim: jackett-config
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1000Mi
