apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik-longhorn
spec:
  forwardAuth:
    address: http://longhorn.${SECERT_DOMAIN}:4180/akprox/auth?traefik
    trustForwardHeader: true
    authResponseHeaders:
      - Set-Cookie
      - X-Auth-Username
      - X-Auth-Groups
      - X-Forwarded-Email
      - X-Forwarded-Preferred-Username
      - X-Forwarded-User
