---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: networking
spec:
  headers:
    frameDeny: true
    browserxssfilter: true
    contentTypeNosniff: true
    permissionsPolicy: geolocation=(), midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()
    customframeoptionsvalue: SAMEORIGIN
    referrerPolicy: strict-origin
    forcestsheader: true
    stspreload: true
    stsincludesubdomains: true
    stsSeconds: 63072000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure
  namespace: networking
spec:
  chain:
    middlewares:
      - name: secure
