# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unpackerr
    namespace: media
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:q/1tg6uRXvTVMTIxWOor61h54z7TRRRSo0yPecHXFrc=,iv:oseLfQuPvbKnRiPh2MJPaJGThgqnFD7AHHMGgNJ+vRk=,tag:w3skrIcaQ0+jKPm21FDzAg==,type:str]
    UN_SONARR_1_API_KEY: ENC[AES256_GCM,data:AMoHWaSFTthmClXcEudtMOmdu4A/VnHzhpOjXd5qYwM=,iv:4Y8OXfsn24wIilH8I1O//qqUckwm5EheesQTg1D60es=,tag:k+qGUlo4JHY84h3AsBN7JA==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:2RJS8b3+YourtRz0r5MaFqUnEj2LFNGXCoqqWw9IZTY=,iv:lIhRHuluVowJpi8v/4n84mfoHPRcgSEsjPo4xdacde4=,tag:1FFp85ih4OknAAEnS+WH9A==,type:str]
    UN_RADARR_1_API_KEY: ENC[AES256_GCM,data:HyBQtHS1wbeTSL/x952E5o7ao/fzg+HZXzP4+H0lXaY=,iv:S1fJeYsdKHc/HScnIuUXJPA2NHDPSSDE/FVvHBG7xes=,tag:CW4sY+kum4m2blvhWt5z2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMUU4MlJjVzdBL0lOTXAy
            cFBqemlHRkczU2d3dTdZZ0ZrdVZOOEdldmxBCnNrdGljMll2d1dlZUp1bGsrUCtQ
            S21pa1NVOGlwREU3U2R6RDF2YjdoN3MKLS0tIGlMekhNcjkyZ0UzV3ErdGowZE94
            ZjNjWVBFYmhFak93Q0RuVVplaDcxWGsKDg7/8zwedKSuIAe8dq7fMxcrmVqv0Q1Y
            4qf2iw5cMPh14UqGYy8+zBy7h1t8JehjuBCOBqvIwOi1g8Kiq9+oxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-15T16:55:11Z"
    mac: ENC[AES256_GCM,data:lpcL9J9V5nnXHBq/Sx0T9deMYwxmu6/1CBiDFI+xjzu39bihtzZFgNCzinBUGr7W+nCrOLdq0hHz7lC0vbrMw7/grfX6dZ5Um/7c+z+pkWMF9VChUHkv1edarzVQ0h91K6EGEL0nSLlv5TV5QW06es+NAbFmIvRUPnJjUBULybU=,iv:psoSGsp9+YNke8j+pqkq9+DeVWryUTOnbpUW/5McHpU=,tag:y4JJyGyn0/SPe3sXO0y96Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
