---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jetbrains-projector
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jetbrains-projector
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      # -- image registry
      registry: ghcr.io/k8s-at-home
      # -- image repository. *MUST SPECIFY AN IMAGE*
      repository: "ghcr.io/k8s-at-home/projector-goland"
      # -- image tag
      tag: v2021.3.2
      # -- image pull policy
      pullPolicy: IfNotPresent
    # -- environment variables. See [image docs](https://github.com/JetBrains/projector-docker) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # ORG_JETBRAINS_PROJECTOR_SERVER_HANDSHAKE_TOKEN: "admin-password"
      # ORG_JETBRAINS_PROJECTOR_SERVER_RO_HANDSHAKE_TOKEN: "read-only-password"

    # -- IDE settings overrides. See the prospective IDE docs (like pycharm)[https://www.jetbrains.com/help/pycharm/tuning-the-ide.html#common-platform-properties]
    # for more info. Default config paths will be /config/* E.G. `idea.system.path=/config/system`
    idea: {}
    #  config:
    #    path: "/config
    #  system:
    #    path: "/config/system"
    #  plugins:
    #    path: "/config/plugins"
    #  log:
    #    path: "/config/log"

    sslGen:
      enabled: false
      certs:
        secret: ""
        crt: "tls.crt"
        key: "tls.key"
      jks:
        dest: "/tmp/cert.jks"
      properties:
        existingSecret: ""
        key: "ssl.properties"
    ingress:
      main:
        enabled: true
    persistence:
      config:
        enabled: false
        mountPath: /config
