---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cdn-nginx
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/coolguy1771/nignx
      tag: 1.25.0
    nameOverride: cdn-nginx
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: "cdn.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "cdn.${SECRET_PUBLIC_DOMAIN}"
            secretName: cdn-nginx-tls
    persistence:
      data:
        enabled: true
        type: custom
        mountPath: /var/www/html
        readOnly: true
        volumeSpec:
          nfs:
            server: "osiris.${SECRET_PRIVATE_DOMAIN}"
            path: /cairo/Media/cdn
