---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cdn-nginx
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/coolguy1771/nginx
      tag: 1.21.5
    nameOverride: cdn-nginx
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: "cdn.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "cdn.${SECRET_PUBLIC_DOMAIN}"
            secretName: cdn-nginx-tls
    persistence:
      data:
        enabled: true
        type: custom
        mountPath: /var/www/html
        readOnly: true
        volumeSpec:
          nfs:
            server: "osiris.${SECRET_PRIVATE_DOMAIN}"
            path: /cairo/Media/cdn
