---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: stash
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      # -- image repository
      repository: stashapp/stash
      # -- image tag
      tag: latest@sha256:ad72b66e65c0673c218bb4f42b116a9109189f346aabd875fe63f37e6e63be75
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See more environment variables in the [stashapp documentation](https://raw.githubusercontent.com/stashapp/stash/master/docker/production/docker-compose.yml)
    # @default -- See below
    env:
      # -- Set the container port
      STASH_PORT: 9999
      STASH_STASH: /data/
      STASH_GENERATED: /generated/
      STASH_METADATA: /generated/
      STASH_CACHE: /cache/
      DANGEROUS_ALLOW_PUBLUC_WITHOUT_AUTH: true

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: "stash.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "stash.${SECRET_DOMAIN}"
            secretName: stash-tls
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        mountPath: /root/.stash
        storageClass: ceph-block
        size: 15Gi
        accessMode: ReadWriteOnce
      media:
        enabled: true
        mountPath: /media
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: ceph-block
      external:
        enabled: true
        type: custom
        mountPath: /external
        readOnly: false
        volumeSpec:
          nfs:
            server: neon
            path: /mnt/user/appdata/stash/data
