---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - media-browser
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - radarr-uhd
  - recyclarr
  - sabnzbd
  - scripts
  - sonarr
  - sonarr-uhd
  - tautulli
  - unpackerr
