# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:VpK6QJITIlx7XnQpN4/Lw2vIxz5FjV2BcxjLlzniVIqqbArc+3M6Yw==,iv:drtuldUgpdZPKKZGbzhieVg7nBQNJiV/tH9oF6/JK3k=,tag:61CI6mexvxkELJUCHxF+/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVFlnR1QvMlFSNEFWYnlS
            RFRuS3lzamM1SkRldXpnR3R2dG1vQ1ovL3pFCkgva240QzAralJsUCtpbC9DVXQw
            dFdJTEhFUm5GMFZROTlPUTA2dWZEOVkKLS0tIExvREdROXJOcHo4cXE1eEE1OWlU
            aDQ5Qm5ZVTAzS2RkbE9HK3FyaUxsNDgKaqsrHuw0/XZiJocIE41sonT4MFY7DiSU
            yH/ImHUDHN2atKmYYgcEQuSwPujhuFMdM525A67PHkvLpz+4m4MbNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:09:22Z"
    mac: ENC[AES256_GCM,data:eavg17Zla8KiO+19JA9qhLaF003vitwgVndbz5NndGHdLboeJ80ttlS1+COFrfvuyff8MnSNhUoJnOckG5a1suawa0voi9rTt1RSVJXO93xaj8mV9qjWLAo9S/0f85kkoBVoMQAcbNBYnnCB5leTt/tyu6/IC9MEVgOIVY2j5LA=,iv:zs8Gofivn/7EnyQTkU5TBdO9GSx4ZjfDInhuMmMv0no=,tag:cCjcVFFhb2XkiczXLShcTg==,type:str]
    pgp:
        - created_at: "2021-11-29T16:05:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5AQ//bUtCc6oakFS3wptkd1LGIjQz7GTCZP3lkFawS66tq88b
            fkdsVNQtjmX90xJDi28Z1cTk4PzhhJeJpRdiNLm/kUvk7G7169Qbis79VhKEfdei
            R1FiOfabmIk9xWcTH57m9un6gg8i+DdIIQFnVAmVHqlVbo2ZcD/hVrQ4xRCtLEYk
            iN7IIvF5daW+jR0jCWDpO9Ezd8P2Ml9xZp10Yw02npM0Ddwv3L0Znl+VBmF/x1Yc
            wy5ocI1WEwFPIlwf5Pbftw4hmaK3rivR+xJxUi42ra5Jt/8huKPCqmHqQSAPud6z
            959Zka1RHX502OhajDYrLGKBlVQrt/D1P3z7eSY+esY70jrOO0R0qLYm9PR0ohSU
            0c4VN3IKnJRuaDDC0R1ua0Acc6PYXM0XbFO1jMoOBvFbtxWgK7fqj6cMyuGV0pcb
            58k9YFmTdNga1edJ7aiDJAruHqhN/h8KSppx4pH6foBjxG/0zA/Ncbtfcj62QWbb
            2F4usQXYS4SYNjR3eYXwRNREVmiHZ0u6FyE+jIe6KAPsQH1VaUfeVqRQ2Gt/uJa9
            KzK94KRVsPHNsO/5KDcBEL3+rPBZMlvvhCP3g1ZZQlC4iphqS2iSiQMNN4H0Jt+m
            d7WK8hi8/J0Oz2HxtCp8/dIIRnNgOvTSfx1bPrmzWyE7Y/pyry6NVgT5cVq4Ig3U
            aAEJAhDqGvJrcuSUCpqNnc6rlp3SiYB7N3pUSRZicHGR33Mr0Nij0W1FQsoS9+8H
            VTwkTQF55faURv8Xz9Hys7ffsW6ghg8eaKjvlmqXU9eIX/NDXJOGb7F80QDg9Zei
            wzEj6EdQMrgy
            =TzrA
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
