# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:e2mv6R7ZffaVVmZTkErTx4vQp6AI5QF5L9Gz5ZfCv0M/3/HC10eylA==,iv:EtL4LAawhFXrVBuTjNe0otXqcGObPlPf5X5cUm28qk4=,tag:Lt1ISy3of10dT51RhZxk2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-03T19:30:09Z"
    mac: ENC[AES256_GCM,data:tYHsbABKMGNNs7WU4kuDIgIaJY0YKjsX1m6k9eQRxfCjGSrQkJqtdom8kAEwVDmTKcoLia9j+Lct3b1DZStcVhELJR6TnN7Jd/sT67IBxjYiJQkS1Nc2lM7f6DXaL1fqDcNEsydLTdTF7q/Zodhh9sdq3qlwPu/tZv6OL22GIuc=,iv:e/YHQE7ebiGBGJrvGBwyl5JaHM4uEnnQuS+fLp7ZdJQ=,tag:qm6QhK5/Hh1Ho4d//bSblw==,type:str]
    pgp:
        - created_at: "2021-11-03T19:30:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6YvMuRc2PZqAQ//Tb63spc7CSwItF9TRuPjES3oC3YaUHIa2V36ZcOZ1Ii7
            Da+WdtCCzYJC4kfXmRIJCV/WIvt0MDYf6FFRHtbZPEQPPNwyq8bo46rWRZ+jpWCD
            NJJ2HNQnfU15NDoKODekgxMudz8WsI5yNbHVACRih2fSgOITDTveyIhAvDNslrG8
            +MjJwLzXjOQ5ebKquvOehWby6XBUywgVJKcn/cIvYY2g2VkeimLbNerE9FOHu4hE
            HkKSErvxmnno6PoOSQ7Jw9JI2yHlG0EsWQLznEN5G6aiVkiNI03ehB+FoKd2VwKV
            M4L9r9LQzcNalFCS5ufOxjkzEQscnH0bhbM/P3NWaATz4NFJZr/knry6kbbWlWU6
            XdfwonxH4iADCOioAHDX0Q+hzqhBVStNMIiEG0kEOy5B1nsARU+zmRVY4cV0czsZ
            EsnvmS+uzwviawMrwqWUrbxnpfWu7Mw2a5LHv3BdYkUn4q/lP4O/rCAUq7wSvlVm
            vRAPqT3c7KSYpYpFN61MWxHyyirRDCTxuPt4UVtIDN82gDRiBEs1nupnIYa438fK
            s4iiuYWSx4FLS6j1dUu9P/jO2Ia5sl/ZBPTizA/nNeB43M5kxwC8347WXicqaAnC
            SFkKt1WLb3pJRSY+4Vm/2IosCjIScxMTiPoZwRLjAWN8vX3vJ2aYS/uXj9dQhx3U
            ZgEJAhAPWrrp57aVDwwH0fu0ITByuIstQFKMLqzNvekM+NdIXPF1B7MM5xFTP5A3
            XSZ1GgVss1je300Ywh+ceB6PBqLlp/MVegxH8Gkfo+WuE2l5rpCsvmhSn2Pruk+n
            wczRkZI2eA==
            =KhVv
            -----END PGP MESSAGE-----
          fp: 86B2157D15BC53A36FBA055FCC5C3C333A4093D1
        - created_at: "2021-11-03T19:30:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9FqixZt57HSARAAmUV+rzuHhSugtIy5d4/yKXCD9wWIZh2F+ykrhfUdnA9g
            P2eqEaJxV/PY5+lvoYTCvIb8AsefoQyNxdYvkmLqF9L1ettkTtHheOAHQITRgUVX
            7Uc37cCLjqamSuRJYerTU7DlwLz5C9MckL1AV1J1uSuQT65MhuOdieNmmU7yAEA2
            18jr1MPf01LN27qq/gHa6MMyYvda55Ye7NpahhLS91Fur9heGbY3ByOxCyPUYc2Y
            b2+Zp1USLHfBHRyBIln0T7UzXUOYhml7P1nDrvSBGrsL75+ysag2xObzztyNtzFM
            yhGjI8TH9QKcaIZgEWVFNbB7POnA215L/3wN4qO2oyL6Jd48Z22ozlsNdBXF8UuA
            CXIY7nygmripmveduLStmWhe6+ya33MR9eLvGfzg8n4AgcBn8DFclnlxEvA1VEsW
            3BiJY4c4y4/46da14gBjd9ajrQ/4YwuvhLeVSfQRZIsrdfELO9iUFlReWbT47ZHm
            nmFj0hl3A2ZjHpCqR/18ls/V3YwOrMnB85B9XGx1iWJKP7cwWUwaqXVGg4rIv3Z3
            GPiHFi4U5MYU3+SBoZkIaiC07QclctXOQT7550EU2lVxcQE68dPaj+KHUyAULUlM
            gTuQm2xUDSNUcikc7FLw1OQlAS/96Iz7dJunUUO5bkJxCuXa2V6YghbiverquHDU
            ZgEJAhCq2RbhcA3YfrHpg8n32M7MM16e/FzKUpiQy1CkHq6uMLKlRsQQOVXm275z
            io4LJSSu/wiWwxWz1vp7IEyEBjnHnSCv4UMS8DKJ+NuvRHL8XaunVakpbVKhVd9z
            O0dOhMkK9Q==
            =eQrA
            -----END PGP MESSAGE-----
          fp: E04EE454BEACA869B2FB211472C2E881FE50E35B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
