---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotify
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: gotify
    image:
      repository: ghcr.io/gotify/server
      tag: 2.1.4
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: gotify
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "gotify.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: gotify-tls
    persistence:
      config:
        enabled: true
        existingClaim: gotify-config-v1
        mountPath: /app/data
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
