# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: gotify
    namespace: monitoring
stringData:
    GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:uXfUnJX+eQ==,iv:gRAoxX+pkoaV8bMz6Jx1ALlcgN5+oN8dnMIAypI3Qb4=,tag:9l9Imfi7ikpgMEs7NVVgMA==,type:str]
    GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:luLhqMucFpcIGA==,iv:Rj6hEdhzeGt+bC4STeM6swo/Jhyiu/l8JvB5rZGkGP8=,tag:RDPEHgrPjyV/ADcd4Zn5lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ3lWR0hLU01UY2R1cE9q
            Z202R0x0a0hUT1VPNGxyMlVVbzlVdzJwNm1VClFQR0JHcDZ2YlZCeDBGNi96eWp2
            NzQzYXQzSjZud0N6SVpyWlJweVhEQ00KLS0tIEJEbWxEc2NwK2xGanRDZ2tpTS8z
            UWJIaUdYTkdiRUJTekhpUkNBMUcwWFkK96UfotdXqTODZAtg1vJlMyc1PeMPc0cP
            NKMZHf+ipKKMfiP8+Vz9c91uf//6wnJZx1SCDuUHcXFn8i1OMJcc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-15T16:11:26Z"
    mac: ENC[AES256_GCM,data:J7R6tdaxKXF7avMGU/AQnUD2mMj7YxpRLkNqJ3K2dNG0pRAz7GVliS33DMLXyMBhK/kgy0jYCkoi9RGbGBlEuunnmlHxpbU063iUnauQTgy7RyuIILwyxPzFWwj6qmkAGUjr1UPAnvgdWnUW1XyqdDy9Vzns+vmM9wRrKYwIHV4=,iv:2VDnIa6gTw1zU4K8U7yPAECsKboTOjeps0XJxEt2y6U=,tag:oO1ASawFqTrYHroREWFY7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
