---
# The interface on the host kube-vip should attach to
kubevip_interface: ens192
kubevip_bgp_peer_ip: 10.10.10.2
kubevip_address: 10.0.42.2
kubevip_bgp_as_number: 64512
kubevip_bgp_peer_as_number: 64512