#ENC[AES256_GCM,data:JOUZJ2wNBxbbvJ16olpLy3M=,iv:zZt9Y1h+JeUuuFVY6z3sRInOaH3+JgCd+B/hZTmBipQ=,tag:3Wu9I/Asb1ZwruyLA0Shjg==,type:comment]
kind: Secret
SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:4c7yezudpzjEbbCkVrpa7BzMA/4=,iv:hAGvPZAG+wxZUENN9sSfzB93qSJ2NWhDvaCLuLq34E4=,tag:CbMfVKjgD6Kr6NKRxd3FlA==,type:str]
SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:/a2riGsqPWAgmtTOmXifULlQbEo=,iv:LcEhQI2XoLKANjOOJLyw8/zi3cv8URnlglTCzNJqInE=,tag:RTz6wQElibRzdOq5IGUDdA==,type:str]
SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:LgVhd4RqARV1oewrTEc=,iv:osxQ7CXYQ1iGkKPvT+TwtM/cqc5q4JElhIeJmS8OIvo=,tag:sh4DZL17xthoqlHwO0z5qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaEpOakxtUSt6UDFpblV6
            MGRJVXV3UlRIb2oxdzZYL2RpMFRzbEdIcFV3Cld2NkI4S0N1V0ZpalF3ODJLR3RW
            Q1hmR0xiYTg1dEFVcmRXTmQySUkxdHcKLS0tIEM0TWNmZytrZ0NDTkNZUkVUQnNJ
            UXUyNGFmTDVIWlZ1OTRsNTJpdHFJTTgKAGrZnb8oitsBjNlL33kRKlVwdarEXkpj
            iJqrhKhKYiyFdGxZDPI4Oit+QtDCctxo2N95YCt4J+3oGc2kYHhm/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-19T15:56:21Z"
    mac: ENC[AES256_GCM,data:dSByqAB/LIRNDNkeJqrvGjFqYY++7YyPVJ7S6gdQ5kEjnh4WGhL4HTzJbnXyw8Vuro7mRvFaBiv4y0wxiaoQqB40R1sKtDANOIByd0GFJeLxc688He3IcK55WbQ9BcjDXlO2PsXKdW7vLA1r65vkxVgffF8dy24+lT5WnHYu+0M=,iv:yDD2kgjyT1UmWHDwgxLgD8TO/dKSvAAP5S706m+lqTs=,tag:E26jjvbdcO0cyx6cLDQi4A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
