# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:/Of7sNUsQeNJg8oL9u/l4vNbu4Szdavn3evdjZIx6bq523iukM4GSslG+fhb6EhkH7wit7xx8bfYnt9RhgY/M9R9hZQlwdIC2nxLksNCsmMjAy1DVhO4tEAfomxd/9mKjD1qLJ07dhuHiNPgpghZBWHLtCWqDyf7MgsOkR0dlbj6v02btrrYXyA4mKygQz01hHrXtqXKzKRUm1mc/omqhvTAK+R3OStAuSJRqApY/3l7KZyCq4AB1dWBw6/BF2Xohmd6yi8mu+nekFnNy2va92gK5iaCw3Pt+fLUlOQ=,iv:g0cudliOWsLd0POgpeAUeWR6JiqK2dtHQcaStWtrbtU=,tag:ry1vC0xqh5NRAJkuiSnILg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnlQR2tQSDQ0WXpBTlFT
            V3VxQUxrUVZqMzcxd253WWtiUDNUL09FRHhBCkVDTGRCUFFWRllsYlM5a0MxK0xp
            R2RZakQ3a3VxY3dtaGpJb1J1bDEwVDQKLS0tIGxZL0NmdTVzaDNWK09HUUtjeFB6
            YTA5V2dIR09NSW5ReFZYZWtRVzdlbmsKPsmdFvaxeEOWPyFuU7LNh9w5XcPkL1p5
            oCUjnljZ++XHYFQthKWxecIk1lo0QwOzLrns5rZupCvo1KcsMNkHIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T18:40:09Z"
    mac: ENC[AES256_GCM,data:9q50tTZv7flknSBm45wgnGsQ0jpUoF1DarOw0fFCygACP6rytu5FuzZwvbqbGvXailnb7T8c+kXtG5WKF1LwNt3P/In/PvYnD2wQ8TqcLpjmK68vE/+EaxE1Y8soKGJx7Fez4h1i60nlreuczGzp7+0hZDlyZ2ozxvjx+D6ONBM=,iv:Jkn4lwByHpDUkbz+uMKrNFmJBIFNQMe1PSAiA6i8Oz4=,tag:BKsyMPA+iyJEyFJq0UTmPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
