# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:8Ke2R9DXT1nn53RrXqo1SK6wO+zxDuIM2AJikXSyrNpQAQ3gc9z7wbpuKQdPLlGWiYo+uZN38oMrpfdKX28eysX1/19sMMpUgsPEQaIIrwuONyXyCWWE8/ooVavhqnVHTqUx19XyvmgQAK++jW0qUDp6SFlXYCbBQKtntexLk/pOq+0XuRliuWvdU3ymJU55NVtIrBCV10xjusKZM0Yr0bVc1xLhViiE/fho8N1G4/z3O66MLivv3QSLmd0v98ySxCaNB9NoZjegsbqOSK5SUy4oNqtspxa3s8m8ON8=,iv:g0cudliOWsLd0POgpeAUeWR6JiqK2dtHQcaStWtrbtU=,tag:yHl15z6tSKxzh/fJOJp6xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1986cspgjd7xhdwfwmyplc5jsjk43gewedu7s3sr7gwwhrdp7rgzq6t4ax9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUVXZ2p1RGFYbVlhTGVX
            N3RkTE9qYm11N2RiendNYWdRZHVuZ0lLVzFRCmRRZTlTRG5CSFJyME1aTDV1RDcz
            azJ6MGNKa21VRStObGVhWlBHaTcvTW8KLS0tIHRGbTMzQ3Z4ODhvdE8zZWlRN2FS
            RGhyTWNCbGVYcXlnOWxueTFUMzFXZzgK6wkcXqPOH8gt4iUece0+0Ev8+VBvvDUy
            t6JGjXVrCZaoInlbHXWXBqcj995v01/zZZpq678NCHr8utxSxN8Dbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T14:13:20Z"
    mac: ENC[AES256_GCM,data:Skc7GH0aNxiOINLGeVY9pJsxrH2YRU/uoWTi7bBeiFL0C2yfmRCGhGVUGhF943IsOyfXbVSMk1uY3X2MYoMpOg6JQu15mskKFGDPswTXQ8X6fcmyD7pRv0pZvVqBDUpdV+wOcJ/Guqu0Y+Rv3qBnoay5x/pXvHazeG4tEWHU0vw=,iv:x5jcVEp/27TdCycUH/EJZDRK+LgOroAFsBJB0ZV2X84=,tag:Yd6ad9GsHEdnPEsrQL+bdg==,type:str]
    pgp:
        - created_at: "2021-11-29T16:01:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42gF8Fyehf5ARAAybpuuRtOn2W7OsMj+iBr1N0nFr4BEn+RX1jfK33H9xe2
            nnUJIedmLZl96sA0l6t0iWyGw6l+hVIGC3IlrkZ8XzZihCBzfakACStMuC4dCvgE
            e9dBifCGNom8s6VWkkgs+xcsq304Xh99EfcXlkbYhUfQOAykBVmBGYLE3TKumgjF
            E2w03DePHPmmx6mF1Errc/fgsgw75GZdpHtjtiio22/adMwtljUvbN0Ve705gGH1
            bjKgiCaLb3HlXqoGbCsZOYzurXZ8SPu+nJD9/tZq7O2G6/YaB/HDdVXhAJPaiRyF
            /bp1LRcnKQrQ0s7Qn9lwJwaG8EJECZ0q5nH5OJ4ndfMPILqRRZiLna2gudLZN7Fu
            F+MXyUFnreMehOSpyQyfws97NmsVvFTL3zC/9kPl/4jUUiNOZ+st3M4TD59WkDur
            J5Dp5pLte/rIrDfWBiENeU7mNvM50bb4keQ8nJ9OlCoLoAb8UsIuiFPn+3B6InfN
            F+EUK+gzkgUFHQ4cHTd0AvVt/N+df1b2D1Q8O7dlG4h4tqE+EvQOeKO4YLSXEZJt
            KeKYXfZUgSirShbcmtXwIi7loZQ7qXixcT3E4lyXixBD5GwAbVGi0OTkZmNnPckx
            lRNy8ZTgKCb7k7B5t1ypgWFTgfDKZCuVUyIcn5Ap9sYijgQYUgsDKAf3FAsRgcjU
            aAEJAhDfI9HedhKxkkcTUB4igz4fIf64apyV7xNEjWnD4RnNCjXo1is8+wgaGcmc
            /JtvTCcr+wDOHnNDO9FAgdjw8KIJWlk6UzfHJpZevTCFfvrqzSLAU7zwnY4CWkJu
            WtLpe87eEBOT
            =g59a
            -----END PGP MESSAGE-----
          fp: 65C16CA584E97C935AE482578967C1536E79773C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
