---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=
      chart: hajimari
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      pullPolicy: IfNotPresent
      tag: v0.1.0
    hajimari:
      defaultEnable: true
      namespaceSelector:
        matchNames:
        - media
        - default
        - docs
        - external
        - monitoring
        - storage
        - networking
      # -- Override the title of the Hajimari pages
      title: null
      # -- Default name for welcome message
      name: "You"
      # -- Add custom applications to the discovered application list
      customApps: []
      # - name: Test
      #   url: https://example.com
      #   icon: test-tube

      # -- Set default bookmarks
      groups: []
      # - name: Communicate
      #   links:
      #   - name: Discord
      #     url: 'https://discord.com'
      #   - name: Gmail
      #     url: 'http://gmail.com'
      #   - name: Slack
      #     url: 'https://slack.com/signin'
    ingress:
      main:
        enabled: true
        hosts:
        - host: "home.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "home.${SECRET_DOMAIN}"
          secretName: hajimari-tls
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
