# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: |-
        type: s3
        config:
            bucket: thanos
            endpoint: 192.168.1.147:9768
            access_key: hAtJ*t^CJdV*%WA@%d8p!CuAU2XxFC!6
            secret_key: ZK5J*yJVcorqemEFmgp$o^5et89xcxU^
            insecure: true
            http_config:
                insecure_skip_verify: true

